# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.sk
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win32/sk/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 4085913CC5482BBEF7C884D40A64296064964B2868191D2D2A91DAAB070401E5
  ProductCode: Firefox Developer Edition 145.0 (x86 sk)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64/sk/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 53AD5DB30AFCC224539D3D1A1096ED74C57A982C3DA94A968F4807640F3A8A97
  ProductCode: Firefox Developer Edition 145.0 (x64 sk)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64-aarch64/sk/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: B7E1FE87A613AF3E203E8FD15A37759984981438B77CA7407A2747D456C919F6
  ProductCode: Firefox Developer Edition 145.0 (arm64 sk)
ManifestType: installer
ManifestVersion: 1.10.0
