# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JetBrains.CLion
PackageVersion: 2026.2.3.1
InstallerType: nullsoft
InstallerSwitches:
  Log: /LOG="<LOGPATH>"
UpgradeBehavior: uninstallPrevious
FileExtensions:
- c
- cpp
- cxx
- h
- hpp
- hxx
- ipr
ProductCode: CLion 2026.2.3.1
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- DisplayVersion: 262.10968.176
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.jetbrains.com/cpp/CLion-2026.2.3.1.exe
  InstallerSha256: 7CF6BEE7FC60D61A1E1C9E255C86A29EE6622F9401E26B33022F65C686E9E94D
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.jetbrains.com/cpp/CLion-2026.2.3.1.exe
  InstallerSha256: 7CF6BEE7FC60D61A1E1C9E255C86A29EE6622F9401E26B33022F65C686E9E94D
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://download.jetbrains.com/cpp/CLion-2026.2.3.1-aarch64.exe
  InstallerSha256: CA70B2232A73E8E7B49AB502949814A29860D5984EB6F69CF8AB9AE13969788D
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://download.jetbrains.com/cpp/CLion-2026.2.3.1-aarch64.exe
  InstallerSha256: CA70B2232A73E8E7B49AB502949814A29860D5984EB6F69CF8AB9AE13969788D
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
