# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CrazyFigure.NoteBoard
PackageVersion: 0.4.6
InstallerType: nullsoft
Scope: user
FileExtensions:
- bmp
- board
- canvas
- excalidraw
- gif
- ico
- jpeg
- jpg
- json
- markdown
- md
- png
- sql
- svg
- txt
- webp
- xml
- yaml
- yml
ProductCode: NoteBoard
ReleaseDate: 2026-10-10
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\NoteBoard'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/CrazyFigure/NoteBoard/releases/download/v0.4.6/NoteBoard_0.4.6_windows_x64-setup.exe
  InstallerSha256: 25E3110A5B955E65B50F6E3BE5E19F1F8A5303CD101B211479E2B6B9911692CC
ManifestType: installer
ManifestVersion: 1.12.0
