# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: CrazyFigure.NoteBoard
PackageVersion: 0.4.6
PackageLocale: zh-CN
Publisher: crazyfigure
PublisherUrl: https://github.com/CrazyFigure
PublisherSupportUrl: https://github.com/CrazyFigure/NoteBoard/issues
PackageName: NoteBoard
PackageUrl: https://github.com/CrazyFigure/NoteBoard
License: 免费软件
ShortDescription: 集 Markdown 笔记、多维表格、思维导图与白板绘图于一体的知识工作台。
Description: NoteBoard 是一款轻量、现代化的跨端效率工具，覆盖 Windows 桌面与安卓手机，集 Markdown 笔记、多维表格、声明式信息图、思维导图、白板绘图、代码配置编辑、文本对比与图片预览于一体。坚持本地优先与文件优先理念：无强制工作区绑定、无强制云端同步，数据完全由用户掌控。
Tags:
- markdown
- 思维导图
- 白板
- 笔记
- 脑图
ReleaseNotes: |-
  新增：
  - 本次暂无新增项。

  修复：
  - 加入收藏时支持选择和新建文件夹
  - 更新检查限流时尝试非 VPN 网络直连
  - 修复选中文字后悬浮菜单定位偏移

  优化：
  - update star history
ReleaseNotesUrl: https://github.com/CrazyFigure/NoteBoard/releases/tag/v0.4.6
ManifestType: defaultLocale
ManifestVersion: 1.12.0
