# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Git.Git
PackageVersion: 2.56.0.2
InstallerType: inno
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
Commands:
- git
FileExtensions:
- gitattributes
- gitignore
- gitmodules
- sh
ReleaseDate: 2026-10-05
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/git-for-windows/git/releases/download/v2.56.0.windows.2/Git-2.56.0.2-64-bit.exe
  InstallerSha256: 52188F917B378F00C70EC136BCF090005F30D44FBC4EBA0BCE759CC6592D60F6
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/git-for-windows/git/releases/download/v2.56.0.windows.2/Git-2.56.0.2-64-bit.exe
  InstallerSha256: 52188F917B378F00C70EC136BCF090005F30D44FBC4EBA0BCE759CC6592D60F6
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/git-for-windows/git/releases/download/v2.56.0.windows.2/Git-2.56.0.2-arm64.exe
  InstallerSha256: B9CED78CE371577DC966F50AE571909D6731E36D31065D35C8EFA21544C58BF0
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/git-for-windows/git/releases/download/v2.56.0.windows.2/Git-2.56.0.2-arm64.exe
  InstallerSha256: B9CED78CE371577DC966F50AE571909D6731E36D31065D35C8EFA21544C58BF0
ManifestType: installer
ManifestVersion: 1.12.0
