# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Nimbalyst.Nimbalyst
PackageVersion: 0.79.1
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
FileExtensions:
- markdown
- md
ProductCode: fe58d461-527f-5843-8c07-27b4ab6d3d90
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nimbalyst/nimbalyst/releases/download/v0.79.1/Nimbalyst-Windows-x64.exe
  InstallerSha256: 274AF7416840D2BC92B87A7E0FAF5C6C8FB883EBCB1A2637A3AE0C13DB9B6CC2
- Architecture: arm64
  InstallerUrl: https://github.com/nimbalyst/nimbalyst/releases/download/v0.79.1/Nimbalyst-Windows-arm64.exe
  InstallerSha256: 56A7A8E743A5F8D5F2FB1E9A0E8760A4EDE4499BA7BE2A64AD3DEBCDAF06EB69
ManifestType: installer
ManifestVersion: 1.12.0
