# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: JetBrains.CLion.EAP
PackageVersion: 263.6800.10
PackageLocale: en-US
Publisher: JetBrains s.r.o.
PublisherUrl: https://www.jetbrains.com/
PublisherSupportUrl: https://www.jetbrains.com/support/
PrivacyUrl: https://www.jetbrains.com/legal/docs/privacy/privacy/
Author: JetBrains s.r.o.
PackageName: CLion (EAP)
PackageUrl: https://www.jetbrains.com/clion/nextversion/
License: Freeware
LicenseUrl: https://www.jetbrains.com/legal/docs/toolbox/user_eap/
Copyright: Copyright © 2000-2026 JetBrains s.r.o.
ShortDescription: A cross-platform IDE for C and C++
Description: Intelligent cross-platform C/C++ IDE for every C and C++ developer on Linux, macOS and Windows
Tags:
- c
- c++
- code
- coding
- cpp
- develop
- development
- ide
- programming
ReleaseNotes: |-
  The latest CLion 2026.3 EAP build is out with the following highlights:
  - Debug profiles are now stored as JSON files by default. You can configure them manually or with an AI agent, and use existing JSON debug configurations from other environments, such as VS Code. This also provides you with configuration options that are not currently exposed in CLion’s UI.
  - When a requires expression evaluates to false, the IDE now shows more detailed diagnostics explaining why the requirement is ill-formed. For example, it can show that a function is inaccessible, deleted, ambiguous, or unresolved.
  - The new Inspect This action helps you quickly find relevant ways to analyze the code at the caret. Use ⌘⌥⇧A on macOS or Ctrl+Alt+Shift+A on Windows/Linux. Depending on the context, the popup gives you access to class layout, code issues, type hierarchy, or all these at once.
  - The bundled CMake has been updated to v4.4.2.
  Please try this build, share your feedback, and report any issues to our issue tracker.
  Thank you for using CLion!
ReleaseNotesUrl: https://youtrack.jetbrains.com/articles/CPP-A-230654564
Documentations:
- DocumentLabel: Learn CLion
  DocumentUrl: https://www.jetbrains.com/clion/learn/
ManifestType: defaultLocale
ManifestVersion: 1.12.0
