# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: poco-ai.Agentero
PackageVersion: 0.11.6
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/poco-ai/Agentero/releases/download/v0.11.6/Agentero_0.11.6_x64-setup.exe
  InstallerSha256: 9715E53666BE14EC1CA112F54E992845C2E2FEBBC42CA0C4AFF4A8C1D1F39A5C
  ProductCode: Agentero
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Agentero'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/poco-ai/Agentero/releases/download/v0.11.6/Agentero_0.11.6_x64_en-US.msi
  InstallerSha256: B68C86D224ED860B6BBDDE2AAF9A74F8CF4D738700DBCA7993B16EC3EEE3FA83
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{AABB37C3-9CDE-4D4A-A33F-D61F64AECC06}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{402FD5B4-C60B-569F-BEDA-586DD7712EAB}'
ManifestType: installer
ManifestVersion: 1.12.0
