# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mihari.Mihari
PackageVersion: 0.9.5
InstallerType: portable
Commands:
- mihari
ReleaseDate: 2026-09-17
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mihari-proxy/mihari/releases/download/v0.9.5/mihari-windows-amd64.exe
  InstallerSha256: CE423598CF1811607C3C333D35BB22C23A5A5F1D9A160BBFFE34A672B46FBF7C
- Architecture: arm64
  InstallerUrl: https://github.com/mihari-proxy/mihari/releases/download/v0.9.5/mihari-windows-arm64.exe
  InstallerSha256: 759CC5E4183FB8048F93D9676EC25539B48B9DE2AD0B118F33147CE01C42F884
ManifestType: installer
ManifestVersion: 1.12.0
