# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: milisp.Codexia
PackageVersion: 0.54.2
UpgradeBehavior: install
Protocols:
- codexia
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/milisp/codexia/releases/download/v0.54.2/codexia_0.54.2_x64-setup.exe
  InstallerSha256: 7503DAEA62958F9B8C6E06905964C67D4090E6F584DD1945127E5F0405B5A465
  ProductCode: codexia
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\codexia'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/milisp/codexia/releases/download/v0.54.2/codexia_0.54.2_x64_en-US.msi
  InstallerSha256: CF7C0D53BE7D8A77DF6F6D9615D957CEBDB4DE6E59C0CDA7EB813FC49CDC2C2F
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{2CDC1205-C63F-48B3-8CF8-46E2D8578049}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{3FC690D7-848A-56A8-BAB1-FE945824991A}'
ManifestType: installer
ManifestVersion: 1.12.0
