# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ReliantLabs.Reliant
PackageVersion: 1.7.16
InstallerType: nullsoft # electron-builder
ProductCode: 4fcef4a6-14b7-5ba3-986f-1a91599ff94d
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://downloads.reliantlabs.io/Reliant-1.7.16-win-x64.exe
  InstallerSha256: 44E5E0B8A4935D67D4E2F38277C957846E2EEDF46EE4B5B72F9BEEBF155CA3F0
  InstallerSwitches:
    Custom: /currentuser
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Reliant'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://downloads.reliantlabs.io/Reliant-1.7.16-win-x64.exe
  InstallerSha256: 44E5E0B8A4935D67D4E2F38277C957846E2EEDF46EE4B5B72F9BEEBF155CA3F0
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Reliant'
ManifestType: installer
ManifestVersion: 1.12.0
