# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: birabittoh.GoopieLauncher
PackageVersion: 1.9.3
ReleaseDate: 2026-09-23
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/birabittoh/GoopieLauncher/releases/download/v1.9.3/Goopie-Launcher-windows-x86_64-setup.exe
  InstallerSha256: F1CE525F7D6F4284D8A9186AEB5090AD73703F372AE3598BCF09A88C20C83C50
  ProductCode: Goopie Launcher
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Goopie Launcher'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/birabittoh/GoopieLauncher/releases/download/v1.9.3/Goopie-Launcher-windows-x86_64.msi
  InstallerSha256: 8A7708775BF32E6679C4E06BB3F3364A3AB3F61D57F3D63589D3F87B3E423128
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{3CD43B43-6AE2-463B-8121-B46CEADDEE73}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{75DE3406-4003-54E2-8521-D76818DA2D0B}'
ManifestType: installer
ManifestVersion: 1.12.0
