# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PlummersSoftware.TMOG
PackageVersion: 1.0.1.0
InstallerType: inno
Scope: user
ProductCode: '{A6C8E313-D89B-4913-BD80-249F5A7575C8}_is1'
ReleaseDate: 2026-09-28
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Task Manager TMOG'
Installers:
- Architecture: x64
  InstallerUrl: https://tmog.org/rtm/downloads/TMOG-Task-Manager-Setup-1.0.1-0-x64-b4edf70fa040.exe
  InstallerSha256: B4EDF70FA040968958C662FFB09FEEEB0EECA07759E6ED7742606BCC39F29FC6
- Architecture: arm64
  InstallerUrl: https://tmog.org/rtm/downloads/TMOG-Task-Manager-Setup-1.0.1-0-arm64-a317a09fc59e.exe
  InstallerSha256: A317A09FC59ED7EC094739FCDDEFD80CF4EEAC8FBB239FB12D0C8C0466A9D21B
ManifestType: installer
ManifestVersion: 1.12.0
