# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: EasyTier.EasyTier
PackageVersion: 2.4.2
PackageLocale: en-US
Publisher: kkrainbow
PublisherUrl: https://easytier.rs/
PublisherSupportUrl: https://github.com/EasyTier/EasyTier/issues
PackageName: easytier-gui
PackageUrl: https://easytier.rs/en/
License: Apache-2.0
LicenseUrl: https://github.com/EasyTier/EasyTier/blob/HEAD/LICENSE
Copyright: Copyright 2024 sunsijie
ShortDescription: A simple, secure, decentralized VPN mesh network solution
Tags:
- ethernet
- intranet
- network
- network-switch
- switch
ReleaseNotes: |-
  🚀 Feature Enhancements
  - CLI Peer Sorting Optimization - Peers in the CLI are now sorted by IPv4 address and hostname for better readability @fanyang89 #1191
  - Statistics Counters - Added statistics counters for monitoring and debugging network status @KKRainbow #1207
  - GUI Port Forwarding - Added port forwarding configuration functionality to the GUI interface @FuturePrayer #1198
  - Enhanced Encryption Options - Added XOR and ChaCha20 encryption algorithms with optimizations for low-end devices and OpenSSL support @CyiceK #1186
  - Android No-TUN Mode Optimization - Added FOREGROUND_SERVICE for Android no_tun mode, eliminating dependency on VPN service @21paradox #1203
  🐞 Bug Fixes
  - IPv6 Routing Fix - Fixed IPv6 packet routing issues and prevented route looping @KKRainbow #1187
  - Jemalloc Prof Feature Fix - Resolved compilation issues with the Jemalloc prof feature @KKRainbow #1201
  - Direct Connect Dead Loop Fix - Fixed a potential infinite loop in the direct connector when the destination peer has disable-p2p enabled @KKRainbow #1206
  - KCP Enable Condition Optimization - Optimized the conditions for enabling the KCP protocol, improving network adaptability @KKRainbow #1210
  - QUIC Transport Panic Fix - Fixed a potential panic issue in the QUIC transport protocol @KKRainbow #1216
  - Code Quality Improvement - Performed Clippy code checks and cleanup, enhancing code quality @KKRainbow #1214
  - Docker Workflow Update - Updated Docker-related continuous integration workflow configurations @KKRainbow #1217
ReleaseNotesUrl: https://github.com/EasyTier/EasyTier/releases/tag/v2.4.2
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://easytier.rs/en/guide/introduction.html
ManifestType: defaultLocale
ManifestVersion: 1.10.0
