# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JingxuanKang.CoSpace
PackageVersion: 0.4.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: cospace.exe
  PortableCommandAlias: cospace
Commands:
- cospace
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/JingxuanKang/cospace/releases/download/v0.4.1/cospace_windows_amd64.zip
  InstallerSha256: 4F83E4956D613D86CA2A0D904C8981BFDAF37192B0E9201E13D387F3E2A71AFB
- Architecture: arm64
  InstallerUrl: https://github.com/JingxuanKang/cospace/releases/download/v0.4.1/cospace_windows_arm64.zip
  InstallerSha256: C514848F193921EF3A3FA631BDB06CDA7A9147168FAF969B9DA1F734253A44CF
ManifestType: installer
ManifestVersion: 1.12.0
