# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: KDE.KGoldrunner
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: kgoldrunner
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/games/kgoldrunner/master/windows/kgoldrunner-master-956-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 5641A2DEFF7738BE1354269B4A84911C04A076CE57D72B2A1E02C368C7C78079
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/games/kgoldrunner/master/windows/kgoldrunner-master-956-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 5641A2DEFF7738BE1354269B4A84911C04A076CE57D72B2A1E02C368C7C78079
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.10.0
