# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: XCP-ng.WindowsPvDrivers
PackageVersion: 9.2.385.0
InstallerType: zip
NestedInstallerType: wix
NestedInstallerFiles:
- RelativeFilePath: xcpng-winpv-9.2.385.0-Release-x64/package/XenTools-x64.msi
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: '{A9CDEFA1-AB19-426F-8065-64331E634A62}'
ReleaseDate: 2026-09-14
AppsAndFeaturesEntries:
- UpgradeCode: '{7C7736B6-B55F-4868-87F5-5A1FFCC73B64}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/xcp-ng/win-pv-drivers/releases/download/v9.2.385/xcpng-winpv-9.2.385.0-Release-x64.zip
  InstallerSha256: 044E2E9F9601D490203704142EBFCCED8F52D3BD2A87434E18F803516A5543E2
ManifestType: installer
ManifestVersion: 1.12.0
