# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: XCP-ng.WindowsPvDrivers
PackageVersion: 9.2.385.0
PackageLocale: zh-CN
ShortDescription: 为运行在 XCP-ng 虚拟机监控程序上的 Windows 客户机提供半虚拟化驱动和客户机代理。
Description: XCP-ng Windows Guest Tools 为运行在 XCP-ng 虚拟机监控程序上的 Windows 客户机提供半虚拟化设备驱动和客户机代理。安装程序包含 Xen 总线、接口、网络、存储、控制台、键盘/鼠标、HID 和标准 VGA 显示驱动，以及驱动安装支持组件、XenPlus 客户机代理和 XenClean、XenBootFix 维护工具。
Tags:
- xcp-ng
- xen
- 虚拟化
- 驱动
ManifestType: locale
ManifestVersion: 1.12.0
