# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Chronosphere.FluentBit
PackageVersion: 5.1.3
Commands:
- fluent-bit
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://packages.fluentbit.io/windows/fluent-bit-5.1.3-win32.exe
  InstallerSha256: 58A25F831AAEEB06FCB54046F694E9C2928767C38DE9B0FE21BCE8D3BB0BE082
  UpgradeBehavior: install
  ProductCode: fluent-bit
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://packages.fluentbit.io/windows/fluent-bit-5.1.3-win64.exe
  InstallerSha256: 5B293C3AA4068DF8967F28CB57E14BF08461C465ABB84EAA035B719F34367D3E
  UpgradeBehavior: install
  ProductCode: fluent-bit
- Architecture: arm64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://packages.fluentbit.io/windows/fluent-bit-5.1.3-winarm64.exe
  InstallerSha256: F61F65493AFC019D0C96AAEEFE5B42BF6B264B25971B6A76DE3EC4C0D5322123
  UpgradeBehavior: install
  ProductCode: fluent-bit
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: fluent-bit-5.1.3-win32\bin\fluent-bit.exe
  InstallerUrl: https://packages.fluentbit.io/windows/fluent-bit-5.1.3-win32.zip
  InstallerSha256: F2CD74424C9D2EBF63C1F476B894B4A47E81157DECCB3EB2AFA142C3A084271F
  ArchiveBinariesDependOnPath: true
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: fluent-bit-5.1.3-win64\bin\fluent-bit.exe
  InstallerUrl: https://packages.fluentbit.io/windows/fluent-bit-5.1.3-win64.zip
  InstallerSha256: 2A06C1A3C0ECDDC970F50486A94A775B54FA28BF2EBE42C57A325511D33C0BB5
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: fluent-bit-5.1.3-winarm64\bin\fluent-bit.exe
  InstallerUrl: https://packages.fluentbit.io/windows/fluent-bit-5.1.3-winarm64.zip
  InstallerSha256: 0C0EA7AA79093491BAF2D599826922E39B0B9F8ABAFAD47AC18027A872D7FCEB
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
