# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.oc
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win32/oc/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 67173B9E7BB9D49DD9BEBB4ED33D1CB8078CC4FF0AE09B6C040AADACB75AED9B
  ProductCode: Firefox Developer Edition 145.0 (x86 oc)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64/oc/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: E511ED7C20B672E6A77DC609B2E9C46EA9674DCB644E591469D64E00CD64B621
  ProductCode: Firefox Developer Edition 145.0 (x64 oc)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64-aarch64/oc/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 934259DFEC0DBFF7C8EAD473E66AF235547F682782753C1B7CF6FEE65BC6CAD3
  ProductCode: Firefox Developer Edition 145.0 (arm64 oc)
ManifestType: installer
ManifestVersion: 1.10.0
