# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AgileBits.1Password
PackageVersion: 8.12.38.34
UpgradeBehavior: install
Protocols:
- onepassword
- onepassword8
ReleaseDate: 2026-10-01
Installers:
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.19041.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://c.1password.com/dist/1P/win8/1PasswordSetup-8.12.38.msixbundle
  InstallerSha256: CE94E7E72693E3B2935C1DCA1EB40E6A29358CD88FC0F8EF5EA3BBFD282BD624
  SignatureSha256: B39BF57A6ADC0F32D2DD39A0167CF0EF0E25A2AFB055290568CFD9C45DFFC135
  PackageFamilyName: Agilebits.1Password_amwd9z03whsfe
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.19041.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://c.1password.com/dist/1P/win8/1PasswordSetup-8.12.38.msixbundle
  InstallerSha256: CE94E7E72693E3B2935C1DCA1EB40E6A29358CD88FC0F8EF5EA3BBFD282BD624
  SignatureSha256: B39BF57A6ADC0F32D2DD39A0167CF0EF0E25A2AFB055290568CFD9C45DFFC135
  PackageFamilyName: Agilebits.1Password_amwd9z03whsfe
- Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://c.1password.com/dist/1P/win8/1PasswordSetup-8.12.38.msi
  InstallerSha256: 78FB3FE99D28E5154FCC4B9DB3AF797E07B4336B6A3A50CD81BD4D6A0C507A03
  ProductCode: '{C20D7863-0F35-49FC-AB66-37571ED0F6BC}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 8.12.38
ManifestType: installer
ManifestVersion: 1.12.0
