# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.ArtCraft
PackageVersion: 0.41.0
UpgradeBehavior: install
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/storytold/artcraft/releases/download/artcraft-v0.41.0/ArtCraft_0.41.0_x64-setup.exe
  InstallerSha256: CB15DA474AE36A7A7F930A6E9916BE2794E7CC84C3340B531C38EABC82F4363E
  ProductCode: ArtCraft
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/storytold/artcraft/releases/download/artcraft-v0.41.0/ArtCraft_0.41.0_x64_en-US.msi
  InstallerSha256: 255F963BA8ACB799B231AC23A5EF04CA157A8D26F9B9B279B3E55A59DB29BE77
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{6C6E01A0-623D-44A8-9FE1-B13FB2871BF7}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{15B9EEF2-2BAC-5133-8062-0862ED3AEA3A}'
ManifestType: installer
ManifestVersion: 1.12.0
