# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Opera.Opera
PackageVersion: 120.0.5543.128
InstallerType: exe
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /silent
  SilentWithProgress: /runimmediately
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- operastable
FileExtensions:
- crx
- htm
- html
- opdownload
- pdf
- shtml
- xht
- xhtml
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/120.0.5543.128/win/Opera_120.0.5543.128_Setup.exe
  InstallerSha256: 7324D626C9BBEE838001376321A8ECA8BC94FDB1547AE11D5DFAF1D5C93B7553
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x86
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/120.0.5543.128/win/Opera_120.0.5543.128_Setup.exe
  InstallerSha256: 7324D626C9BBEE838001376321A8ECA8BC94FDB1547AE11D5DFAF1D5C93B7553
  InstallerSwitches:
    Custom: /allusers=1
- Architecture: x64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/120.0.5543.128/win/Opera_120.0.5543.128_Setup_x64.exe
  InstallerSha256: 87E4296C55AB97E51A35BE094B65AC153D09B160EAE56597918C1EA82DD12B05
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/120.0.5543.128/win/Opera_120.0.5543.128_Setup_x64.exe
  InstallerSha256: 87E4296C55AB97E51A35BE094B65AC153D09B160EAE56597918C1EA82DD12B05
  InstallerSwitches:
    Custom: /allusers=1
- Architecture: arm64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/120.0.5543.128/win/Opera_120.0.5543.128_Setup_arm64.exe
  InstallerSha256: 7AD718DF0D08F92BBA837C4AE1CF755DD634326BEA77F915A226129081FA4403
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/120.0.5543.128/win/Opera_120.0.5543.128_Setup_arm64.exe
  InstallerSha256: 7AD718DF0D08F92BBA837C4AE1CF755DD634326BEA77F915A226129081FA4403
  InstallerSwitches:
    Custom: /allusers=1
ManifestType: installer
ManifestVersion: 1.10.0
