# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Foxit.PhantomPDF
PackageVersion: 14.0.0.33046
Scope: machine
UpgradeBehavior: install
Protocols:
- foxitpdfeditor
- foxitphantom
- foxitphantompdf
FileExtensions:
- bxml
- cpdf
- fdf
- ofd
- ppdf
- xdp
- xfdf
ProductCode: '{8145C975-74E2-11F0-B61B-208810E1398B}'
ReleaseDate: 2025-09-25
Installers:
- InstallerLocale: en
  Architecture: x64
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: FoxitPDFEditor.msi
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.zip
  InstallerSha256: 9EB9525D20CB303CD9A6FA736D0EC373C37206E7EDE3C357D1603629CA4A4287
- InstallerLocale: en
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang en
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: da
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang da-DK
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: de
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang de
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: es
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang es
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: fi
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang fi-FI
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: fr
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang fr
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: it
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang it
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: ja
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang jp
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: ko
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang ko
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: nb
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang nb-NO
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: nl
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang nl
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: pl
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang pl
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: pt
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang pt
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: ru
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang ru
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: sv
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang sv-SE
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: zh-CN
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang zh
  AppsAndFeaturesEntries:
  - InstallerType: wix
- InstallerLocale: zh-TW
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/14.0.1/FoxitPDFEditor1401_L10N_Setup_x64.exe
  InstallerSha256: 1F272850660682704187EBE67D231DD241257DDEB4D1E11F78E1E22AEC4C8B3F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
    Custom: /lang zh-tw
  AppsAndFeaturesEntries:
  - InstallerType: wix
ManifestType: installer
ManifestVersion: 1.10.0
