# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: QuinGillespie.Fedra
PackageVersion: 0.7.0
InstallerType: inno
Scope: machine
ProductCode: Fedra_is1
ReleaseDate: 2026-09-30
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Fedra'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/trypsynth/fedra/releases/download/v0.7.0/fedra_setup-x64.exe
  InstallerSha256: AF9B59D679F66ED92F9457A9B479149ABCE053C4459EC47E94629ABC8F405DB7
- Architecture: arm64
  InstallerUrl: https://github.com/trypsynth/fedra/releases/download/v0.7.0/fedra_setup-arm64.exe
  InstallerSha256: 300AA85AD8016CAED2CFA8C58C710AB28E2EBBBFBF13C9DCBAB8002FA27347F3
ManifestType: installer
ManifestVersion: 1.12.0
