# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Adobe.DNGConverter
PackageVersion: "18.7"
InstallerType: inno
Scope: machine
FileExtensions:
- dng
ProductCode: '{E7E87F48-82D9-4B7B-9620-AD99DD7D1684}}_is1'
ReleaseDate: 2026-09-28
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Adobe\Adobe DNG Converter'
Installers:
- Architecture: x64
  InstallerUrl: https://download.adobe.com/pub/adobe/dng/win/AdobeDNGConverter_x64_18_7.exe
  InstallerSha256: 360B392693999094AC6D22E863DB297FB5AD299F767120F08C548EE2138CC90E
- Architecture: arm64
  InstallerUrl: https://download.adobe.com/pub/adobe/dng/win/AdobeDNGConverter_arm64_18_7.exe
  InstallerSha256: 5AEA49D829A32A761B4CD301935435BF94F22661EC75DBFDB8094E33A36BCA7F
ManifestType: installer
ManifestVersion: 1.12.0
