# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.CadCraft
PackageVersion: 0.3.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
FileExtensions:
- dwg
- dxf
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- UpgradeCode: '{119D7D76-0167-4A9E-8F37-09DA0235F68E}'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/storytold/cadcraft/releases/download/v0.3.0/cadcraft-0.3.0-windows-x86.msi
  InstallerSha256: 92DB2365544308E54D5AC843030C88D0DA0375790C054904CBFC3A4FBC945D14
  ProductCode: '{7C188812-42A0-4540-9F0D-CD753A7B780C}'
- Architecture: x64
  InstallerUrl: https://github.com/storytold/cadcraft/releases/download/v0.3.0/cadcraft-0.3.0-windows-x64.msi
  InstallerSha256: C89C35736A36358617D687EBB356C4D9231937C3B322FC524D2737EA425C0973
  ProductCode: '{F7115747-2202-49B0-B2BF-D75EE57FEB65}'
- Architecture: arm64
  InstallerUrl: https://github.com/storytold/cadcraft/releases/download/v0.3.0/cadcraft-0.3.0-windows-arm64.msi
  InstallerSha256: 246EB1D5F7C1884E268FCAEF299C42BAEFFC2CD9972D88991C4486458D8C89A3
  ProductCode: '{FAA98A1C-A0FC-464E-8A19-21A649CA9CBF}'
ManifestType: installer
ManifestVersion: 1.12.0
