# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: a9gent.MindFS
PackageVersion: 0.5.6
InstallerType: zip
NestedInstallerType: portable
Commands:
- mindfs
ReleaseDate: 2026-10-09
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: mindfs_v0.5.6_windows_amd64\mindfs.exe
  InstallerUrl: https://github.com/a9gent/mindfs/releases/download/v0.5.6/mindfs_v0.5.6_windows_amd64.zip
  InstallerSha256: E177C0FD29A176BD5DE0F337EB7D2A1311F1B6B492D911CADE3004EF2D94A40B
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: mindfs_v0.5.6_windows_arm64\mindfs.exe
  InstallerUrl: https://github.com/a9gent/mindfs/releases/download/v0.5.6/mindfs_v0.5.6_windows_arm64.zip
  InstallerSha256: 0C710CB94EF93B56047200D7118EE0C3EED8D07D00D77F2E311C781FBF2A4ECA
ManifestType: installer
ManifestVersion: 1.12.0
