# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: hsingjui.Pilo
PackageVersion: 0.2.2
InstallerType: nullsoft
Scope: user
ProductCode: Pilo
ReleaseDate: 2026-09-30
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Pilo'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/hsingjui/pilo/releases/download/v0.2.2/Pilo-v0.2.2-x64-setup.exe
  InstallerSha256: f26014f244258559d8875aa6226b226b8c16c0924262451f59807f59719c68cc
ManifestType: installer
ManifestVersion: 1.12.0
