# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Havysoft.MemBeatle
PackageVersion: 3.3.0.171
PackageLocale: en-US
Publisher: Havy Alegria
PublisherUrl: https://www.havysoft.cl/
PublisherSupportUrl: https://www.havysoft.cl/contacto.html
Author: Havy Alegria
PackageName: MemBeatle
PackageUrl: https://www.havysoft.cl/membeatle.html
License: Freeware
LicenseUrl: https://www.havysoft.cl/acuerdo.html
Copyright: Copyright © 2026 Havy Alegria. All Rights Reserved.
ShortDescription: Retro-style memory puzzle game for Windows inspired by The Beatles.
Description: |-
  MemBeatle is a fun retro-style memory puzzle game for Windows inspired by The Fab Four, The Beatles. Test your mouse skills and visual concentration to find all 20 covers of their well-known albums hidden behind playing cards and duplicated in different positions on the virtual table, in the shortest time and with the fewest moves possible.
  Enjoy 7 visual themes with a neon effect while listening to their greatest hits during gameplay, and switch players at any time.
Tags:
- beatles
- game
- memory-game
ManifestType: defaultLocale
ManifestVersion: 1.12.0
