# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Havysoft.MemBeatle
PackageVersion: 3.3.0.171
InstallerType: zip
NestedInstallerType: inno
NestedInstallerFiles:
- RelativeFilePath: MB_Install.exe
Scope: machine
UpgradeBehavior: install
ProductCode: '{81B34302-7BE8-43B1-8AF0-4B50CEA935E8}_is1'
ReleaseDate: 2026-07-20
InstallationMetadata:
  DefaultInstallLocation: '%SystemDrive%\Programs\Havysoft\MemBeatle'
Installers:
- Architecture: x64
  InstallerUrl: https://www.havysoft.cl/download/MB_Install.zip
  InstallerSha256: F5D4BE2A2116EBBF41F3570BF0D773F4D4CAD3291A0449B2A470BFCE4BBE6829
ManifestType: installer
ManifestVersion: 1.12.0
