# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Havysoft.MemBeatle
PackageVersion: 3.3.0.171
PackageLocale: zh-CN
License: 免费软件
ShortDescription: 受披头士乐队启发的 Windows 复古记忆拼图游戏。
Description: |-
  MemBeatle 是一款受披头士乐队（The Fab Four）启发的 Windows 复古风格记忆拼图游戏。考验你的鼠标技巧和视觉专注力：藏在扑克牌背后的 20 张知名专辑封面以不同位置重复出现在虚拟桌面上，用最短的时间和最少的翻牌次数把它们全部找出来。
  游戏过程中可以欣赏 7 种霓虹效果的视觉主题，并聆听他们的经典金曲，还可以随时切换玩家。
Tags:
- beatles
- 游戏
- 记忆游戏
ManifestType: locale
ManifestVersion: 1.12.0
