# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SenseTime.OfficeRaccoon
PackageVersion: 1.0.38
InstallerType: nullsoft
Scope: machine
Protocols:
- office-raccoon
ProductCode: 90a89ad7-4216-5774-8cbd-d2255d0e6f3b
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://sta-volc.xiaohuanxiong.com/office-agent/win/商汤小浣熊-1.0.38-x64.exe
  InstallerSha256: ADB24197A2CC21FE4E497784D8B19C472A6C7A9CF94356CAB61032D8679CCEAB
ManifestType: installer
ManifestVersion: 1.12.0
