# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Power-user.Power-user
PackageVersion: 2609.1.0.445
PackageLocale: en-US
Publisher: Power-user
PublisherUrl: https://www.powerusersoftwares.com/
PublisherSupportUrl: https://www.powerusersoftwares.com/help
PrivacyUrl: https://www.powerusersoftwares.com/data-privacy-agreement
Author: Power-User SAS
PackageName: Power-user
PackageUrl: https://support.powerusersoftware.com/support/solutions/articles/80000744918-installing-power-user
License: Proprietary
LicenseUrl: https://www.powerusersoftwares.com/terms
Copyright: © 2025-25 Power-user SAS
CopyrightUrl: https://www.powerusersoftwares.com/terms
ShortDescription: A productivity add-in for Microsoft PowerPoint, Excel and Word.
Description: |-
  Power-user is a productivity add-in for Microsoft PowerPoint, Excel and Word. It brings dozens of advanced features to save time and deliver attractive presentations:
  - Access thousands of templates, icons, flags, maps, charts, pictures, logos and more from the Library
  - Create robust links between Excel and PowerPoint to automate reports
  - Clean your presentation from common mistakes in 1 click
  - Create agenda pages automatically
  - Easily align and manipulate shapes
  - Clean Excel data and formula
  - And a lot more!
Tags:
- excel
- office
- powerpoint
- word
ReleaseNotes: |-
  - [NEW FEATURE] Smart Fields: create variables, use them at multiple places and update them centrally
  - [Smart Fields] Display an input form when opening a file template containing Smart Fields
  - [Links] Fixed issue with reversed Arabic text
  - [Links] Fixed issue with the Create Link button not showing up
  - [Links] Update the Link Manager when a link is updated from the contextual window
  - [Links] Text links can be clicked to open the underlying Excel cell
  - [Agenda] Add a placeholcer shape when a section is created, before the first update
  - [Agenda] Add a variable with the section name in Agenda slide titles
  - [SmartPainter] Apply bullet indentation
  - [Themes] Clean the default template in Startup locations and settings file
  - [Library] Previews of dynamic Shapes are now animated
  - [Table Styles] New interface to manage multiple table styles
  - [Calendar] Show the calendar window only on cells formatted to date
  - [Shape Carousels] Performance improved
  - Multiple bugs fixed
ReleaseNotesUrl: https://www.powerusersoftwares.com/version-history
ManifestType: defaultLocale
ManifestVersion: 1.12.0
