# Created with YamlCreate.ps1 v2.4.4 $debug=NVS1.CRLF.7-5-0.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.9.0.schema.json

PackageIdentifier: Beanbag.RBTools
PackageVersion: 5.1.1
PackageLocale: zh-CN
# Publisher:
# PublisherUrl:
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
# PackageName:
# PackageUrl:
# License:
# LicenseUrl:
# Copyright:
# CopyrightUrl:
ShortDescription: 一套用于 Review Board 的命令行工具和 Python API。
Description: RBTools 是一套用于 Review Board 的命令行工具和 Python API，可以轻松创建、更新和落地审查请求，检查待处理审查请求的状态，制作自定义工具，并提供与自定义应用程序和脚本的集成。
# Moniker:
# Tags:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
Documentations:
- DocumentLabel: 文档
  DocumentUrl: https://www.reviewboard.org/docs/rbtools/latest/
ManifestType: locale
ManifestVersion: 1.9.0
