# Created with YamlCreate.ps1 v2.4.4 $debug=NVS1.CRLF.7-5-0.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Beanbag.RBTools
PackageVersion: 5.1.1
PackageLocale: en-US
Publisher: Beanbag, Inc.
PublisherUrl: https://www.reviewboard.org/
PublisherSupportUrl: https://www.reviewboard.org/support/
PrivacyUrl: https://www.beanbaginc.com/privacy/
Author: Beanbag, Inc.
PackageName: RBTools
PackageUrl: https://www.reviewboard.org/downloads/rbtools/
License: MIT
LicenseUrl: https://github.com/reviewboard/rbtools/blob/HEAD/COPYING
Copyright: |-
  Copyright (c) 2007-2010  Christian Hammond
  Copyright (c) 2007-2010  David Trowbridge
CopyrightUrl: https://www.beanbaginc.com/terms-of-service/general/
ShortDescription: A set of command line tools and a Python API for working with Review Board.
Description: RBTools is a set of command line tools and a Python API for working with Review Board. It makes it easy to create, update, and land review requests, check the status of pending review requests, craft custom tools, and provide integration with custom applications and scripts.
# Moniker:
Tags:
- rbt
- review-board
- reviewboard
ReleaseNotes: |-
  Bug Fixes
  rbt patch
  - Fixed a remaining bug with rbt patch --px and Subversion leading to a crash.
  Contributors
  - Christian Hammond
  - David Trowbridge
  - Michelle Aubin
ReleaseNotesUrl: https://www.reviewboard.org/docs/releasenotes/rbtools/5.1.1/
# PurchaseUrl:
# InstallationNotes:
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://www.reviewboard.org/docs/rbtools/latest/
ManifestType: defaultLocale
ManifestVersion: 1.9.0
