# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Opera.Opera
PackageVersion: 120.0.5543.161
InstallerType: exe
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /silent
  SilentWithProgress: /runimmediately
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- operastable
FileExtensions:
- crx
- htm
- html
- opdownload
- pdf
- shtml
- xht
- xhtml
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/120.0.5543.161/win/Opera_120.0.5543.161_Setup.exe
  InstallerSha256: 22C18BFB13AE9CBF6AD912163096FF393ADE56199ADB8805DE132052FCD07AE4
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x86
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/120.0.5543.161/win/Opera_120.0.5543.161_Setup.exe
  InstallerSha256: 22C18BFB13AE9CBF6AD912163096FF393ADE56199ADB8805DE132052FCD07AE4
  InstallerSwitches:
    Custom: /allusers=1
- Architecture: x64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/120.0.5543.161/win/Opera_120.0.5543.161_Setup_x64.exe
  InstallerSha256: F342148612B3292E461508B30291D0EFCD051D37DCA1780EF22F696203EAC870
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/120.0.5543.161/win/Opera_120.0.5543.161_Setup_x64.exe
  InstallerSha256: F342148612B3292E461508B30291D0EFCD051D37DCA1780EF22F696203EAC870
  InstallerSwitches:
    Custom: /allusers=1
- Architecture: arm64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/120.0.5543.161/win/Opera_120.0.5543.161_Setup_arm64.exe
  InstallerSha256: 64C23D3D657B2FA898261C1DEB0FF91139B173A919CE3441BE89C210C1DB91DC
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/120.0.5543.161/win/Opera_120.0.5543.161_Setup_arm64.exe
  InstallerSha256: 64C23D3D657B2FA898261C1DEB0FF91139B173A919CE3441BE89C210C1DB91DC
  InstallerSwitches:
    Custom: /allusers=1
ManifestType: installer
ManifestVersion: 1.10.0
