# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MiniMax.MiniMaxCode
PackageVersion: 3.1.1
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- minimax
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerUrl: https://file.cdn.minimax.io/public/minimax-agent-prod/release/MiniMax%20Code%20Setup%203.1.1.exe
  InstallerSha256: 9AFAFD3C76D6E464548ECF43BB7C217386583FC3573E77B59EFA3B511AFF9ED6
  ProductCode: c3ad25b6-f8e2-5011-aa9b-70457ab9e042
- Architecture: arm64
  InstallerUrl: https://file.cdn.minimax.io/public/minimax-agent-prod/release/MiniMax%20Code%20Setup%203.1.1.exe
  InstallerSha256: 9AFAFD3C76D6E464548ECF43BB7C217386583FC3573E77B59EFA3B511AFF9ED6
  ProductCode: c3ad25b6-f8e2-5011-aa9b-70457ab9e042
- InstallerLocale: zh-CN
  Architecture: x64
  InstallerUrl: https://filecdn.minimax.chat/public/minimax-agent-prod/release/MiniMax%20Code%20Setup%203.1.1.exe
  InstallerSha256: 1CB3A9976CC5F6D6F533CC7DD47F8858C3999867CC4B13FEA820B1AAC55BCEF7
  ProductCode: f2219de5-6104-50ab-8a91-95ff0ef719de
- InstallerLocale: zh-CN
  Architecture: arm64
  InstallerUrl: https://filecdn.minimax.chat/public/minimax-agent-prod/release/MiniMax%20Code%20Setup%203.1.1.exe
  InstallerSha256: 1CB3A9976CC5F6D6F533CC7DD47F8858C3999867CC4B13FEA820B1AAC55BCEF7
  ProductCode: f2219de5-6104-50ab-8a91-95ff0ef719de
ManifestType: installer
ManifestVersion: 1.12.0
