# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: k4if3ng.SelectBridge
PackageVersion: 1.2.2
InstallerType: inno
Scope: user
ProductCode: '{8A6DCE91-54BC-4E4A-A09D-6ADFD7F41430}_is1'
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\SelectBridge'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/k4if3ng/select-bridge/releases/download/v1.2.2/SelectBridge-1.2.2-windows-x64-setup.exe
  InstallerSha256: 4B0FDC8BAFCF57C220F0880CF4C38A71342130C5DD3595F9F32F0ABAE2891A76
- Architecture: arm64
  InstallerUrl: https://github.com/k4if3ng/select-bridge/releases/download/v1.2.2/SelectBridge-1.2.2-windows-arm64-setup.exe
  InstallerSha256: 7A348669C9FF8F18F4D8A7735AF0CBF9586E012888909E9E9594182E3986F508
ManifestType: installer
ManifestVersion: 1.12.0
