# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: newdee.Magpie
PackageVersion: 0.5.5
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/newdee/magpie/releases/download/v0.5.5/magpie_0.5.5_x64-setup.exe
  InstallerSha256: 9234BAA8B4B3209AA82DA07E18A3A3CE8B9C5473F062343541C76DCEFA1451F7
  ProductCode: magpie
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/newdee/magpie/releases/download/v0.5.5/magpie_0.5.5_x64_en-US.msi
  InstallerSha256: 1439B260EE03A774F470B33E491D3B96B10B7FD594834473E5C737BFDD60A283
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{CF55BABB-4601-4F99-A46D-DB229C8F074B}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{285F4DB5-673C-524F-B28E-235FEC26AD24}'
ManifestType: installer
ManifestVersion: 1.12.0
