# Created with YamlCreate.ps1 v2.4.6 $debug=NVS1.CRLF.7-5-0.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Box.BoxForOffice.EXE
PackageVersion: 4.23.1576.0
InstallerType: zip
NestedInstallerType: exe # Advanced Installer
NestedInstallerFiles:
- RelativeFilePath: BoxForOffice-4.23.1576.0.exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /exenoui /quiet /norestart
  SilentWithProgress: /exenoui /passive /norestart
  InstallLocation: APPDIR="<INSTALLPATH>"
  Log: /log "<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
- InstallerReturnCode: 1654
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1650
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1649
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1644
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1643
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1640
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
- InstallerReturnCode: 1639
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1638
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: 1633
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1628
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1625
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1623
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1618
  ReturnResponse: installInProgress
- InstallerReturnCode: 1602
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 1601
  ReturnResponse: contactSupport
- InstallerReturnCode: 87
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1
  ReturnResponse: invalidParameter
- InstallerReturnCode: -1
  ReturnResponse: cancelledByUser
UpgradeBehavior: install
ProductCode: Box for Office 4.23.1576.0
Installers:
- Architecture: x64
  InstallerUrl: https://e3.boxcdn.net/boxforoffice/releases/BoxForOffice-4.23.1576.0.exe.zip
  InstallerSha256: 6A9AB394FE22B4DC9349C7D0A4CD4A3D0A41D6A954F205CF4024B18CDED6FEB4
ManifestType: installer
ManifestVersion: 1.10.0
