# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.pt-BR
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win32/pt-BR/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 819F4AB7CA89900885EC1A0F2C49BB4F86F4B508A47A5488495E6720BA4D7E1A
  ProductCode: Firefox Developer Edition 145.0 (x86 pt-BR)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64/pt-BR/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 7D38C18D6F959684526BE2F3E228A88FEDB8A6F7EF6E89ECE361F5B3524AF053
  ProductCode: Firefox Developer Edition 145.0 (x64 pt-BR)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64-aarch64/pt-BR/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 6CB921B7581EBD63CF57C7ECECB158F719786FF6B2CF55E62568F90CEF3AE652
  ProductCode: Firefox Developer Edition 145.0 (arm64 pt-BR)
ManifestType: installer
ManifestVersion: 1.10.0
