# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: ReinerSCT.morris
PackageVersion: 2.0.0
PackageLocale: zh-CN
License: 免费软件
ShortDescription: 让浏览器直接访问芯片卡读卡器的中间件。
Description: morris 是一款中间件软件，让浏览器可以直接访问芯片卡读卡器。例如，可以直接在浏览器银行中用芯片卡读卡器签署交易。银行网页应用只需几行代码即可调用客户电脑上的 morris 接口。多重保护机制可有效保障对芯片卡读卡器的访问安全。
Tags:
- 中间件
- 签名
- 网上银行
ManifestType: locale
ManifestVersion: 1.12.0
