# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: ReinerSCT.morris
PackageVersion: 2.0.0
PackageLocale: de-DE
Publisher: REINER SCT
PublisherUrl: https://www.reiner-sct.com/
PublisherSupportUrl: https://www.reiner-sct.com/support/
PrivacyUrl: https://www.reiner-sct.com/datenschutz/
Author: REINER Kartengeräte GmbH & Co. KG
PackageName: morris
PackageUrl: https://www.reiner-sct.com/morris-software/
License: Gratis
LicenseUrl: https://www.reiner-sct.com/agb/
CopyrightUrl: https://www.reiner-sct.com/agb/
ShortDescription: Middleware für den Zugriff auf den Chipkartenleser direkt aus dem Browser.
Description: morris ist eine Middleware (Software), die es ermöglicht, direkt vom Browser aus auf den Chipkartenleser zuzugreifen. So können zum Beispiel Transaktionen direkt von Browser-Banking aus mit dem Chipkartenleser signiert werden. Die Browser-Bankingapplikation muss lediglich mit ein paar Zeilen Code die morris-Schnittstelle auf dem PC des Kunden ansprechen. Mehrere Schutzmechanismen sichern den Zugriff auf den Chipkartenleser wirkungsvoll ab.
Tags:
- middleware
- online-banking
- signature
ManifestType: defaultLocale
ManifestVersion: 1.12.0
