# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: ReinerSCT.morris
PackageVersion: 2.0.0
PackageLocale: en-US
PublisherUrl: https://www.reiner-sct.com/en/
PublisherSupportUrl: https://www.reiner-sct.com/en/support/
PrivacyUrl: https://www.reiner-sct.com/en/data-protection/
PackageUrl: https://www.reiner-sct.com/en/reiner-sct-morris-downloads-at-a-glance/
License: Freeware
LicenseUrl: https://www.reiner-sct.com/en/gtc/
CopyrightUrl: https://www.reiner-sct.com/en/gtc/
ShortDescription: Middleware to access the chip card reader directly from the browser.
Description: morris is a middleware (software) that makes it possible to access the chip card reader directly from the browser. For example, transactions can be signed directly from browser banking using the chip card reader. The browser banking application only needs to address the morris interface on the customer's PC with a few lines of code. Several protective mechanisms effectively secure access to the chip card reader.
ManifestType: locale
ManifestVersion: 1.12.0
