# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ReinerSCT.morris
PackageVersion: 2.0.0
InstallerType: inno
Scope: machine
ProductCode: '{C37FB380-F05B-4B34-A8C0-E11888C310DA}_is1'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\REINER SCT\morris'
Installers:
- Architecture: x86
  InstallerUrl: https://dp.reiner-sct.com/downloads/d.php?s=mo&f=morris_V_2_0_0.exe
  InstallerSha256: B55ADF36F25F26BCFCAE08EA5B7187E58351E9C5BCAB216A0F34C2B592E77BBF
ManifestType: installer
ManifestVersion: 1.12.0
