# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.FilmCraft
PackageVersion: 0.4.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- UpgradeCode: '{31E6FB14-9DBC-41DD-B24B-26B71FB31B62}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/storytold/filmcraft/releases/download/v0.4.0/filmcraft-0.4.0-windows-x86.msi
  InstallerSha256: D3FACA4015A455B8CD56C00E5A04F4007EE80115F180839135C1E650CCCF27B9
  ProductCode: '{A02462BF-B4DC-4646-AE8A-11D6D0EA56FB}'
- Architecture: x64
  InstallerUrl: https://github.com/storytold/filmcraft/releases/download/v0.4.0/filmcraft-0.4.0-windows-x64.msi
  InstallerSha256: EDD03E2D3D7D495596677A1CD1FAEF037387300AB485FFAD9AE51DF593A2F931
  ProductCode: '{CB314353-9889-42FC-A230-BC23C675C70A}'
- Architecture: arm64
  InstallerUrl: https://github.com/storytold/filmcraft/releases/download/v0.4.0/filmcraft-0.4.0-windows-arm64.msi
  InstallerSha256: 25692FDF0A0F2AB4A43E07CA68F4ADB2B3B4F457BA397C75EFE78E5051F75164
  ProductCode: '{A60508A8-DB87-4340-B6CA-88B0BA7F1130}'
ManifestType: installer
ManifestVersion: 1.12.0
