# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OrchestratorInc.AgentOrchestrator
PackageVersion: 0.13.3
InstallerType: nullsoft # electron-builder
ProductCode: d06535a3-65f7-5495-a483-b4bc9f28c80a
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/OrchestratorInc/agent-orchestrator/releases/download/v0.13.3/Agent.Orchestrator.Setup.0.13.3.exe
  InstallerSha256: 3A9177E228FD8C10262AAF07FEF67B3C5D10AF16262757BFFC60F3687C58AC1C
  InstallerSwitches:
    Custom: /currentuser
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\agent-orchestrator'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/OrchestratorInc/agent-orchestrator/releases/download/v0.13.3/Agent.Orchestrator.Setup.0.13.3.exe
  InstallerSha256: 3A9177E228FD8C10262AAF07FEF67B3C5D10AF16262757BFFC60F3687C58AC1C
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\agent-orchestrator'
ManifestType: installer
ManifestVersion: 1.12.0
