# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.az
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b8/win32/az/Firefox%20Setup%20145.0b8.exe
  InstallerSha256: CB6FA87DF7077801B3635FD0B1AECC720B5668E9A9E7392909A83ABC0AB2EBE2
  ProductCode: Firefox Developer Edition 145.0 (x86 az)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b8/win64/az/Firefox%20Setup%20145.0b8.exe
  InstallerSha256: 4676622C2D2982554DFE3D341E39D672DEEE5C62D02946A24C2A54191BCDE5B0
  ProductCode: Firefox Developer Edition 145.0 (x64 az)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b8/win64-aarch64/az/Firefox%20Setup%20145.0b8.exe
  InstallerSha256: 6320AC35FBB38CEBB113745A10D0677041A740238BA997D495108EC48F9C2CA5
  ProductCode: Firefox Developer Edition 145.0 (arm64 az)
ManifestType: installer
ManifestVersion: 1.10.0
