# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PortSwigger.BurpSuite
PackageVersion: 2026.9.2
InstallerType: exe
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -q -Dinstall4j.suppressUnattendedReboot=true
  SilentWithProgress: -q -splash "" -Dinstall4j.suppressUnattendedReboot=true
  InstallLocation: -dir "<INSTALLPATH>"
  Log: -Dinstall4j.log="<LOGPATH>"
UpgradeBehavior: install
FileExtensions:
- burp
ProductCode: 6592-1155-2163-3973
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://portswigger.net/burp/releases/download?product=desktop&version=2026.9.2&type=WindowsX64
  InstallerSha256: 866101D7317C8E7F0456F6C9516AD71D8AD24085A3DB0ABE5A55F03C4A25BE0F
- Architecture: x64
  Scope: machine
  InstallerUrl: https://portswigger.net/burp/releases/download?product=desktop&version=2026.9.2&type=WindowsX64
  InstallerSha256: 866101D7317C8E7F0456F6C9516AD71D8AD24085A3DB0ABE5A55F03C4A25BE0F
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://portswigger.net/burp/releases/download?product=desktop&version=2026.9.2&type=WindowsArm64
  InstallerSha256: E4BD207230C76C965DCF0E5BFAAFA284CF31B100354F3172EB7A552980AFE353
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://portswigger.net/burp/releases/download?product=desktop&version=2026.9.2&type=WindowsArm64
  InstallerSha256: E4BD207230C76C965DCF0E5BFAAFA284CF31B100354F3172EB7A552980AFE353
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
