# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Anysphere.Cursor
PackageVersion: 3.23.12
InstallerType: inno
InstallerSwitches:
  Custom: /mergetasks=!runcode
UpgradeBehavior: install
Protocols:
- cursor
FileExtensions:
- ascx
- asp
- aspx
- bash
- bash_login
- bash_logout
- bash_profile
- bashrc
- bib
- bowerrc
- c
- c++
- cc
- cfg
- cjs
- clj
- cljs
- cljx
- clojure
- cls
- cmake
- code-workspace
- coffee
- config
- containerfile
- cpp
- cs
- cshtml
- csproj
- css
- csv
- csx
- ctp
- cxx
- dart
- diff
- dockerfile
- dot
- dtd
- editorconfig
- edn
- erb
- eyaml
- eyml
- fs
- fsi
- fsscript
- fsx
- gemspec
- gitattributes
- gitconfig
- gitignore
- go
- gradle
- groovy
- h
- h++
- handlebars
- hbs
- hh
- hpp
- hxx
- ini
- ipynb
- jade
- jav
- java
- js
- jscsrc
- jshintrc
- jshtm
- json
- jsp
- jsx
- less
- log
- lua
- m
- makefile
- markdown
- md
- mdoc
- mdown
- mdtext
- mdtxt
- mdwn
- mjs
- mk
- mkd
- mkdn
- ml
- mli
- npmignore
- php
- phtml
- pl
- pl6
- plist
- pm
- pm6
- pod
- pp
- profile
- properties
- ps1
- psd1
- psgi
- psm1
- py
- pyi
- r
- rb
- rhistory
- rprofile
- rs
- rst
- rt
- sass
- scss
- sh
- shtml
- sql
- svgz
- t
- tex
- toml
- ts
- tsx
- txt
- vb
- vue
- wxi
- wxl
- wxs
- xaml
- xhtml
- xml
- yaml
- yml
- zsh
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://downloads.cursor.com/production/2d29876d567da1607532b23bbf2cd5ddbca496fe/win32/x64/user-setup/CursorUserSetup-x64-3.23.12.exe
  InstallerSha256: D33BD0FE1821FB0A1B6C8272B341C4ED54D10D8D4C6940708A83A42409988641
  ProductCode: '{DADADADA-ADAD-ADAD-ADAD-ADADADADADAD}}_is1'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://downloads.cursor.com/production/2d29876d567da1607532b23bbf2cd5ddbca496fe/win32/x64/system-setup/CursorSetup-x64-3.23.12.exe
  InstallerSha256: 34D597D17BC5DB5D634514ADC0F392092756F46BC6B083174B4F90F28408BAF2
  ProductCode: '{D7D7D7D7-7D7D-7D7D-7D7D-7D7D7D7D7D7D}}_is1'
- Architecture: arm64
  Scope: user
  InstallerUrl: https://downloads.cursor.com/production/2d29876d567da1607532b23bbf2cd5ddbca496fe/win32/arm64/user-setup/CursorUserSetup-arm64-3.23.12.exe
  InstallerSha256: 21C180FDB0298561D0B2C68B1358B7323222C83FE5B2B37360952AE926396C1A
  ProductCode: '{DBDBDBDB-BDBD-BDBD-BDBD-BDBDBDBDBDBD}}_is1'
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://downloads.cursor.com/production/2d29876d567da1607532b23bbf2cd5ddbca496fe/win32/arm64/system-setup/CursorSetup-arm64-3.23.12.exe
  InstallerSha256: E6F98C56E22E31F68B9C6664E9E35AF61A3F4F2127303F82C70B7034DA09895B
  ProductCode: '{D8D8D8D8-8D8D-8D8D-8D8D-8D8D8D8D8D8D}}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
