# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Waytech.CloudDrive2
PackageVersion: "1.0"
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: '{6A67D75D-B097-4828-B0DA-9257E00ECEF4}_is1'
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/cloud-fs/cloud-fs.github.io/releases/download/v1.1.2/CloudDrive2Setup-X64-1.1.2.exe
  InstallerSha256: 3E9760DFD16CC65ED9FB3E132B923C49EACFB14E6A3FEB362D2A0772669CBF69
- Architecture: arm64
  InstallerUrl: https://github.com/cloud-fs/cloud-fs.github.io/releases/download/v1.1.2/CloudDrive2Setup-Arm64-1.1.2.exe
  InstallerSha256: 6D9046E4BF172A9F40B9FF66C497F28FA459712941A839CE7152EE646B75266A
ManifestType: installer
ManifestVersion: 1.12.0
