# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.ru
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b8/win32/ru/Firefox%20Setup%20145.0b8.exe
  InstallerSha256: 415347D6CD361CE20D380150106DAD1AFB27761A1631602AA3ED1CC9668B9955
  ProductCode: Firefox Developer Edition 145.0 (x86 ru)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b8/win64/ru/Firefox%20Setup%20145.0b8.exe
  InstallerSha256: CD6B1F3EE0233EC559C16BDFCDBBF9D6128F02893A23BF0CE07E096E8C71B222
  ProductCode: Firefox Developer Edition 145.0 (x64 ru)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b8/win64-aarch64/ru/Firefox%20Setup%20145.0b8.exe
  InstallerSha256: A59E766ECFE2A22C2C711463F42301FD5C06E2399D0356D423618C674D61B95F
  ProductCode: Firefox Developer Edition 145.0 (arm64 ru)
ManifestType: installer
ManifestVersion: 1.10.0
