# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.gl
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b8/win32/gl/Firefox%20Setup%20145.0b8.exe
  InstallerSha256: 4558617E62871BE1051391A0834B413F4F8AA2154822672AD64AAC76CC96E15B
  ProductCode: Firefox Developer Edition 145.0 (x86 gl)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b8/win64/gl/Firefox%20Setup%20145.0b8.exe
  InstallerSha256: 99916A22CDAA2D41BD398BE5C5AD164145BA9AD452B46CB1958A444365CA938A
  ProductCode: Firefox Developer Edition 145.0 (x64 gl)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b8/win64-aarch64/gl/Firefox%20Setup%20145.0b8.exe
  InstallerSha256: 18B9820C9B173C15D9DE09C5D2C1BAEA245B04A0E57C519ED825301A0AE0B314
  ProductCode: Firefox Developer Edition 145.0 (arm64 gl)
ManifestType: installer
ManifestVersion: 1.10.0
