# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.gl
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win32/gl/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 67215A0687F3820FE981EDF1888917B28045841839758A6F6F4D3D33038741D6
  ProductCode: Firefox Developer Edition 145.0 (x86 gl)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64/gl/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 31D30051E20FCA85B72AA918F4F87FCA6841601B5A46226DE932D919A901301C
  ProductCode: Firefox Developer Edition 145.0 (x64 gl)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64-aarch64/gl/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 3E0CB670E0345EB8DE70CCCCB0793F0BD37B67FFA2FC776C4C725A229C931F57
  ProductCode: Firefox Developer Edition 145.0 (arm64 gl)
ManifestType: installer
ManifestVersion: 1.10.0
