# Created with YamlCreate.ps1 v2.4.6 $debug=NVS1.CRLF.7-5-0.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.10.0.schema.json

PackageIdentifier: Kadaster.KLIC-viewer
PackageVersion: 7.1.1
PackageLocale: zh-CN
# Publisher:
# PublisherUrl:
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
# PackageName:
# PackageUrl:
License: 免费软件
# LicenseUrl:
# Copyright:
# CopyrightUrl:
ShortDescription: 提交挖掘报告、紧急报告或定位请求后，您将收到关于电缆和管道的数字信息。通过此应用程序，您可以在挖掘现场查看并使用这些信息。
# Description:
# Moniker:
# Tags:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: locale
ManifestVersion: 1.10.0
