# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Noderr.Micronode
PackageVersion: 1.1.6
InstallerType: nullsoft
Scope: user
ProductCode: NoderrMicronode
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\Noderr Micronode'
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.noderr.xyz/windows/1.1.6/noderr-windows-micronode-setup.exe
  InstallerSha256: 0524F1BCDD2EE40BA7E8136839DDE80C3787B25369BDAEB65522E73CC1DCF1F5
ManifestType: installer
ManifestVersion: 1.12.0
