# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.EffectCraft
PackageVersion: 0.6.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- UpgradeCode: '{AACA8593-C6ED-40A8-BA6C-CB325D8529F9}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/storytold/effectcraft/releases/download/v0.6.0/effectcraft-0.6.0-windows-x86.msi
  InstallerSha256: 87AC2C52F58E9239C20531D0CCDDD6982349D4CAF4F5F8AB5B090E5B5931508B
  ProductCode: '{F4E67703-7428-49EE-82DF-A2650C9420E1}'
- Architecture: x64
  InstallerUrl: https://github.com/storytold/effectcraft/releases/download/v0.6.0/effectcraft-0.6.0-windows-x64.msi
  InstallerSha256: A3B5448D27EBA599E22A11B9D6CCF38AFB206DAB26EB2B980148900020E2BBC7
  ProductCode: '{C5CC368B-4E09-4DF5-8A94-C6F09BBDEC98}'
- Architecture: arm64
  InstallerUrl: https://github.com/storytold/effectcraft/releases/download/v0.6.0/effectcraft-0.6.0-windows-arm64.msi
  InstallerSha256: EFEEE3D0B0424F146AE134F61989CF9D518210C867593A2721BF43B1834EB53B
  ProductCode: '{AFBB90FC-419D-4C1F-81A1-5319848D28CB}'
ManifestType: installer
ManifestVersion: 1.12.0
