# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BlueHeisenberg.SCSKiller
PackageVersion: 1.2.3
MinimumOSVersion: 10.0.19041.0
InstallerType: exe # Velopack
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --installto "<INSTALLPATH>"
  Log: --log "<LOGPATH>"
UpgradeBehavior: install
ProductCode: SCSKiller.App
ReleaseDate: 2026-10-05
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\SCSKiller.App'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/BlueHeisenberg/SCSKiller/releases/download/v1.2.3/SCSKiller-Setup.exe
  InstallerSha256: B0EF5F26E2D453825B2BAA2BA8243D0AB8B1CA8DCE5C593822025DE424338D5F
ManifestType: installer
ManifestVersion: 1.12.0
