# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: yetone.Cumora
PackageVersion: 0.18.7
InstallerType: nullsoft
Scope: user
Protocols:
- cumora
ProductCode: 229be350-c80e-5792-8e2e-118530dad57c
ReleaseDate: 2026-09-22
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\cumora'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/yetone/cumora-releases/releases/download/v0.18.7/Cumora-Setup-0.18.7.exe
  InstallerSha256: 6BBCC731D888CF1885BA7A19F8E495B415CF257A395C6ACFA01EF94AF5551808
ManifestType: installer
ManifestVersion: 1.12.0
