# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.BraveOrigin.Nightly
PackageVersion: 155.1.99.25
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Origin-Nightly
ReleaseDate: 2026-10-08
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.25/BraveOriginStandaloneSilentNightlySetup32.exe
  InstallerSha256: 669AED4D3ED3B1C98CEBAA553B9C336E54D6AB13EDC2B577FBA896C6D236239B
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.25/BraveOriginStandaloneNightlySetup32.exe
  InstallerSha256: 87F56C5868C96724861EA074245D6B2B7D7693CA5A40606066814237F9779841
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.25/BraveOriginStandaloneSilentNightlySetup.exe
  InstallerSha256: 4C950D1348808CC552AD95B299E5E8E92E36ACDDC78485EC3AB479E52966E33D
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.25/BraveOriginStandaloneNightlySetup.exe
  InstallerSha256: 5E14411800F6C7C9155500BEE270F2981D0674595A912B61EF9365FF641C6C45
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.25/BraveOriginStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: 8C8D6F6C8E6D47E5A11018FCC461E2D60216760DABC7186CB9E0F4C03221A236
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.25/BraveOriginStandaloneNightlySetupArm64.exe
  InstallerSha256: 95781F6CF2134535BA83BC53A1ECEF1F6BEA363B70669D1A3D6E69B825D9D308
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
