# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: maddada.Ghostex
PackageVersion: 10.12.0
InstallerType: exe # Velopack
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --installto "<INSTALLPATH>"
  Log: --log "<LOGPATH>"
UpgradeBehavior: install
ProductCode: Ghostex
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/maddada/Ghostex/releases/download/v10.12.0/ghostex-10.12.0-windows-x64.exe
  InstallerSha256: CAACC4CA72DF4CAA6F0907DAC0B8F54259CFF8FFA50F9082C84D106E89070C9C
ManifestType: installer
ManifestVersion: 1.12.0
