# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.GoogleAppForDesktop
PackageVersion: 1.0.25.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
Protocols:
- wga
ProductCode: '{06a8089e-0b65-445d-b5c4-10b0d1b540f2}'
ReleaseDate: 2026-10-05
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Google\Google'
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/Windows%20Google%20App/ppixnthfoaz7gk3xryshcayjiu_1.0.25.0/installer.exe
  InstallerSha256: BC53DF62F83097998814E4621605FA87BAC5E27E2F26BE0C28E7F3BB7E49F719
ManifestType: installer
ManifestVersion: 1.12.0
