# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Google.GoogleAppForDesktop
PackageVersion: 1.0.25.0
PackageLocale: en-US
Publisher: Google
PublisherUrl: https://www.google.com/
PublisherSupportUrl: https://support.google.com/websearch/
PrivacyUrl: https://policies.google.com/privacy
Author: Google LLC
PackageName: Google App
PackageUrl: https://search.google/google-app/desktop/
License: Proprietary
LicenseUrl: https://policies.google.com/terms
Copyright: Copyright (C) 2026 Google LLC
ShortDescription: The Google app for desktop
Description: |-
  Ask anything with the Google app for desktop. Using a simple keyboard shortcut, get quicker access to AI-powered responses and keep exploring with follow-up questions and helpful links.
  With Lens and screen sharing built into the app, you can also ask about any part of your screen, whether a specific window or your entire screen. Plus, easily find apps and files across your computer and Google Drive—all from the Search box.
Tags:
- ai
- google
- search
ManifestType: defaultLocale
ManifestVersion: 1.12.0
