# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Google.GoogleAppForDesktop
PackageVersion: 1.0.25.0
PackageLocale: zh-CN
PrivacyUrl: https://policies.google.com/privacy?hl=zh-CN
License: 专有软件
LicenseUrl: https://policies.google.com/terms?hl=zh-CN
ShortDescription: 桌面版 Google 应用
Description: |-
  通过桌面版 Google 应用随时提问。使用简单的键盘快捷键，更快获取 AI 生成的回答，并通过后续问题和实用链接继续探索。
  应用内置 Lens 和屏幕共享功能，你可以就屏幕的任何部分提问，无论是特定窗口还是整个屏幕。此外，还可以在搜索框中轻松查找电脑和 Google 云端硬盘中的应用和文件。
Tags:
- 人工智能
- 大模型
- 大语言模型
- 搜索
- 谷歌
ManifestType: locale
ManifestVersion: 1.12.0
