# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.10.0.schema.json

PackageIdentifier: Tableau.PrepBuilder
PackageVersion: 25.2.42422
PackageLocale: zh-CN
Publisher: Tableau Software, LLC
PublisherUrl: https://www.tableau.com/zh-cn
PublisherSupportUrl: https://www.tableau.com/zh-cn/support
PrivacyUrl: https://www.salesforce.com/company/privacy/
Author: Salesforce, Inc.
PackageName: Tableau Prep Builder
PackageUrl: https://www.tableau.com/zh-cn/products/prep
License: 专有软件
LicenseUrl: https://www.tableau.com/zh-cn/legal/eula
Copyright: © 2024 Tableau Software, LLC 及其许可方。保留所有权利。
CopyrightUrl: https://www.salesforce.com/company/legal/intellectual/tmcusageguidelines/
ShortDescription: 更快地合并、调整和清理您的数据
Description: Tableau Prep Builder 提供了一种现代的数据准备方法，让您可以更轻松、更快速地组合、调整和清理数据以在 Tableau 中进行分析。借助直观便捷的数据准备流程，您只需点击几下即可获得高质量的数据。
Tags:
- etl
- 分析
- 商业智能
- 数据
- 数据准备
- 数据分析
- 数据清理
- 数据转换
Agreements:
- AgreementLabel: 最终用户许可协议
  AgreementUrl: https://www.tableau.com/zh-cn/legal/eula
ReleaseNotes: |-
  Could not open file with Japanese dakuten or handakuten in the filename or path using TPB 2025.2 in Windows OS
  Japanese input cached in Tableau Agent for Prep Window After Hitting Enter Key in Prep Builder & Prep Web Authoring
  Unintentional Text Added to Tableau Agent Interactions in Prep by Autocomplete for Japanese, Korean, and Chinese (Traditional or Simplified)
  The Popup Can't Effectively Show All The Fields If Multiple Fields Are Selected and Deleted at Once in A Prep Builder Clean Step
ReleaseNotesUrl: https://www.tableau.com/zh-cn/support/releases/prep/2025.2.1
PurchaseUrl: https://buy.tableau.com/zh-cn/
Documentations:
- DocumentLabel: 基础入门
  DocumentUrl: https://www.tableau.com/zh-cn/learn/get-started
ManifestType: locale
ManifestVersion: 1.10.0
