# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.zh-TW
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/zh-TW/Firefox%20Setup%20157.0.exe
  InstallerSha256: 5C7E5AD57332B87A7551D6F00D4BE08621124EAB87B17A03F32237FCD1E20F4E
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/zh-TW/Firefox%20Setup%20157.0.exe
  InstallerSha256: 47DF3C68BF0D1675070964F1B78E58CA4B1C47600F27F3E90044B6E265A1D5BE
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/zh-TW/Firefox%20Setup%20157.0.exe
  InstallerSha256: E2BE096BAD97E724DB72DBCA1D901BFF90958026C2DD1B186CC55E2B067FA3DB
ManifestType: installer
ManifestVersion: 1.12.0
