# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WonderIdea.FlipPDFPlus
PackageVersion: 8.1.8
InstallerType: zip
NestedInstallerType: inno
NestedInstallerFiles:
- RelativeFilePath: Flip_PDF_Plus_8.1.8_x64.exe
Scope: machine
UpgradeBehavior: install
FileExtensions:
- flbx
ProductCode: D4B238FB-30D8-4C8C-B231-3880DECA1CE4_is1
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://static.flipbuilder.com/download/flippdf2/Flip_PDF_Plus_x64.zip
  InstallerSha256: DA705228E1FE361086F27ED28A425903B46ECC2600889953A616230CC98A8BB2
ManifestType: installer
ManifestVersion: 1.12.0
