# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: MiniMax.MiniMaxCode
PackageVersion: 3.0.74
PackageLocale: en-US
Publisher: MiniMax
PublisherUrl: https://www.minimax.io/
PublisherSupportUrl: https://discord.com/invite/minimax
Author: Shanghai Xiyu Technology Co., Ltd.
PackageName: MiniMax Code
PackageUrl: https://github.com/MiniMax-AI/minimax-code
License: MIT
LicenseUrl: https://github.com/MiniMax-AI/minimax-code/blob/HEAD/LICENSE
Copyright: Copyright (c) 2026 MiniMax Code
ShortDescription: Remembers your habits, builds Agent teams, automates the repetitive work
Tags:
- agent
- agentic
- ai
- chatbot
- code
- coding
- large-language-model
- llm
- minimax
- programming
ReleaseNotes: |-
  What’s New
  - M3.1-Flash-Preview: MiniMax’s latest text model debuts in MiniMax Code, supporting everyday development work from bug fixes to complete feature implementation.
  Limited-time offers
  - Double check-in points: From September 28 through October 7, log in to MiniMax Code and complete the daily check-in to receive double free points. New and existing users can participate, and points can be used with all supported text and multimodal models.
  - Token Plan quota reset: Token Plan quotas have been reset for all users following the launch of M3.1-Flash-Preview.
ReleaseNotesUrl: https://agent.minimax.io/docs/changelog
ManifestType: defaultLocale
ManifestVersion: 1.12.0
