# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MiniMax.MiniMaxCode
PackageVersion: 3.0.74
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- minimax
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://file.cdn.minimax.io/public/minimax-agent-prod/release/MiniMax%20Code%20Setup%203.0.74.exe
  InstallerSha256: 7C7BE125856531FF7F13EF4EDC2E0CB63EC879349582023836E26CD025639CEF
  ProductCode: c3ad25b6-f8e2-5011-aa9b-70457ab9e042
- Architecture: arm64
  InstallerUrl: https://file.cdn.minimax.io/public/minimax-agent-prod/release/MiniMax%20Code%20Setup%203.0.74.exe
  InstallerSha256: 7C7BE125856531FF7F13EF4EDC2E0CB63EC879349582023836E26CD025639CEF
  ProductCode: c3ad25b6-f8e2-5011-aa9b-70457ab9e042
- InstallerLocale: zh-CN
  Architecture: x64
  InstallerUrl: https://filecdn.minimax.chat/public/minimax-agent-prod/release/MiniMax%20Code%20Setup%203.0.74.exe
  InstallerSha256: 6DFEE11508A5CDA66312472BB69C5F5215A0CE0713966114D015EA59B17D4D94
  ProductCode: f2219de5-6104-50ab-8a91-95ff0ef719de
- InstallerLocale: zh-CN
  Architecture: arm64
  InstallerUrl: https://filecdn.minimax.chat/public/minimax-agent-prod/release/MiniMax%20Code%20Setup%203.0.74.exe
  InstallerSha256: 6DFEE11508A5CDA66312472BB69C5F5215A0CE0713966114D015EA59B17D4D94
  ProductCode: f2219de5-6104-50ab-8a91-95ff0ef719de
ManifestType: installer
ManifestVersion: 1.12.0
