# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: AGTEK.Gradework
PackageVersion: 1.12.3
InstallerType: exe
Scope: machine
InstallerSwitches:
  Silent: /hide
  SilentWithProgress: /silent
  InstallLocation: /InstallDir="<INSTALLPATH>"
UpgradeBehavior: install
FileExtensions:
- adf
- agt
- cgo
- esw
- esz
- ppl
- rds
- rog
ProductCode: AGTEK Gradework
ReleaseDate: 2025-09-17
Installers:
- Architecture: x64
  InstallerUrl: https://agtek.s3.amazonaws.com/Agtek/0KR47EtNHvmV
  InstallerSha256: BD3B06014B1FFD8019B1D4DA7AADAE50015AE2406348C9567ABF9FFD09A77137
ManifestType: installer
ManifestVersion: 1.10.0
