# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MiniMax.MiniMaxCode
PackageVersion: 3.1.0
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- minimax
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://file.cdn.minimax.io/public/minimax-agent-prod/release/MiniMax%20Code%20Setup%203.1.0.exe
  InstallerSha256: 0CFFB4CF61C447FBDF70AA508EDD28933FF808DD459CE3EB8FD3AC579CF1F9A7
  ProductCode: c3ad25b6-f8e2-5011-aa9b-70457ab9e042
- Architecture: arm64
  InstallerUrl: https://file.cdn.minimax.io/public/minimax-agent-prod/release/MiniMax%20Code%20Setup%203.1.0.exe
  InstallerSha256: 0CFFB4CF61C447FBDF70AA508EDD28933FF808DD459CE3EB8FD3AC579CF1F9A7
  ProductCode: c3ad25b6-f8e2-5011-aa9b-70457ab9e042
- InstallerLocale: zh-CN
  Architecture: x64
  InstallerUrl: https://filecdn.minimax.chat/public/minimax-agent-prod/release/MiniMax%20Code%20Setup%203.1.0.exe
  InstallerSha256: 8B18EE556E6EA8DF2234FB5B7DB4D67FE8C04B01A48FE0A82F068D0E29AE57D4
  ProductCode: f2219de5-6104-50ab-8a91-95ff0ef719de
- InstallerLocale: zh-CN
  Architecture: arm64
  InstallerUrl: https://filecdn.minimax.chat/public/minimax-agent-prod/release/MiniMax%20Code%20Setup%203.1.0.exe
  InstallerSha256: 8B18EE556E6EA8DF2234FB5B7DB4D67FE8C04B01A48FE0A82F068D0E29AE57D4
  ProductCode: f2219de5-6104-50ab-8a91-95ff0ef719de
ManifestType: installer
ManifestVersion: 1.12.0
