# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Eassos.DiskGenius
PackageVersion: 6.0.1
PackageLocale: en-US
Publisher: Eassos Co., Ltd.
PublisherUrl: https://www.eassos.com/
PublisherSupportUrl: https://www.diskgenius.com/support.php
Author: Eassos Co., Ltd.
PackageName: DiskGenius
PackageUrl: https://www.diskgenius.com/
License: Proprietary
Copyright: Copyright (C) 1997-2024 Eassos Technology Co., Ltd.
ShortDescription: All-in-one solution for IT professionals
Description: DiskGenius provides an all-in-one solution for data recovery, disk partition management and backup & restore for Windows PCs, Servers and workstations.
Moniker: diskman
Tags:
- backup
- boot
- data
- disk
- file
- partition
- recover
- recovery
- restore
- system
- volume
ReleaseNotes: |-
  - New
    1. The "TRIM Optimization" feature now supports the ReFS file system.
  - Enhanced
    1. For Microsoft recovery partitions on GPT disks without volume labels, the partition name is now displayed as "MS Recovery".
    2. Microsoft recovery partitions on GPT disks are no longer marked as "Hidden".
    3. Improve the detection of damaged BitLocker encrypted partitions.
  - Fixed
    1. Fixed an issue that the software might exit abnormally after completing system migration.
    2. Fixed an issue that GPT partition tables could not be displayed under certain circumstances.
    3. Fixed an issue that retrieving hard drive S.M.A.R.T. information caused slow performance in some features.
ReleaseNotesUrl: https://www.diskgenius.com/version-history.php
PurchaseUrl: https://www.diskgenius.com/buy.php
Documentations:
- DocumentLabel: User Guide
  DocumentUrl: https://www.diskgenius.com/manual/
- DocumentLabel: FAQ
  DocumentUrl: https://www.diskgenius.com/faqs.php
ManifestType: defaultLocale
ManifestVersion: 1.10.0
