# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.10.0.schema.json

PackageIdentifier: Eassos.DiskGenius
PackageVersion: 6.0.1
PackageLocale: zh-CN
Publisher: 秦皇岛易数科技有限公司
PublisherUrl: https://www.eassos.cn/
PublisherSupportUrl: https://www.diskgenius.cn/help/index.php
Author: 秦皇岛易数科技有限公司
PackageName: DiskGenius
PackageUrl: https://www.diskgenius.cn/
License: 专有软件
Copyright: 版权所有 (C) 1997-2024 易数科技
ShortDescription: 集数据恢复、硬盘分区、系统备份等功能于一身的多功能工具软件
Description: DiskGenius，专家级数据恢复软件，集数据恢复、硬盘分区、系统备份还原等多种功能于一身的超级工具软件。
Tags:
- 分区
- 卷
- 备份
- 宗卷
- 引导
- 恢复
- 数据
- 文件
- 硬盘
- 磁盘
- 系统
- 还原
ReleaseNotes: |-
  1. TRIM 优化功能增加对 ReFS 文件系统的支持。
  2. GPT 磁盘上的微软恢复分区没有卷标时，分区名称显示为“MS Recovery”。
  3. GPT 磁盘上的微软恢复分区不显示为“隐藏”。
  4. 完善对损坏的 BitLocker 加密分区的判断。
  5. 纠正系统迁移功能执行完成后软件异常退出的问题。
  6. 纠正在某些情况下无法显示 GPT 磁盘分区表的问题。
  7. 纠正获取硬盘 SMART 信息导致部分功能执行速度慢的问题。
ReleaseNotesUrl: https://www.diskgenius.cn/releasenote.php
PurchaseUrl: https://www.eassos.cn/dg/buynow.php
ManifestType: locale
ManifestVersion: 1.10.0
