# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AgileBits.1Password
PackageVersion: 8.12.40.31
UpgradeBehavior: install
Protocols:
- onepassword
- onepassword8
ReleaseDate: 2026-10-05
Installers:
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.19041.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://c.1password.com/dist/1P/win8/1PasswordSetup-8.12.40.msixbundle
  InstallerSha256: 3455AE98708F4BD2FEF91E96FC00A5855CFF59A11E20CE2B4498E1BD298F3DA6
  SignatureSha256: C48E4EC50B83325102176A85DE23EC86837F9A101958CD824B9E4E2FC455B305
  PackageFamilyName: Agilebits.1Password_amwd9z03whsfe
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.19041.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://c.1password.com/dist/1P/win8/1PasswordSetup-8.12.40.msixbundle
  InstallerSha256: 3455AE98708F4BD2FEF91E96FC00A5855CFF59A11E20CE2B4498E1BD298F3DA6
  SignatureSha256: C48E4EC50B83325102176A85DE23EC86837F9A101958CD824B9E4E2FC455B305
  PackageFamilyName: Agilebits.1Password_amwd9z03whsfe
- Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://c.1password.com/dist/1P/win8/1PasswordSetup-8.12.40.msi
  InstallerSha256: FF0F2CF4FE802CBED4EFD8CBCBFB6ECF83A426E6B1E5A2F09FC03DBEC236D1DB
  ProductCode: '{7F49CB21-7E3D-49C9-BB59-E9E901BCFE40}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 8.12.40
ManifestType: installer
ManifestVersion: 1.12.0
