# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: EPOS.EPOSConnect
PackageVersion: 8.7.0.52713
PackageLocale: en-US
Publisher: EPOS Group A/S
PublisherUrl: https://www.eposaudio.com/
PublisherSupportUrl: https://www.eposaudio.com/support
PrivacyUrl: https://www.accobrands.com/privacy-center/global-privacy-notices/acco-uk-ltd-privacy-notice/
Author: EPOS Group A/S
PackageName: EPOS Connect
PackageUrl: https://www.eposaudio.com/en-us/software/epos-connect/
License: Proprietary
Copyright: Copyright (c) EPOS Group A/S
ShortDescription: Update with the latest firmware and personalize your EPOS audio device settings to ensure flawless operation and maximum productivity
Description: EPOS Connect for Windows gives the end user access to the latest firmware updates and personalized audio device settings. Stay in control with a tool that keeps EPOS headsets and speakerphones work seamlessly with all leading softphones.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
