# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EPOS.EPOSConnect
PackageVersion: 8.7.0.52713
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2026-10-02
Installers:
- Architecture: x86
  InstallerType: burn
  InstallerUrl: https://www.eposaudio.com/globalassets/abc---master-blocks-uk-fallback/epos-build/epos/files/software/epos-connect/epos-connect-8.7.0/eposconnect_8.7.0.52713.exe
  InstallerSha256: FD39F0123175D7E9C82CC986D9D3355A2DD3C081DFE68AC8F296EE517CD1FCA7
  AppsAndFeaturesEntries:
  - UpgradeCode: '{1BFE2806-B9C8-4366-A3BD-F3904A0BE8D4}'
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: EPOSConnect_8.7.0.52713.msi
  InstallerUrl: https://www.eposaudio.com/globalassets/abc---master-blocks-uk-fallback/epos-build/epos/files/software/epos-connect/epos-connect-8.7.0/eposconnect_8.7.0_msi.zip
  InstallerSha256: 7249A55B36ABEE707B50B095BF11434C853170C42ABDE38EB21E3FDAD306597E
  InstallerSwitches:
    InstallLocation: INSTALLLOCATION="<INSTALLPATH>"
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
  ProductCode: '{25B9F9A3-4177-4764-90B2-C6A3B03FD34A}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{D1B37831-C9FB-4560-8844-4F3CC47FB472}'
ManifestType: installer
ManifestVersion: 1.12.0
