# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.km
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win32/km/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 1A1AB0DFF5EAD253D6913844522D095C0AA0CD3E479ADDFAF3C3B7B3C9B46321
  ProductCode: Firefox Developer Edition 145.0 (x86 km)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64/km/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 205A1C6AE9F37337CD875A18387D50B36011CE7A4ECE7FBE951C6DF0FE9B8FC6
  ProductCode: Firefox Developer Edition 145.0 (x64 km)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64-aarch64/km/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: AB44B638BA0A99A4D06194D816DA7BC9E638703F0ABEF112F92536B4FEA3A6FE
  ProductCode: Firefox Developer Edition 145.0 (arm64 km)
ManifestType: installer
ManifestVersion: 1.10.0
