# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: DYMO.DYMOID
PackageVersion: 1.6.180
PackageLocale: en-US
Publisher: Sanford, L.P.
PublisherSupportUrl: https://help.dymo.com/
PrivacyUrl: https://privacy.newellbrands.com/index
Author: DYMO, Inc.
PackageName: DYMO ID
License: Proprietary
LicenseUrl: https://www.newellbrands.com/terms-of-use/
Copyright: © 2026 Sanford, L.P.
CopyrightUrl: https://www.newellbrands.com/terms-of-use/
ShortDescription: DYMO ID software makes it easier than ever to design and print labels and transfer files to your XTL or Rhino 6000+ label maker.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
