# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DYMO.DYMOID
PackageVersion: 1.6.180
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S /V/quiet /V/norestart
  SilentWithProgress: /S /V/passive /V/norestart
  InstallLocation: /V"INSTALLDIR=""<INSTALLPATH>"""
  Log: /V"/log ""<LOGPATH>"""
ExpectedReturnCodes:
- InstallerReturnCode: -1
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 1
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1150
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1201
  ReturnResponse: diskFull
- InstallerReturnCode: 1203
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1601
  ReturnResponse: contactSupport
- InstallerReturnCode: 1602
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 1618
  ReturnResponse: installInProgress
- InstallerReturnCode: 1623
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1625
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1628
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1633
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1638
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: 1639
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
- InstallerReturnCode: 1640
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1643
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1644
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1649
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1650
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1654
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
UpgradeBehavior: install
FileExtensions:
- 110job
- afjob
- atjob
- contselflamjob
- distjob
- flagjob
- genjob
- hbreakerjob
- hstjob
- mmjob
- pmjob
- ppjob
- quickjob
- rquickjob
- rtkjob
- sljob
- tbjob
- vbreakerjob
- wrapjob
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ProductCode: '{F888DAE6-BD1F-45BD-8AB7-5442A0E407A5}'
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- UpgradeCode: '{E4845BD2-89DD-461A-A396-397586347F7B}'
  InstallerType: msi
Installers:
- Architecture: x86
  InstallerUrl: https://download.dymo.com/dymo/Software/DYMOID_1.6.180/DYMOIDSetup.1.6.180.exe
  InstallerSha256: 6CB78FA778FB586FD20C30EF42E96863985A2A0F12BE3E9B9E1006859E64BC8A
ManifestType: installer
ManifestVersion: 1.12.0
