# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: TopazLabs.TopazVideoAI
PackageVersion: 7.1.0
PackageLocale: en-US
Publisher: Topaz Labs LLC
PublisherUrl: https://www.topazlabs.com/
PublisherSupportUrl: https://docs.topazlabs.com/sales-account-licensing/basic-troubleshooting/contact-support
PrivacyUrl: https://downloads.topazlabs.com/web-assets/TopazLabs-privacy-policy-101424.pdf
Author: Topaz Labs LLC
PackageName: Topaz Video AI
PackageUrl: https://www.topazlabs.com/topaz-video-ai
License: Proprietary
LicenseUrl: https://downloads.topazlabs.com/web-assets/Topaz%20-%20EULA%20(FL%202.05.25).pdf
Copyright: © 2009-2025 All rights reserved
CopyrightUrl: https://downloads.topazlabs.com/web-assets/Topaz%20-%20EULA%20(FL%202.05.25).pdf
ShortDescription: Video enhancement trusted by creative pros everywhere.
Tags:
- video
- video-enhancement
ReleaseNotes: |-
  Topaz Video AI 7.1.0
  Hi everyone,
  We are excited to share some of our latest updates for Topaz Video AI 7.1!
  See more details below:

  Major Features

  Cross-Scene Artifact Suppression for Frame Interpolation

  With Scene Detection enabled, the Slow Motion function for videos, is better equipped to handle videos with cuts. This enabled feature will treat each shot/clip between cuts as independent entities. This will prevent blending/smearing of frames from the previous or next shot from your full video.

  As noted when you enable this feature, scene detection won’t live render.
  Things to consider
  - It is recommended to have at least 8 frames per cut within your video to prevent potential stalled frames.
  - While rendering, this will split the scenes as individual parts. Ref Image: (Green) Original Source, (Red Arrow) Scene parts, (Yellow Arrow) processing scene.
  - Within the Render Queue, if a process errors and the “Retry Failed Scenes” message populates under the Status section of the render Queue. Simply Click the highlighted “Retry Failed Scenes” button to continue the render.

  - If a crash does occur, the individual parts will remain so that you can continue from where you left off rather than having to re-render the entire video.
  - Once the entirety of the render completes, the individual scenes will be stitched back into a single video. Ref Image: (Green) Original Source, (Blue Arrow) Rendered Video.
  - If any stalled frames occur, it is recommended to “Enable externally previewable exports” via the Crash Recovery section within Preferences
  - At this time, you will need to export locally to take advantage of this feature.

  Presets for Film Stock
  The following Film Stock Presets will require a second pass enhancement. At default this feature is not enabled. Please refer to the Second Pass Enhancement web doc for enabling and more information.
  Film Stock 4K Light

  This setup is for film or progressive older footage that need a light touch to bring out some details.
  - 4K preset
  - This preset has stabilization enabled as many older family films did not have a physical stabilizer for the time. You can disable this task for faster results.
  - Much of this setting can be used as a base and further modified to your liking.
  Film Stock 4K Medium

  This setup is for film or progressive older footage that need an extra push from the light touch version. This uses a different set of filters for the overall treatment.
  - 4K preset
  - This preset has stabilization enabled as many older family films did not have a physical stabilizer for the time. You can disable this task for faster results.
  - Works best with high contrast black & white films like the example above. Please ensure that “Black & White” is checked (within the Input Settings -Gear Button next to Presets), if your film is grayscale.
  - Much of this setting can be used as a base and can be partially modified to your liking.
  Film Stock 4K Strong

  This setup is for film or progressive older footage with lots of grain/digital noise.
  - 4K preset
  - This preset has stabilization enabled as many older family films did not have a physical stabilizer for the time. You can disable this task for faster results.
  - Great results for 8mm/Super 8mm films digitally captured with products such as Wolverine Data MovieMaker PRO, Kodak Reels Digitizer and Eyesen Film Scanner Digitizer.
  - Also good results with grainy 16mm telecine digital files.
  - Much of this setting can be used as a base and can be partially modified to your liking.

  Preset for MiniDV
  This setup is for MiniDV or digitally captured videos that made use of Interlaced footage (horizontal fields) for the time. MiniDV saw a large range of quality variations and conditions throughout it’s reign beginning around 1995 and ending around the late 2000’s. There was a huge use case scenarios with home movies to actual television shows and feature films.
  MiniDV Int HD Basic

  Due to the large quality and use case scenarios, the settings is a basic starting point for interlaced MiniDV footage. The intention of this preset is to get an average result that looks good in many cases. This setting is therefore intended to be modified.
  - HD Preset. Can be adjusted to 4k.
  - To make use of the Interlaced footage the settings are prepared with the Interlaced Video Type category.
  - The resolution is set to custom in order to keep the aspect ratio and pixel type as Square Pixel. Change accordingly.
  - This setting is intentionally and fully modifiable as a solid base for further refinement.

  Disable Live Export

  You can now disable or enable the Live Export viewer.
  - You can find this option within the Preferences menu under the Advanced Features section.
  - Please note that this is enabled by default.

  Disable Live Render

  You can now disable or enable the Live Render function.
  - You can find this option within the Preferences menu under the Advanced Features section.
  - When disabled, areas that do not have a rendered preview will automatically play the original source.
  - Please note that this is enabled by default.

  EXR Alpha Support

  EXRs with an Alpha channel, can now be supported by giving you the option to enable Alpha channel outputs via the codec settings.
  *Note, that at this time EXRs with Alpha may show transparency of the alpha as a checkerboard pattern in the preview. Outputs do not perform any matte operations, so the full of the RGB image will remain intact. Refer to the example below:

  DPX Non-Conversion

  No longer will DPX files need to be converted to Tiffs when working with Video AI. Now you can use DPX files like any other image sequence.

  Starlight Mini: 10x Faster in the Cloud!

  Starlight Mini, the second diffusion-based upscaling model Topaz Labs has released, is now up to 10x faster in the Cloud when compared to its original iteration. Starlight Mini brings what makes the Original Starlight so special, into a more friendly and cost effective alternative on the Cloud.
  Some Starlight Mini Reminders below
  - Starlight Mini is still a large resource intensive AI Model, so long renders are expected.
  - Recommended to use square-pixel video footage at or under 1920x1080 to avoid any aspect ratio shifts
  - Starlight Mini renders up to 4K resolution. Note: Starlight Mini output resolution options are limited.
  - Starlight Mini is a standalone enhancement and can’t be combined with other filters.
  - Please note that if you have text that is too small, blurry or inconsistent, the result may not be “sp3ll3d” correctly. If you can barely make it out, so will the AI model. It may assume that the text is a texture or pattern.
  - If you have interlaced videos, it is recommended that you deinterlace first before enhancing with Starlight Mini.
  Learn more about Starlight Mini: Here

  Pro GPU: Selection
  Those with Pro accounts that have multiple GPUs, will be able to select the specific GPU for processing.

  VP9 16K Renders
  Revisited the VP9 codec to fully support 16K outputs.

  Known Issues
  - For Cross-Scene Artifact Suppression the preview may display a frame of overlap. However, it will produce successful renders.
  Enjoy the updates with 7.1!
ReleaseNotesUrl: https://community.topazlabs.com/t/topaz-video-ai-7-1/93448
PurchaseUrl: https://www.topazlabs.com/pricing
Documentations:
- DocumentLabel: Docs
  DocumentUrl: https://docs.topazlabs.com/
ManifestType: defaultLocale
ManifestVersion: 1.10.0

