# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SillanumSoftware.VisualAnalyser
PackageVersion: "26.10"
InstallerType: inno
ProductCode: '{12AF98FE-1B69-4336-B058-D9FE2C0AF997}_is1'
ReleaseDate: 2026-10-09
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://www.sillanumsoft.org/Download/VAsetup.exe
  InstallerSha256: 37179043F94C743278BBADF4E50558993F119B3339096FF79426784A060CC965
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://www.sillanumsoft.org/Download/VAsetup.exe
  InstallerSha256: 37179043F94C743278BBADF4E50558993F119B3339096FF79426784A060CC965
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  Scope: user
  InstallerUrl: https://www.sillanumsoft.org/Download/VAsetup.exe
  InstallerSha256: 37179043F94C743278BBADF4E50558993F119B3339096FF79426784A060CC965
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://www.sillanumsoft.org/Download/VAsetup.exe
  InstallerSha256: 37179043F94C743278BBADF4E50558993F119B3339096FF79426784A060CC965
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
