# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenLogic.OpenJDK.17.JDK
PackageVersion: 17.0.20.8
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Custom: ADDLOCAL=ALL
UpgradeBehavior: install
Commands:
- jar
- jarsigner
- java
- javac
- javadoc
- javap
- javaw
- jconsole
- jdeprscan
- jdeps
- jlink
- jmod
- jps
- jshell
- jstat
- keytool
FileExtensions:
- class
- jar
- java
- jsp
ProductCode: '{DDE05C64-1780-4084-88A0-FF2621310741}'
ReleaseDate: 2026-08-06
AppsAndFeaturesEntries:
- DisplayName: OpenLogic-OpenJDK JDK with Hotspot 17.0.20+8 (x64)
  UpgradeCode: '{F376C13E-75A7-41A9-B826-A34D1A0A9ECC}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\OpenLogic\jdk-17.0.20.8-hotspot'
Installers:
- Architecture: x64
  InstallerUrl: https://builds.openlogic.com/downloadJDK/openlogic-openjdk/17.0.20+8/openlogic-openjdk-17.0.20+8-windows-x64.msi
  InstallerSha256: 0142F0700F513A0B4D9574DB1DCB0B32AF255D191A238AC435D2D8EF5088CDFF
ManifestType: installer
ManifestVersion: 1.12.0
