# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TryHardStudios.Solo
PackageVersion: 0.10.1
InstallerType: nullsoft
Scope: user
Protocols:
- solo
ProductCode: Solo
ReleaseDate: 2026-09-03
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Solo'
Installers:
- Architecture: x64
  InstallerUrl: https://releases.soloterm.com/windows/x86_64/Solo_0.10.1_x64-setup.exe
  InstallerSha256: B3254C8DD6AA1FEAB52F3D6F58713E311ED9AA6EBFD532D51E6284E00D21849C
ManifestType: installer
ManifestVersion: 1.12.0
