# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.LightCraft
PackageVersion: 0.4.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- UpgradeCode: '{229BB552-5EFD-479A-BA86-8CB6D926390C}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/storytold/lightcraft/releases/download/v0.4.0/lightcraft-0.4.0-windows-x86.msi
  InstallerSha256: 576586742FF44E4FC629062EF404E9697DB803D41E2D3FE56B9357397521F7A8
  ProductCode: '{C3DE5FD1-DCFB-4792-83CF-DB90CAAAA77F}'
- Architecture: x64
  InstallerUrl: https://github.com/storytold/lightcraft/releases/download/v0.4.0/lightcraft-0.4.0-windows-x64.msi
  InstallerSha256: 7B404524FEFD87F109F5F59EA21208BFA62F2437726CF578BE4E448526762103
  ProductCode: '{0D6F7851-4476-4F65-9215-03085DB51977}'
- Architecture: arm64
  InstallerUrl: https://github.com/storytold/lightcraft/releases/download/v0.4.0/lightcraft-0.4.0-windows-arm64.msi
  InstallerSha256: D2B4C72014CBF75BFB5E832C42C8903F61C739E91792FC523B188102AE0C7E5B
  ProductCode: '{8F7D7010-19AA-46B3-A484-48B2BFC93722}'
ManifestType: installer
ManifestVersion: 1.12.0
