# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tencent.WorkBuddy
PackageVersion: 5.7.6
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: BFD312E9-1019-4F57-9F44-F86246833B50
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.codebuddy.cn/workbuddy/saas/win32-x64-user/WorkBuddy-win32-x64-user-5.7.6.40409493-306add2a.exe
  InstallerSha256: 044B17B87A55282E79E67595485EE3046CF4B9B6A2F0429B37C55925A3D22354
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.codebuddy.cn/workbuddy/saas/win32-x64-user/WorkBuddy-win32-x64-user-5.7.6.40409493-306add2a.exe
  InstallerSha256: 044B17B87A55282E79E67595485EE3046CF4B9B6A2F0429B37C55925A3D22354
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
