# Created with YamlCreate.ps1 v2.5.0 $debug=NVS2.CRLF.7-5-2.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Loftware.NiceLabel.10
PackageVersion: 21.5.0.11092
InstallerType: exe # InstallAware
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
  InstallLocation: TARGETDIR="<INSTALLPATH>"
  Log: /l="<LOGPATH>"
Protocols:
- nicelabelautomationbuilder
- nicelabelautomationmanager
- nicelabeldesigner
- nicelabelprint
FileExtensions:
- mis
- misx
- nlbl
- nsln
ProductCode: NiceLabel 10
Installers:
- Architecture: x64
  InstallerUrl: https://www.loftware.com/siteassets/trial-download/nicelabel10.exe
  InstallerSha256: 284F5C6E99C2C1F1F953675EF0B9FE397A0AA811DB90C1B1AF51B76D6FD24787
ManifestType: installer
ManifestVersion: 1.10.0
