# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: chen-yu-hao.AcaNomo
PackageVersion: 0.5.9
InstallerType: nullsoft
Scope: user
FileExtensions:
- json
- markdown
- md
- txt
ProductCode: AcaNomo
ReleaseDate: 2026-09-28
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\AcaNomo'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/chen-yu-hao/Acanomo/releases/download/v0.5.9/AcaNomo_0.5.9_x64-setup.exe
  InstallerSha256: 23F8ADAB6D51D08A4679B11019673C06CFE9DD96AB9E3ADE9A192CB14EFB215E
ManifestType: installer
ManifestVersion: 1.12.0
