# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: g0orx.hpsdr-rs
PackageVersion: 0.7.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: '{19094204-D7C2-467C-9BCA-AA2B040ACCCA}'
AppsAndFeaturesEntries:
- UpgradeCode: '{E9AF3C7B-6CD1-4AEE-A60F-DB9ED109AEED}'
ReleaseDate: 2026-09-21
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/g0orx/hpsdr-rs/releases/download/v0.7.0/hpsdr-rs-0.7.0-x86_64.msi
  InstallerSha256: 794066C5C3FDEBA5898B3C771EECC54E767C384BDD0408D4B1D2430A25EBEC47
ManifestType: installer
ManifestVersion: 1.12.0
