# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: QNAP.Qsync
PackageVersion: 6.0.2.0529
PackageLocale: en-US
Publisher: QNAP Systems, Inc.
PublisherSupportUrl: https://service.qnap.com/
Author: QNAP Systems, Inc.
PackageName: QNAP Qsync Client
License: Proprietary
Copyright: 2026 QNAP Systems, Inc. All rights reserved.
ShortDescription: Automatic file synchronization across different devices.
Description: Qsync enables automatic file synchronization across different devices. Simply drag and drop files in the “Qsync folder”, data on devices linked with the NAS is updated simultaneously when changes are made. Additional sync modes, such as Smart Sync or Advanced Selective Sync, allow users to only sync selective data or folders. You can also create download links to share files with others without them having to create a user account for download.
Tags:
- nas
- storage
- sync
ReleaseNotes: |-
  [Enhancements]
  - Enhanced the presentation of backup tasks for more intuitive status monitoring.
  - Updated core components to further improve compatibility and overall stability.
  [Fixed Issues]
  - Fixed an issue where disconnections could occur during large file transfers, thus improving transfer reliability.
  - Fixed issues that could lead to unexpected application behaviors in certain scenarios for enhanced overall stability.
  - Fixed issues where QNAP ID (QID) notifications might not display correctly, improving connection status clarity.
  - Fixed issues where backup task results and logs could be inconsistent, ensuring more accurate task information.
  - Fixed some display issues related to UI behaviors and interactions to improve usability.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
