# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenLogic.OpenJDK.22.JDK
PackageVersion: 22.0.2.9
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Custom: ADDLOCAL=ALL
UpgradeBehavior: install
Commands:
- jar
- jarsigner
- java
- javac
- javadoc
- javap
- javaw
- jconsole
- jdeprscan
- jdeps
- jlink
- jmod
- jps
- jshell
- jstat
- keytool
FileExtensions:
- class
- jar
- java
- jsp
ProductCode: '{6B358934-27ED-4911-BBC9-DD6D9EFA2703}'
ReleaseDate: 2025-08-22
AppsAndFeaturesEntries:
- DisplayName: OpenLogic-OpenJDK JDK with Hotspot 22.0.2+9 (x64)
  UpgradeCode: '{0CF1B400-84FD-45F2-AF0F-235AFD8E92A5}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\OpenLogic\jdk-22.0.2.9-hotspot'
Installers:
- Architecture: x64
  InstallerUrl: https://builds.openlogic.com/downloadJDK/openlogic-openjdk/22.0.2+9/openlogic-openjdk-22.0.2+9-windows-x64.msi
  InstallerSha256: 46BD84F0C9768B561304F6A8DF934B710178ED968ED4E9A4F29358A61CA31085
ManifestType: installer
ManifestVersion: 1.12.0
