# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: KDE.Elisa
PackageVersion: 25.11.70
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: Elisa
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/multimedia/elisa/master/windows/elisa-master-4040-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 98AC405D05A0CEFF909B067141448829290AFBE2C568C06BFC6C048ED40E6CEF
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/multimedia/elisa/master/windows/elisa-master-4040-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 98AC405D05A0CEFF909B067141448829290AFBE2C568C06BFC6C048ED40E6CEF
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.10.0
