# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: KDE.Elisa
PackageVersion: 25.11.70
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: Elisa
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/multimedia/elisa/master/windows/elisa-master-4005-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 76CAFCDB0921A2C5C732F0FD5C02263BEFE1968F7B214B994377FC5E15FADB5A
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/multimedia/elisa/master/windows/elisa-master-4005-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 76CAFCDB0921A2C5C732F0FD5C02263BEFE1968F7B214B994377FC5E15FADB5A
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.10.0
