# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ayangweb.BongoCat
PackageVersion: 2.1.0
InstallerType: nullsoft
ProductCode: BongoCat
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/ayangweb/BongoCat/releases/download/v2.1.0/BongoCat_2.1.0_x64.exe
  InstallerSha256: 56FD96B70A4B761E8DD29733985C1217BDF8394D0D983E25CC2A20C019B91570
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/ayangweb/BongoCat/releases/download/v2.1.0/BongoCat_2.1.0_x64.exe
  InstallerSha256: 56FD96B70A4B761E8DD29733985C1217BDF8394D0D983E25CC2A20C019B91570
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
