# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: lbjlaq.AntigravityTools
PackageVersion: 4.9.4
UpgradeBehavior: install
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/lbjlaq/Antigravity-Manager/releases/download/v4.9.4/Antigravity.Tools_4.9.4_x64-setup.exe
  InstallerSha256: 8D87F4C0B8D5EB1B4B6DF574415E2D0707059A6619F634B7D23FE1B580DF2396
  ProductCode: Antigravity Tools
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Antigravity Tools'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/lbjlaq/Antigravity-Manager/releases/download/v4.9.4/Antigravity.Tools_4.9.4_x64_en-US.msi
  InstallerSha256: 74018E800AA3D13A9DB7B8FBA4250D687DED859B3DD33D09CF84D6724078F5DC
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{C759605A-ED94-4AD9-8E8D-735E94FF18AC}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{E6D0D59B-1948-5950-A427-E2A516157557}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Antigravity Tools'
ManifestType: installer
ManifestVersion: 1.12.0
