# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Python.Python.3.13
PackageVersion: 3.13.16
InstallerType: burn
UpgradeBehavior: install
Commands:
- py
- python
- pythonw
- pyw
FileExtensions:
- py
- pyc
- pyd
- pyo
- pyw
- pyz
- pyzw
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://www.python.org/ftp/python/3.13.16/python-3.13.16.exe
  InstallerSha256: 394CA84150EA428DB952CB617C1163C49FBC30E47EC53048C26E6AE44265DF07
  InstallerSwitches:
    InstallLocation: DefaultJustForMeTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=0 PrependPath=1
  ProductCode: '{4f6ee48c-ea2b-454c-b9b1-7239d5664d79}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.13.16150.0
    UpgradeCode: '{D931076A-D223-5314-A7DC-5C755C936363}'
- Architecture: x86
  Scope: machine
  InstallerUrl: https://www.python.org/ftp/python/3.13.16/python-3.13.16.exe
  InstallerSha256: 394CA84150EA428DB952CB617C1163C49FBC30E47EC53048C26E6AE44265DF07
  InstallerSwitches:
    InstallLocation: DefaultAllUsersTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=1 PrependPath=1
  ProductCode: '{4f6ee48c-ea2b-454c-b9b1-7239d5664d79}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.13.16150.0
    UpgradeCode: '{D931076A-D223-5314-A7DC-5C755C936363}'
  ElevationRequirement: elevatesSelf
- Architecture: x64
  Scope: user
  InstallerUrl: https://www.python.org/ftp/python/3.13.16/python-3.13.16-amd64.exe
  InstallerSha256: FB4F9F5D438B2396DA0086DC70B935C530CB578E37ADC6D354F7AD2037FEE83B
  InstallerSwitches:
    InstallLocation: DefaultJustForMeTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=0 PrependPath=1
  ProductCode: '{9caacd4b-4909-48f6-8790-c9839e0283c9}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.13.16150.0
    UpgradeCode: '{F96F59BD-3E48-5E4E-B1A4-6CAFADEFEAE8}'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://www.python.org/ftp/python/3.13.16/python-3.13.16-amd64.exe
  InstallerSha256: FB4F9F5D438B2396DA0086DC70B935C530CB578E37ADC6D354F7AD2037FEE83B
  InstallerSwitches:
    InstallLocation: DefaultAllUsersTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=1 PrependPath=1
  ProductCode: '{9caacd4b-4909-48f6-8790-c9839e0283c9}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.13.16150.0
    UpgradeCode: '{F96F59BD-3E48-5E4E-B1A4-6CAFADEFEAE8}'
  ElevationRequirement: elevatesSelf
- Architecture: arm64
  Scope: user
  InstallerUrl: https://www.python.org/ftp/python/3.13.16/python-3.13.16-arm64.exe
  InstallerSha256: 696E2226062C6EC3622C13F143D28336A856968518E49CB4F4C62513215A4F5D
  InstallerSwitches:
    InstallLocation: DefaultJustForMeTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=0 PrependPath=1
  ProductCode: '{8cb90e0c-8a84-44d9-9ac9-7150f7d4880c}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.13.16150.0
    UpgradeCode: '{303A4F18-F0C9-5E9F-8F29-42EA62697711}'
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://www.python.org/ftp/python/3.13.16/python-3.13.16-arm64.exe
  InstallerSha256: 696E2226062C6EC3622C13F143D28336A856968518E49CB4F4C62513215A4F5D
  InstallerSwitches:
    InstallLocation: DefaultAllUsersTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=1 PrependPath=1
  ProductCode: '{8cb90e0c-8a84-44d9-9ac9-7150f7d4880c}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.13.16150.0
    UpgradeCode: '{303A4F18-F0C9-5E9F-8F29-42EA62697711}'
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
