# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: tigerowo.InfiniteCanvas
PackageVersion: 0.8.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
ReleaseDate: 2026-09-24
AppsAndFeaturesEntries:
- UpgradeCode: '{030F7069-E17A-5B81-8F9A-58292FDE2049}'
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerUrl: https://github.com/tigerowo/infinite-canvas/releases/download/v0.8.0/Infinite.Canvas_0.8.0_x64_en-US.msi
  InstallerSha256: A0FBA2DA6CEDB5CF215F82FA41C76580176E02D9B29F1BB3460D16ECFF06ACCC
  ProductCode: '{3282E96F-E31E-4795-A9D5-5CBC872E129C}'
- InstallerLocale: zh-CN
  Architecture: x64
  InstallerUrl: https://github.com/tigerowo/infinite-canvas/releases/download/v0.8.0/Infinite.Canvas_0.8.0_x64_zh-CN.msi
  InstallerSha256: DBF4C91974CB786780BD732C79D8009AEB55DA8A28685439DA63E224F144A039
  ProductCode: '{A1F0A1AC-EC22-4085-B5E9-76A5E83FC919}'
ManifestType: installer
ManifestVersion: 1.12.0
