# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: muutot.Clipboard
PackageVersion: 1.7.3
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/muutot/Clipboard/releases/download/v1.7.3/Clipboard_1.7.3_x64-setup.exe
  InstallerSha256: B400F77694EC5294728CF8D5E3DBE04DBEB12B7A803C8A709E2EC657F6423A22
  ProductCode: Clipboard
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Clipboard'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/muutot/Clipboard/releases/download/v1.7.3/Clipboard_1.7.3_x64_en-US.msi
  InstallerSha256: 82D3CD6DF402B5137B870569410A6638D565990A0CF3BC0A5D06F034BE453702
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{8A1FA01F-7E01-4801-81AA-7E86283D229C}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{D2C48E63-D3DF-5D07-9516-57DF96E4A9D4}'
ManifestType: installer
ManifestVersion: 1.12.0
