# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.en-GB
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win32/en-GB/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 8D34352C4BEB08C54C16D9C5CF83648A42DC64DF0EB32AA0B90C3743618F7496
  ProductCode: Firefox Developer Edition 145.0 (x86 en-GB)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64/en-GB/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: B272D1026207DF9FABEB709A263AA70BE6F15936018AE39EFA7CED66A7AF2356
  ProductCode: Firefox Developer Edition 145.0 (x64 en-GB)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64-aarch64/en-GB/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 82D2D72EDB5C1F11A9ABAC2DBF363506163AB65394C678CEEF4962B26592DCAE
  ProductCode: Firefox Developer Edition 145.0 (arm64 en-GB)
ManifestType: installer
ManifestVersion: 1.10.0
