# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenLogic.OpenJDK.21.JRE
PackageVersion: 21.0.12.8
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Custom: ADDLOCAL=ALL
UpgradeBehavior: install
Commands:
- java
- javaw
- jfr
- jrunscript
- keytool
- kinit
- klist
- ktab
- rmiregistry
FileExtensions:
- class
- jar
- java
- jsp
ProductCode: '{8004CBFA-50D1-4C8E-A0B9-78AA32063D4D}'
ReleaseDate: 2026-08-06
AppsAndFeaturesEntries:
- DisplayName: OpenLogic-OpenJDK JRE with Hotspot 21.0.12+8 (x64)
  UpgradeCode: '{1F3A6D28-7FB8-4272-86E9-37056E92EC32}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\OpenLogic\jre-21.0.12.8-hotspot'
Installers:
- Architecture: x64
  InstallerUrl: https://builds.openlogic.com/downloadJDK/openlogic-openjdk-jre/21.0.12+8/openlogic-openjdk-jre-21.0.12+8-windows-x64.msi
  InstallerSha256: FD351144FD37335C20B8B2AA1B85C40292F09D4B26809B11D38DABED988E3A67
ManifestType: installer
ManifestVersion: 1.12.0
