# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: lbjlaq.AntigravityTools
PackageVersion: 4.9.0
UpgradeBehavior: install
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/lbjlaq/Antigravity-Manager/releases/download/v4.9.0/Antigravity.Tools_4.9.0_x64-setup.exe
  InstallerSha256: 50F895495681ED25CC92AC8EB1305CD776D43AD4C1373A90AEB6FD8901EB6319
  ProductCode: Antigravity Tools
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Antigravity Tools'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/lbjlaq/Antigravity-Manager/releases/download/v4.9.0/Antigravity.Tools_4.9.0_x64_en-US.msi
  InstallerSha256: 142139C8864AA76C9A8F23D2F688F66C96FC0123C59CEA9C7EA88B20D79C1DB3
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{D7034693-887F-45FD-8F03-0B658260C20D}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{E6D0D59B-1948-5950-A427-E2A516157557}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Antigravity Tools'
ManifestType: installer
ManifestVersion: 1.12.0
