# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EthanYoQ.AINovelWriter
PackageVersion: 1.1.0
InstallerType: nullsoft
Scope: user
ProductCode: d450fff5-aa36-58c2-9233-2209945e43f4
ReleaseDate: 2026-09-08
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\ai-novel-writer'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/EthanYoQ/AI-Novel-Writer/releases/download/v1.1.0/ai-novel-writer-setup-1.1.0.exe
  InstallerSha256: 54B436AEAB43A8B00AFFB768E1DB083F3E6B90EF25EBF1CD2DD6779A500C7F88
ManifestType: installer
ManifestVersion: 1.12.0
