# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SST.opencode
PackageVersion: 1.18.34
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: opencode.exe
Commands:
- opencode
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/anomalyco/opencode/releases/download/v1.18.34/opencode-windows-x64.zip
  InstallerSha256: 8EC42ED1AD8DB108052394B83AB69D0331398F761FBFFF5FE50F91D65BDD3548
- Architecture: arm64
  InstallerUrl: https://github.com/anomalyco/opencode/releases/download/v1.18.34/opencode-windows-arm64.zip
  InstallerSha256: B738AE4E823C862EABA6D6BD6E1D35E01B46851D7160882C7BDB189F33A16447
ManifestType: installer
ManifestVersion: 1.12.0
