# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: xingkongliang.SkillsManager
PackageVersion: 1.40.1
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/xingkongliang/skills-manager/releases/download/v1.40.1/skills-manager_1.40.1_x64-setup.exe
  InstallerSha256: 5E6F048BB27C69F0A3C3B3BDA47E06EE9663C89E3838AB2B3DA1C822AC7206DD
  ProductCode: skills-manager
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\skills-manager'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/xingkongliang/skills-manager/releases/download/v1.40.1/skills-manager_1.40.1_x64_en-US.msi
  InstallerSha256: 5A6505A7C53FC7CA64EB9E82DDA2C9FF576848B9EA370CCEEBCAAD306B1D90C5
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{C96864A6-0B76-4BA7-B2ED-A6D8949C9090}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{08C191C4-BDBB-5964-9F50-BC2B2EDAFD1A}'
ManifestType: installer
ManifestVersion: 1.12.0
