# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: KDE.Haruna
PackageVersion: 1.6.0
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: Haruna
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/multimedia/haruna/master/windows/haruna-master-1470-windows-gcc-x86_64.exe
  InstallerSha256: 7030812F3005A0D5B35A9C5F2E2D09037B581F0666C102B3AC2E86623D7642D2
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/multimedia/haruna/master/windows/haruna-master-1470-windows-gcc-x86_64.exe
  InstallerSha256: 7030812F3005A0D5B35A9C5F2E2D09037B581F0666C102B3AC2E86623D7642D2
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.10.0
