# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ChangeXbc.AgentCompanion
PackageVersion: 0.2.2
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: Agent Companion
ReleaseDate: 2026-10-03
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Agent Companion'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/changexbc/agent-companion/releases/download/v0.2.2/Agent-Companion_windows_x86_64-setup.exe
  InstallerSha256: B654CFA627A865CABA163FE2F39101F801DB883793714DFA0EEFF4F1B63A9951
ManifestType: installer
ManifestVersion: 1.12.0
