# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: TopazLabs.TopazVideoAI
PackageVersion: 7.1.3
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
ProductCode: '{186122F2-21A2-4DD7-88D6-33113005799B}'
ReleaseDate: 2025-08-26
AppsAndFeaturesEntries:
- UpgradeCode: '{E128DC31-1178-4B6F-80A6-61E1B255CAED}'
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.topazlabs.com/deploy/TopazVideoAI/7.1.3/TopazVideoAI-7.1.3.msi
  InstallerSha256: 99B942251A573AD22531CF97C0664675B84FAA47E31F616298F0289FCE6D056A
ManifestType: installer
ManifestVersion: 1.10.0
