# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenLogic.OpenJDK.22.JRE
PackageVersion: 22.0.2.9
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Custom: ADDLOCAL=ALL
UpgradeBehavior: install
Commands:
- jar
- jarsigner
- java
- javac
- javadoc
- javap
- javaw
- jconsole
- jdeprscan
- jdeps
- jlink
- jmod
- jps
- jshell
- jstat
- keytool
FileExtensions:
- class
- jar
- java
- jsp
ProductCode: '{1B287172-A3A8-40C0-80E4-D7EE146FE41B}'
ReleaseDate: 2025-08-22
AppsAndFeaturesEntries:
- DisplayName: OpenLogic-OpenJDK JRE with Hotspot 22.0.2+9 (x64)
  UpgradeCode: '{FBB94BC4-EC80-412D-AF16-2B5F79FE3E58}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\OpenLogic\jre-22.0.2.9-hotspot'
Installers:
- Architecture: x64
  InstallerUrl: https://builds.openlogic.com/downloadJDK/openlogic-openjdk-jre/22.0.2+9/openlogic-openjdk-jre-22.0.2+9-windows-x64.msi
  InstallerSha256: 0A4A729565C84D71D34100699AF2923D13562132D88482C5F50DC9914EC02B92
ManifestType: installer
ManifestVersion: 1.12.0
