# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.PasswordManager
PackageVersion: 1.0.3.2
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente Password Manager 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/passwordmanagerx86
  InstallerSha256: 71C17B6938AD9A5A1D3508D4F50E9C3BC184B6C189BF2D934D7D232216B46DC8
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/passwordmanagerx64
  InstallerSha256: E804ADDB007E4CE0C86F1C6C047C47F9E5A0ED1345CEA06F802B0E817E34F638
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/passwordmanagerarm64
  InstallerSha256: 212866F7D6B0694D3D1939F561F22D45BF502B46925C98A4EFC3432F79103D17
ManifestType: installer
ManifestVersion: 1.12.0
