# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Alibaba.QoderIDE.CN
PackageVersion: 1.106.3
InstallerType: inno
InstallerSwitches:
  Custom: /mergetasks=!runcode
UpgradeBehavior: install
Protocols:
- qoder-cn
- qoder-cn-ide
FileExtensions:
- ascx
- asp
- aspx
- bash
- bash_login
- bash_logout
- bash_profile
- bashrc
- bib
- bowerrc
- c
- c++
- cc
- cfg
- cjs
- clj
- cljs
- cljx
- clojure
- cls
- cmake
- coffee
- config
- containerfile
- cpp
- cs
- cshtml
- csproj
- css
- csv
- csx
- ctp
- cxx
- dart
- diff
- dockerfile
- dot
- dtd
- editorconfig
- edn
- erb
- eyaml
- eyml
- fs
- fsi
- fsscript
- fsx
- gemspec
- gitattributes
- gitconfig
- gitignore
- go
- gradle
- groovy
- h
- h++
- handlebars
- hbs
- hh
- hpp
- htm
- html
- hxx
- ini
- ipynb
- jade
- jav
- java
- js
- jscsrc
- jshintrc
- jshtm
- json
- jsp
- jsx
- less
- log
- lua
- m
- makefile
- markdown
- md
- mdoc
- mdown
- mdtext
- mdtxt
- mdwn
- mjs
- mk
- mkd
- mkdn
- ml
- mli
- npmignore
- php
- phtml
- pl
- pl6
- plist
- pm
- pm6
- pod
- pp
- profile
- properties
- ps1
- psd1
- psgi
- psm1
- py
- pyi
- r
- rb
- rhistory
- rprofile
- rs
- rst
- rt
- sass
- scss
- sh
- shtml
- sql
- svg
- t
- tex
- toml
- ts
- tsx
- txt
- vb
- vue
- wxi
- wxl
- wxs
- xaml
- xhtml
- xml
- yaml
- yml
- zsh
ReleaseDate: 2026-09-23
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://ide.qoder.com.cn/qoder/release/1.32.0/QoderCNIDEUserSetup-x64.exe
  InstallerSha256: 8CA6DCE48C2CD702F45A246A8CC1F22370B4671D7EC0EA4106263B0036B6D5CC
  ProductCode: '{5D8EA147-6C69-472E-B958-C37C7EFE95A2}_is1'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://ide.qoder.com.cn/qoder/release/1.32.0/QoderCNIDESetup-x64.exe
  InstallerSha256: 421EBCA980CF63317B1C5A723FA86AE5187820FB5ABCA520F1A3F1354E3C2A08
  ProductCode: '{BC6ADD90-08CA-4DB6-BA20-880304768E9F}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
