# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Alibaba.QoderIDE.CN
PackageVersion: 1.106.3
PackageLocale: zh-CN
Publisher: Alibaba Cloud
PublisherUrl: https://qoder.cn/
PublisherSupportUrl: https://docs.qoder.cn/support/faq
PrivacyUrl: https://terms.alicdn.com/legal-agreement/terms/privacy_policy_full/20231023213159724/20231023213159724.html
Author: 通义云启（杭州）信息技术有限公司
PackageName: Qoder CN IDE
PackageUrl: https://qoder.cn/download
License: 专有软件
LicenseUrl: https://terms.alicdn.com/legal-agreement/terms/c_platform_service_agreement/20231023213402278/20231023213402278.html
Copyright: Copyright (C) 2026 Qoder. All rights reserved
CopyrightUrl: https://terms.alicdn.com/legal-agreement/terms/c_platform_service_agreement/20231023213402278/20231023213402278.html
ShortDescription: 面向真实软件开发的 AI 原生 Qoder CN IDE。
Description: Qoder CN IDE 是阿里云推出的面向真实软件开发的 AI 原生集成开发环境。它将增强型上下文工程与智能体无缝结合，全面理解您的代码库，并系统化地完成软件开发任务。底层支持 GLM、DeepSeek、Kimi、MiniMax 等国内主流大模型，全链路在国内云上部署，满足金融、政务等行业对数据安全与合规的高要求。适用于 Windows 和 macOS 系统。Qoder CN 系列原名“智能编码助手通义灵码”，已于 2026 年 5 月 20 日正式更名。
Tags:
- 人工智能
- 代码
- 大语言模型
- 开发
- 智能体
- 编程
- 自主智能
ReleaseNotesUrl: https://docs.qoder.cn/product-overview/qoder-cn-update-log
PurchaseUrl: https://qoder.cn/pricing
Documentations:
- DocumentLabel: 文档
  DocumentUrl: https://docs.qoder.cn/
ManifestType: defaultLocale
ManifestVersion: 1.12.0
