# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Alibaba.QoderIDE.CN
PackageVersion: 1.106.3
PackageLocale: en-US
License: Proprietary
ShortDescription: The AI-native IDE built for real software development.
Description: Qoder CN IDE is an AI-native integrated development environment built by Alibaba Cloud for real software development. It seamlessly integrates enhanced context engineering with intelligent agents to gain a comprehensive understanding of your codebase and systematically tackles software development tasks. Powered by leading domestic large language models such as GLM, DeepSeek, Kimi, and MiniMax, it is fully deployed on domestic cloud infrastructure to meet the data security and compliance requirements of industries like finance and government. Available for Windows and macOS. The Qoder CN family was formerly known as Lingma.
Tags:
- agent
- agentic
- ai
- code
- coding
- develop
- development
- large-language-model
- llm
- programming
Documentations:
- DocumentLabel: Docs
  DocumentUrl: https://docs.qoder.cn/
ManifestType: locale
ManifestVersion: 1.12.0
