# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: PTV.Vistro.2026
PackageVersion: 2026.00-08
PackageLocale: zh-CN
License: 专有软件
ShortDescription: 交通影响分析与信号优化软件。
Description: PTV Vistro 是一款综合性的交通影响分析与信号优化工具，为交通影响研究与信号配时提供完整的工作流程。
Tags:
- 交通
- 信号优化
ManifestType: locale
ManifestVersion: 1.12.0
