# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: PTV.Vistro.2026
PackageVersion: 2026.00-08
PackageLocale: en-US
Publisher: PTV Group
PublisherUrl: https://www.ptvgroup.com/
PublisherSupportUrl: https://support.ptvgroup.com/
PrivacyUrl: https://www.ptvgroup.com/en/terms-privacy
Author: PTV Planung Transport Verkehr GmbH
PackageName: PTV Vistro
PackageUrl: https://www.ptvgroup.com/en/products/traffic-engineering-software-ptv-vistro
License: Proprietary
LicenseUrl: https://www.ptvgroup.com/en/terms-privacy
Copyright: © PTV Planung Transport Verkehr GmbH
CopyrightUrl: https://www.ptvgroup.com/en/terms-privacy
ShortDescription: Traffic impact analysis and signal optimization software.
Description: PTV Vistro is your all-in-one traffic engineering tool. It provides a complete workflow for traffic impact studies and signal timing.
Tags:
- engineering
- signal-optimization
- traffic
ReleaseNotesUrl: https://cgi.ptvgroup.com/visionSetups/Setups/VISTRO/260/Release%20Notes_Vistro_2026.00-08_EN.pdf
ManifestType: defaultLocale
ManifestVersion: 1.12.0
