# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.gu-IN
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b8/win32/gu-IN/Firefox%20Setup%20145.0b8.exe
  InstallerSha256: 8906AE89907CF1B0BC029BCC39DFC20BF834F4D80CEEA98033FE0D3818CB6F2D
  ProductCode: Firefox Developer Edition 145.0 (x86 gu-IN)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b8/win64/gu-IN/Firefox%20Setup%20145.0b8.exe
  InstallerSha256: DA050309FE829DD7C4401E14A017E73FADDA016693194C31D3D40AEEEDBA9F80
  ProductCode: Firefox Developer Edition 145.0 (x64 gu-IN)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b8/win64-aarch64/gu-IN/Firefox%20Setup%20145.0b8.exe
  InstallerSha256: DDA83CAAACC49CCF1319D15D846D470EAB4C1C67E07017F65E7D6301D33019BA
  ProductCode: Firefox Developer Edition 145.0 (arm64 gu-IN)
ManifestType: installer
ManifestVersion: 1.10.0
