# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NGLSL.Kite
PackageVersion: 0.5.0
InstallerType: nullsoft
Scope: machine
ProductCode: Kite
ReleaseDate: 2026-10-01
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Kite'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/NGLSL/Kite/releases/download/v0.5.0/kite-setup.exe
  InstallerSha256: F4AE459E9CC56D8A9F7BD6493444681FE107DDEFBA5B76037B36C62FDCB21629
ManifestType: installer
ManifestVersion: 1.12.0
