# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: VicinaeHQ.Vicinae
PackageVersion: 0.29.1
PackageLocale: zh-CN
ShortDescription: 专注的桌面启动器——原生、快速、可扩展。
Description: |-
  Vicinae 是一款高性能的桌面原生命令面板。开箱即用，它可以作为应用搜索、剪贴板历史、文本扩展（代码片段）、文件搜索、浏览器标签页切换器、表情选择器、计算器、窗口/工作区切换器、字体浏览器和音量控制器。

  需要更多功能时，Vicinae 支持多种扩展方式：

  - React/Typescript 扩展，兼容 Raycast 生态，并内置 Vicinae 商店与 Raycast 商店集成
  - 脚本命令，同样兼容 Raycast 的同名功能，并带有 Vicinae 特有的增强
  - dmenu 风格的菜单创建
Tags:
- raycast
- 剪贴板历史
- 启动器
- 命令面板
- 效率
Documentations:
- DocumentLabel: 用户文档
  DocumentUrl: https://docs.vicinae.com/
ManifestType: locale
ManifestVersion: 1.12.0
