# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VicinaeHQ.Vicinae
PackageVersion: 0.29.1
InstallerType: inno
Scope: user
UpgradeBehavior: install
Protocols:
- com.raycast
- raycast
- vicinae
ProductCode: '{C698C8E4-B6C9-4C86-A9AA-520A6D2E45A1}_is1'
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/vicinaehq/vicinae/releases/download/v0.29.1/vicinae-x64-setup.exe
  InstallerSha256: 40EA3EA57D727D7F2AEEAEB950B5A5FF61BAA23F048C49F4B1053419B5A8DBDB
ManifestType: installer
ManifestVersion: 1.12.0
