# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Plenom.kuandoHUB
PackageVersion: 2.1.5.0
InstallerType: zip
NestedInstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
ReleaseDate: 2026-10-08
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: kuandoHUBSetup.msi
  InstallerUrl: https://www.plenom.com/download/130526/
  InstallerSha256: 7CF8ADBA7555012E849574E40E71FB07BDB2D0CB5F50A00ED480A017FA6A5667
  ProductCode: '{1AC2C329-E0C0-4380-BA95-E9C7B69E4DFC}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{0CE02261-70C2-4F9B-8FD5-B8608451C132}'
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: kuandoHUBSetup_64bit.msi
  InstallerUrl: https://www.plenom.com/download/130526/
  InstallerSha256: 7CF8ADBA7555012E849574E40E71FB07BDB2D0CB5F50A00ED480A017FA6A5667
  ProductCode: '{08A8B12B-2252-4081-979D-A120D4AFED4B}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{EE01CA42-F3AC-4C42-A33D-7F4B2EAE3DD1}'
ManifestType: installer
ManifestVersion: 1.12.0
