# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Amazon.CloudWatchAgent
PackageVersion: 1.4.37929
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: '{7D978239-01BB-400C-88C2-0B3997307DA3}'
ReleaseDate: 2026-09-23
AppsAndFeaturesEntries:
- UpgradeCode: '{C537C936-91B3-4270-94D7-E128ACFC3E86}'
Installers:
- Architecture: x64
  InstallerUrl: https://amazoncloudwatch-agent.s3.amazonaws.com/windows/amd64/1.300073.2b1889/amazon-cloudwatch-agent.msi
  InstallerSha256: 9001BFC40366DC677221FE16EC6B2E505BE980B9A044077AFB99D1CD6C424A58
ManifestType: installer
ManifestVersion: 1.12.0
