# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NGLSL.Kite
PackageVersion: 0.4.3
InstallerType: nullsoft
Scope: machine
ProductCode: Kite
ReleaseDate: 2026-09-29
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Kite'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/NGLSL/Kite/releases/download/v0.4.3/kite-setup.exe
  InstallerSha256: 8C1FC2EF9ABB7847207AD2F41AD8B53D3D18C1F740351398AF54C2DDE9536FAC
ManifestType: installer
ManifestVersion: 1.12.0
