# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OSGeo.QGIS
PackageVersion: 4.2.3
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: uninstallPrevious
FileExtensions:
- qgs
- qgz
- qlr
- qml
- qpt
ProductCode: '{4F4B34D4-F82F-1014-AE3E-B2146432C84E}'
ReleaseDate: 2026-09-25
AppsAndFeaturesEntries:
- DisplayName: QGIS 4.2.3 'Belém do Pará'
Installers:
- Architecture: x64
  InstallerUrl: https://qgis.org/downloads/QGIS-OSGeo4W-4.2.3-2.msi
  InstallerSha256: C9B4B837350D00EECB77AE5C965219B3F74776E1921F7460B3859C898F38B1CF
ManifestType: installer
ManifestVersion: 1.12.0
