# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Genesys.GenesysCloudBackgroundAssistant
PackageVersion: 1.5.335.0
InstallerType: burn
Scope: machine
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ProductCode: '{3B8BA20F-6683-4FB9-8470-A750769113C1}'
ReleaseDate: 2025-05-19
AppsAndFeaturesEntries:
- UpgradeCode: '{869F55A6-C5DD-449D-BF50-03A916557107}'
Installers:
- Architecture: x86
  InstallerUrl: https://dhqbrvplips7x.cloudfront.net/background-assistant-windows/1.5.335-237/genesys-cloud-background-assistant-windows-1.5.335.exe
  InstallerSha256: 09CC186ADFA9E8F30A09C5476B9B59D02FC98637EEED49DC6D69326CE5CEE743
ManifestType: installer
ManifestVersion: 1.10.0
