# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EnvBox.Aura
PackageVersion: 0.3.12
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
ProductCode: Aura
ReleaseDate: 2026-10-08
ElevationRequirement: elevationRequired
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Aura'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/NGLSL/Aura/releases/download/v0.3.12/aura-setup.exe
  InstallerSha256: 946661D2E6F98257F0753908B8155A56B21691403CCE02672E433F6BC853F5DC
ManifestType: installer
ManifestVersion: 1.12.0
