# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: PTV.Vissim.2026
PackageVersion: 2026.00-10
PackageLocale: zh-CN
License: 专有软件
ShortDescription: 多模式交通模拟软件。
Description: 全球领先的交通模拟软件 PTV Vissim 使交通规划师、工程师和咨询顾问能够在交通措施实施之前对其进行规划、测试和论证。它可真实、细致且直观地模拟任何多模式微观交通场景。
Tags:
- 交通
- 交通模拟
ManifestType: locale
ManifestVersion: 1.12.0
