# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: PTV.Vissim.2026
PackageVersion: 2026.00-10
PackageLocale: en-US
Publisher: PTV Group
PublisherUrl: https://www.ptvgroup.com/
PublisherSupportUrl: https://support.ptvgroup.com/
PrivacyUrl: https://www.ptvgroup.com/en/terms-privacy
Author: PTV Planung Transport Verkehr GmbH
PackageName: PTV Vissim
PackageUrl: https://www.ptvgroup.com/en/products/ptv-vissim
License: Proprietary
LicenseUrl: https://www.ptvgroup.com/en/terms-privacy
Copyright: © PTV Planung Transport Verkehr GmbH
CopyrightUrl: https://www.ptvgroup.com/en/terms-privacy
ShortDescription: Multimodal traffic simulation software.
Description: The world's leading traffic simulation software PTV Vissim enables traffic planners, engineers and consultants to plan, test and justify mobility measures before they are implemented.
Tags:
- microscopic
- multimodal
- simulation
- traffic
ReleaseNotesUrl: https://cgi.ptvgroup.com/visionSetups/Setups/VISSIM/260/Release%20Notes_Vissim_2026.00-10_EN.pdf
ManifestType: defaultLocale
ManifestVersion: 1.12.0
