# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PTV.Vissim.2026
PackageVersion: 2026.00-10
InstallerType: inno
Scope: machine
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Wibu-Systems.CodeMeterRuntimeKit
ProductCode: '{VISSIM_260_B02CC8DE-A297-11DE-82EA-0019990EF7FA}_IS0_is1'
ReleaseDate: 2026-08-05
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\PTV Vision\PTV Vissim 2026'
Installers:
- Architecture: x64
  InstallerUrl: https://cgi.ptvgroup.com/visionSetups/Setups/VISSIM/260/Setup_VISSIM_2026.00-10_x64.exe
  InstallerSha256: 78E095D40BD3A4A17B10543FCDDF09B2E4C698D73A4CB2EDC69DD58BCC214F1B
ManifestType: installer
ManifestVersion: 1.12.0
