# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: since2006.ShellRS
PackageVersion: 0.1.7
InstallerType: inno
Scope: user
ProductCode: '{45D9E9F5-84BB-4B09-ABE8-1FFE107ACF96}_is1'
ReleaseDate: 2026-10-10
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\ShellRS'
Installers:
- Architecture: x64
  InstallerUrl: https://dl.shellrs.com/releases/0.1.7/ShellRS-0.1.7-windows-x86_64-setup.exe
  InstallerSha256: 9AA8FFDFFEE0FAC3EF1A020E658EC8D52FBAF11B06B611788B0BB69E243369B9
ManifestType: installer
ManifestVersion: 1.12.0
