# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OSGeo.QGIS_LTR
PackageVersion: 3.44.15
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: uninstallPrevious
FileExtensions:
- qgs
- qgz
- qlr
- qml
- qpt
ProductCode: '{E39B4920-F79A-1014-863B-E5879587D155}'
ReleaseDate: 2026-09-25
AppsAndFeaturesEntries:
- DisplayName: QGIS 3.44.15 'Solothurn'
  UpgradeCode: '{E39BBE19-F79A-1014-863B-E5879587D155}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\QGIS 3.44.11'
Installers:
- Architecture: x64
  InstallerUrl: https://qgis.org/downloads/QGIS-OSGeo4W-3.44.15-1.msi
  InstallerSha256: EB980A4B84E4A040D872DAA025520A2457292D6754C4641B6A26734C3C4FC02A
ManifestType: installer
ManifestVersion: 1.12.0
