# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.PasswordManager
PackageVersion: 1.0.3.3
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente Password Manager 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/passwordmanagerx86
  InstallerSha256: 140A18418B3DA831E8989E999BAFC07125DE446CAEC25D51BAE82EB13EB6C9ED
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/passwordmanagerx64
  InstallerSha256: B859E1338ACFA1D1B3D9977D6F76EFC61E71ECE1F84C8CA68EE15483EA84AD0B
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/passwordmanagerarm64
  InstallerSha256: E0AFFC480D788919CA4188E3955356350BC0A4D0A32516EE15047A250D6320C8
ManifestType: installer
ManifestVersion: 1.12.0
