# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: xiazhi88.Desic-Terminal
PackageVersion: 0.3.1
InstallerType: nullsoft
Scope: user
ProductCode: Desic Terminal
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Desic Terminal'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/xiazhi88/Desic-Terminal/releases/download/v0.3.1/Desic-Terminal_Windows-x64-setup.exe
  InstallerSha256: BBDFC819766FF62FA392B6B4E79F64E59ED15102EFBAD3870D04511D85AE5FB2
ManifestType: installer
ManifestVersion: 1.12.0
