# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Tencent.QiDian
PackageVersion: 6.7.0.22607
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
  InstallLocation: /install_path="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- crmqq
- qdapi
- qdwpa
- qqtel
- tencent
FileExtensions:
- eif
- kipx
ProductCode: '{E354F39D-4B67-4B4F-914F-FFAF55D6F5FF}'
ReleaseDate: 2025-07-29
AppsAndFeaturesEntries:
- ProductCode: '{E354F39D-4B67-4B4F-914F-FFAF55D6F5FF}'
  UpgradeCode: '{65DA7564-D22B-4D0D-B269-7266F754FCE5}'
  InstallerType: msi
Installers:
- Architecture: x86
  InstallerUrl: https://dldir1v6.qq.com/qqfile/crm/qidian/QiDian6.7.0.22607.exe
  InstallerSha256: D87B0EE06013EB834F4655073CACEFB543010AE424B36FA8AA02E1099BD31436
ManifestType: installer
ManifestVersion: 1.10.0
