# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Amazon.SSMAgent
PackageVersion: 3.3.5390.0
InstallerType: burn
Scope: machine
UpgradeBehavior: install
ProductCode: '{c568cb1c-cf5a-4ee8-8b25-3dbdd09af344}'
ReleaseDate: 2026-09-17
AppsAndFeaturesEntries:
- UpgradeCode: '{D66D03A7-CA16-4C0C-B5B2-520F22AE5448}'
Installers:
- Architecture: x64
  InstallerUrl: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/3.3.5390.0/windows_amd64/AmazonSSMAgentSetup.exe
  InstallerSha256: 678AD50B21BF53ACB5A07A5ED27B5555FC4970DFCA4612CA75A066E6AA97458E
ManifestType: installer
ManifestVersion: 1.12.0
