# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.ar
PackageVersion: "151.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Firefox Developer Edition
ReleaseDate: 2026-05-04
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/151.0b6/win32/ar/Firefox%20Setup%20151.0b6.exe
  InstallerSha256: A7DC3961C94648C2EC475BC565C1DDF0749FD4030A4A0A907BA113DFA4A0657D
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/151.0b6/win64/ar/Firefox%20Setup%20151.0b6.exe
  InstallerSha256: 0922DFA20178CE5F09C3FECAA6D8C0B82FE37E98F690EA16B9DFF159189681D6
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/151.0b6/win64-aarch64/ar/Firefox%20Setup%20151.0b6.exe
  InstallerSha256: 2F7CEEA5FC4F99CE22869CAB16EEE0D51B3453D289051D7A78EB367571AB30CE
ManifestType: installer
ManifestVersion: 1.12.0
