# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CrystalLang.Crystal
PackageVersion: 1.21.1
UpgradeBehavior: install
Commands:
- crystal
- shards
FileExtensions:
- cr
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: crystal.exe
    PortableCommandAlias: crystal
  - RelativeFilePath: shards.exe
    PortableCommandAlias: shards
  InstallerUrl: https://github.com/crystal-lang/crystal/releases/download/1.21.1/crystal-1.21.1-windows-x86_64-msvc-unsupported.zip
  InstallerSha256: 696DB553299CA120100C0D81682E2AA78D6D230A1E176623E8F2B43D7149163D
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  ArchiveBinariesDependOnPath: true
- Architecture: x64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/crystal-lang/crystal/releases/download/1.21.1/crystal-1.21.1-windows-x86_64-msvc-unsupported.exe
  InstallerSha256: 58F90EC8D0717F5FD834C1E33AF127CF13A5B2BB36139325C2C092254001B136
  InstallerSwitches:
    Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
    SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART
    Custom: /CURRENTUSER
  ProductCode: '{7C307DDF-447E-46C5-BB3B-47A6F652D7C8}_is1'
- Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://github.com/crystal-lang/crystal/releases/download/1.21.1/crystal-1.21.1-windows-x86_64-msvc-unsupported.exe
  InstallerSha256: 58F90EC8D0717F5FD834C1E33AF127CF13A5B2BB36139325C2C092254001B136
  InstallerSwitches:
    Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
    SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART
    Custom: /ALLUSERS
  ProductCode: '{7C307DDF-447E-46C5-BB3B-47A6F652D7C8}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
