# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: newdee.Magpie
PackageVersion: 0.5.7
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/newdee/magpie/releases/download/v0.5.7/magpie_0.5.7_x64-setup.exe
  InstallerSha256: CB7C54779DB3794A5C2ADB29EC1CE225970204EE144C31E0B7344C4A54AFA6D8
  ProductCode: magpie
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/newdee/magpie/releases/download/v0.5.7/magpie_0.5.7_x64_en-US.msi
  InstallerSha256: 9903FAD767A5248C1F1818FD54BA7425A2160422F8B117E8331D8E7288DC01BB
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{B349B1DC-7853-4C79-8BBC-F701917D4FAB}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{285F4DB5-673C-524F-B28E-235FEC26AD24}'
ManifestType: installer
ManifestVersion: 1.12.0
