# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenVPNTechnologies.OpenVPN
PackageVersion: 2.7.801
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: PRODUCTDIR="<INSTALLPATH>"
UpgradeBehavior: install
Commands:
- openvpn
FileExtensions:
- ovpn
ProductCode: '{C0D194A7-C9F7-4E55-BA12-E6A9EB25534B}'
ReleaseDate: 2026-10-07
Installers:
- Architecture: x86
  InstallerUrl: https://swupdate.openvpn.org/community/releases/OpenVPN-2.7.8-I001-x86.msi
  InstallerSha256: AA71B4D0D5B5C384879FDD1EFACF9363D01022C962386384CCE7BE270AED8EB5
  AppsAndFeaturesEntries:
  - UpgradeCode: '{1195A47B-A37A-4055-9D34-B7A691F7E97B}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\OpenVPN'
- Architecture: x64
  InstallerUrl: https://swupdate.openvpn.org/community/releases/OpenVPN-2.7.8-I001-amd64.msi
  InstallerSha256: 1EA61A3056905B90607D4B0F084C04E5CF3043E07CF192D9CD44B0474F29CC49
  AppsAndFeaturesEntries:
  - UpgradeCode: '{461BDF86-D389-4471-BF36-99806B64C127}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\OpenVPN'
- Architecture: arm64
  InstallerUrl: https://swupdate.openvpn.org/community/releases/OpenVPN-2.7.8-I001-arm64.msi
  InstallerSha256: 6FC0E8899CC5275EE297FB837BC84AA2BC49F8EF96D7AD93EE3FEE1E7163A25C
  AppsAndFeaturesEntries:
  - UpgradeCode: '{1E8C4DDC-9E93-4AE2-9495-DF86821EAA3A}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\OpenVPN'
ManifestType: installer
ManifestVersion: 1.12.0
