# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Youzini-afk.Varin
PackageVersion: 0.9.22
InstallerType: nullsoft
Protocols:
- varin
ProductCode: 97ba5f9d-69e7-5ca0-b9bd-16d3f3697f80
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/Youzini-afk/Varin/releases/download/v0.9.22/Varin-0.9.22-win-x64.exe
  InstallerSha256: EF2B419C6188024A01D135CE840F37DA462D6DDE69DB4BDE049E139B07C2449E
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/Youzini-afk/Varin/releases/download/v0.9.22/Varin-0.9.22-win-x64.exe
  InstallerSha256: EF2B419C6188024A01D135CE840F37DA462D6DDE69DB4BDE049E139B07C2449E
  InstallerSwitches:
    Custom: /allusers
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/Youzini-afk/Varin/releases/download/v0.9.22/Varin-0.9.22-win-arm64.exe
  InstallerSha256: 49C8B039726586A678EE0B216FFFAC5531435A5A6F94F4EF547CA9F31068E92A
  InstallerSwitches:
    Custom: /currentuser
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/Youzini-afk/Varin/releases/download/v0.9.22/Varin-0.9.22-win-arm64.exe
  InstallerSha256: 49C8B039726586A678EE0B216FFFAC5531435A5A6F94F4EF547CA9F31068E92A
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
