# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.hsb
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win32/hsb/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 79C25FD8B0EB7B14826D0530B54F572D1E163299BBD14093BA05941249A73BAA
  ProductCode: Firefox Developer Edition 145.0 (x86 hsb)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64/hsb/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: F70F8C62BD007B43FF7BABAE3A812A4C1DADA8FA2B35F659772DE2E76B670624
  ProductCode: Firefox Developer Edition 145.0 (x64 hsb)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64-aarch64/hsb/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 5C10DFAEAF3A328136C69E46D415A9E30C54AE436A7E92B85EADDE4BFBE5F6C3
  ProductCode: Firefox Developer Edition 145.0 (arm64 hsb)
ManifestType: installer
ManifestVersion: 1.10.0
