# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Anysphere.Cursor
PackageVersion: 3.24.12
InstallerType: inno
InstallerSwitches:
  Custom: /mergetasks=!runcode
UpgradeBehavior: install
Protocols:
- cursor
FileExtensions:
- ascx
- asp
- aspx
- bash
- bash_login
- bash_logout
- bash_profile
- bashrc
- bib
- bowerrc
- c
- c++
- cc
- cfg
- cjs
- clj
- cljs
- cljx
- clojure
- cls
- cmake
- code-workspace
- coffee
- config
- containerfile
- cpp
- cs
- cshtml
- csproj
- css
- csv
- csx
- ctp
- cxx
- dart
- diff
- dockerfile
- dot
- dtd
- editorconfig
- edn
- erb
- eyaml
- eyml
- fs
- fsi
- fsscript
- fsx
- gemspec
- gitattributes
- gitconfig
- gitignore
- go
- gradle
- groovy
- h
- h++
- handlebars
- hbs
- hh
- hpp
- hxx
- ini
- ipynb
- jade
- jav
- java
- js
- jscsrc
- jshintrc
- jshtm
- json
- jsp
- jsx
- less
- log
- lua
- m
- makefile
- markdown
- md
- mdoc
- mdown
- mdtext
- mdtxt
- mdwn
- mjs
- mk
- mkd
- mkdn
- ml
- mli
- npmignore
- php
- phtml
- pl
- pl6
- plist
- pm
- pm6
- pod
- pp
- profile
- properties
- ps1
- psd1
- psgi
- psm1
- py
- pyi
- r
- rb
- rhistory
- rprofile
- rs
- rst
- rt
- sass
- scss
- sh
- shtml
- sql
- svgz
- t
- tex
- toml
- ts
- tsx
- txt
- vb
- vue
- wxi
- wxl
- wxs
- xaml
- xhtml
- xml
- yaml
- yml
- zsh
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://downloads.cursor.com/production/37b865941ccb31e2fc90c685157534efca87f964/win32/x64/user-setup/CursorUserSetup-x64-3.24.12.exe
  InstallerSha256: 94D4292C97F23F097C62963F92FAA6F01ACA6620DA3435306FE97684E79E08CF
  ProductCode: '{DADADADA-ADAD-ADAD-ADAD-ADADADADADAD}}_is1'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://downloads.cursor.com/production/37b865941ccb31e2fc90c685157534efca87f964/win32/x64/system-setup/CursorSetup-x64-3.24.12.exe
  InstallerSha256: 5932298DB1A88E89BC0F66947E816C1D66D9052C03B696199ECF09A985008379
  ProductCode: '{D7D7D7D7-7D7D-7D7D-7D7D-7D7D7D7D7D7D}}_is1'
- Architecture: arm64
  Scope: user
  InstallerUrl: https://downloads.cursor.com/production/37b865941ccb31e2fc90c685157534efca87f964/win32/arm64/user-setup/CursorUserSetup-arm64-3.24.12.exe
  InstallerSha256: 8EA80EFC537AE4F50EB79ECBC499A046D71E88C7EC50A3FE1A232D496A8AF54C
  ProductCode: '{DBDBDBDB-BDBD-BDBD-BDBD-BDBDBDBDBDBD}}_is1'
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://downloads.cursor.com/production/37b865941ccb31e2fc90c685157534efca87f964/win32/arm64/system-setup/CursorSetup-arm64-3.24.12.exe
  InstallerSha256: 7B8D466D0951EC68E805115125CA09B96460EA7249B43571F4CDA6D84F4ACDFE
  ProductCode: '{D8D8D8D8-8D8D-8D8D-8D8D-8D8D8D8D8D8D}}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
