# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: sevensir888.CodexCommandCenter
PackageVersion: 0.1.1
UpgradeBehavior: install
ReleaseDate: 2026-08-29
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/sevensir888/codex-command-center/releases/download/v0.1.1/Codex.Command.Center_0.1.1_x64-setup.exe
  InstallerSha256: 6C9C4C69C303FB9075D6073607150B565F379B4F93EFA413F23B6AE383B26FB4
  ProductCode: Codex Command Center
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Codex Command Center'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/sevensir888/codex-command-center/releases/download/v0.1.1/Codex.Command.Center_0.1.1_x64_en-US.msi
  InstallerSha256: 7267EB84BEAF213BC2C180D21B78BAC294AB3C65D177F711DEE7ED8BAAA5587A
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{7B0DD123-728A-4729-B987-B6FF3546B2E3}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{2229ABD2-F69F-51B2-B80E-A6C6B4F8291C}'
ManifestType: installer
ManifestVersion: 1.12.0
