# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.PhotoCraft
PackageVersion: 0.5.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
FileExtensions:
- avif
- bmp
- exr
- gif
- hdr
- ico
- jpeg
- jpg
- pcraft
- png
- psb
- psd
- qoi
- tga
- tif
- tiff
- webp
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- UpgradeCode: '{D9660F32-2D0A-4ABE-B73D-17BE25F1542C}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/storytold/photocraft/releases/download/v0.5.0/photocraft-0.5.0-windows-x86.msi
  InstallerSha256: 48F0BF5657AA6B62C1C6C14CA665AEA4D7AE0EEF5FC3EC8416920897055CA487
  ProductCode: '{C37E6954-E0F9-4C20-8C22-C8BAE3B420A9}'
- Architecture: x64
  InstallerUrl: https://github.com/storytold/photocraft/releases/download/v0.5.0/photocraft-0.5.0-windows-x64.msi
  InstallerSha256: AD4E1A1E574BAE0B0EB0EA9DD7538DA70A6E5D94D441488D94E1CCC32830BE38
  ProductCode: '{5FFBC1D1-9734-4549-AFDB-19992C885E66}'
- Architecture: arm64
  InstallerUrl: https://github.com/storytold/photocraft/releases/download/v0.5.0/photocraft-0.5.0-windows-arm64.msi
  InstallerSha256: D1E81892C837D38B394401DEF73AAC87B8BF59D4DF0FA8FA43F73341DD397B88
  ProductCode: '{D38A48DF-AE8D-4A81-91FE-E4BD581EF5F1}'
ManifestType: installer
ManifestVersion: 1.12.0
