# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: KDE.KAlarm
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: kalarm
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/pim/kalarm/master/windows/kalarm-master-2905-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: C40C085812FBF12E1FD6A7B2FD16013BD297377336BA1F98CF3AEE614F5E2553
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/pim/kalarm/master/windows/kalarm-master-2905-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: C40C085812FBF12E1FD6A7B2FD16013BD297377336BA1F98CF3AEE614F5E2553
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.10.0
