# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ProteoWizard.ProteoWizard
PackageVersion: 3.0.26274
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
ProductCode: '{95D861FC-A462-49CB-BDB1-85DF52ACBF51}'
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- UpgradeCode: '{644795C6-012A-49B7-A47F-E46E164D3689}'
Installers:
- Architecture: x64
  InstallerUrl: https://mc-tca-01.s3.us-west-2.amazonaws.com/ProteoWizard/bt83/4197455/pwiz-setup-3.0.26274.d6f5df17-x86_64.msi
  InstallerSha256: B0429CCB9EFECDC000C736839AFFB76B0432CA9F7B5907BF10F5B70BCA8DF874
ManifestType: installer
ManifestVersion: 1.12.0
