# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: hardbeat920.MonoCode
PackageVersion: 0.7.1
InstallerType: nullsoft
Scope: user
ProductCode: MonoCode
ReleaseDate: 2026-10-05
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\MonoCode'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/hardbeat920/monocode/releases/download/v0.7.1/MonoCode_0.7.1_x64-setup.exe
  InstallerSha256: EE9E21F472FB2718F4AA8D109002E473A2A2F247535035DA872045A9DC17F7CB
ManifestType: installer
ManifestVersion: 1.12.0
