# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ChuxinNeko.NekoCodeDesktop
PackageVersion: 0.0.7
InstallerType: nullsoft
Scope: user
ProductCode: 5007aadc-759b-50ed-a439-2f8c26d0e560
ReleaseDate: 2026-10-01
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\NekoCode Desktop'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ChuxinNeko/NekoCodeDesktop/releases/download/v0.0.7/NekoCode-Desktop-0.0.7-win-x64.exe
  InstallerSha256: 65C2D1805BD7D9FCF1443BA2AF82450B8ED6C165B941AB225944F0F291B7789A
ManifestType: installer
ManifestVersion: 1.12.0
