# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Nightly
PackageVersion: 156.1.99.29
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser
ReleaseDate: 2026-10-09
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.29/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: 4FE47ABDCA6B18795B6D2CFB37767F1C329CEFC8709D738A9F3CA0DFA732BD99
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.29/BraveBrowserStandaloneNightlySetup32.exe
  InstallerSha256: 4C78F8D1FDA8ED2628CF7C6A11FD26F2DCE8CE398714959DDABD15E1442680BD
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.29/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: 9252D57D762E7E494ED1980916FE2E087CC0DC4369AC58AA8697F6ED59DE3FC0
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.29/BraveBrowserStandaloneNightlySetup.exe
  InstallerSha256: 7C71D714DBFC620DC6078A2F589E2CC285D54E7FA8DCC9CC7D730F0F9E5DBCD3
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.29/BraveBrowserStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: 0E5F43883B23D57CAAC60ED094DE584CC6E0531A71AF5AC3E54F21A9DBB2888C
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.29/BraveBrowserStandaloneNightlySetupArm64.exe
  InstallerSha256: FDD75F40B402B03BD1EBFC411A2177B3BE72B660803728F594517AE6314C077E
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
