# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: darrenprx.lolPing
PackageVersion: 0.5.0
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: fcc9b0cc-d3c2-5751-b36a-bc176194a4e1
ReleaseDate: 2026-10-08
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\lolPing'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/darrenprx/lolPing/releases/download/v0.5.0/lolPing-Setup-0.5.0.exe
  InstallerSha256: CFD72D572AE4733F2E11A254FD339FCB6E9B13BF22C87BC2945C8127A9CFEE23
ManifestType: installer
ManifestVersion: 1.12.0
