# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.WordCraft
PackageVersion: 0.3.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- UpgradeCode: '{49E87D30-BB68-4896-AA1D-F45C833CFC3C}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/storytold/wordcraft/releases/download/v0.3.0/wordcraft-0.3.0-windows-x86.msi
  InstallerSha256: 573D96894424EF7FC262F614E1B71D552D637CEEA0D3CDDBEA20F75156FDDC31
  ProductCode: '{2C815CFF-FBA8-4A80-9F52-AEA964333AFF}'
- Architecture: x64
  InstallerUrl: https://github.com/storytold/wordcraft/releases/download/v0.3.0/wordcraft-0.3.0-windows-x64.msi
  InstallerSha256: 9EF44BC198D361F30AD986BF056C4D255DF032D3CB1B5AB23A75DE2B20A7DE0C
  ProductCode: '{FEA37DD3-B5A9-4BBF-B112-9E5617C9F9F0}'
- Architecture: arm64
  InstallerUrl: https://github.com/storytold/wordcraft/releases/download/v0.3.0/wordcraft-0.3.0-windows-arm64.msi
  InstallerSha256: A17F5B8D3213C9462694DBA532DC99F6148E75FFC79785BDB0C7D285E1B2B161
  ProductCode: '{558B49BC-9CB4-438A-8997-E61530D21F60}'
ManifestType: installer
ManifestVersion: 1.12.0
