# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Python.Python.3.14
PackageVersion: 3.14.8
FileExtensions:
- py
- pyc
- pyd
- pyo
- pyw
- pyz
- pyzw
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerType: burn
  Scope: user
  InstallerUrl: https://www.python.org/ftp/python/3.14.8/python-3.14.8.exe
  InstallerSha256: 963DEF30C7EBC6381A1EE9056D251DDC4520B18391DA2CF0602CFB58F5B80568
  InstallerSwitches:
    InstallLocation: DefaultJustForMeTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=0 PrependPath=1
  UpgradeBehavior: install
  Commands:
  - py
  - python
  - pythonw
  - pyw
  ProductCode: '{c335046b-858f-4462-9d9c-92d104c5e974}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.14.8150.0
    UpgradeCode: '{872DB5D2-A16E-5A3C-B222-176907A65867}'
- Architecture: x86
  InstallerType: burn
  Scope: machine
  InstallerUrl: https://www.python.org/ftp/python/3.14.8/python-3.14.8.exe
  InstallerSha256: 963DEF30C7EBC6381A1EE9056D251DDC4520B18391DA2CF0602CFB58F5B80568
  InstallerSwitches:
    InstallLocation: DefaultAllUsersTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=1 PrependPath=1
  UpgradeBehavior: install
  Commands:
  - py
  - python
  - pythonw
  - pyw
  ProductCode: '{c335046b-858f-4462-9d9c-92d104c5e974}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.14.8150.0
    UpgradeCode: '{872DB5D2-A16E-5A3C-B222-176907A65867}'
  ElevationRequirement: elevatesSelf
- Architecture: x64
  InstallerType: burn
  Scope: user
  InstallerUrl: https://www.python.org/ftp/python/3.14.8/python-3.14.8-amd64.exe
  InstallerSha256: 759BE887B96E736A3CA886DAF8D575F18FCAE1A09EFAB6902F42D59E8999F8EF
  InstallerSwitches:
    InstallLocation: DefaultJustForMeTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=0 PrependPath=1
  UpgradeBehavior: install
  Commands:
  - py
  - python
  - pythonw
  - pyw
  ProductCode: '{2528e662-d535-44b5-82ab-3b0cd1175719}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.14.8150.0
    UpgradeCode: '{AF37ADBF-A448-569B-983A-EE8E6DEC0484}'
- Architecture: x64
  InstallerType: burn
  Scope: machine
  InstallerUrl: https://www.python.org/ftp/python/3.14.8/python-3.14.8-amd64.exe
  InstallerSha256: 759BE887B96E736A3CA886DAF8D575F18FCAE1A09EFAB6902F42D59E8999F8EF
  InstallerSwitches:
    InstallLocation: DefaultAllUsersTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=1 PrependPath=1
  UpgradeBehavior: install
  Commands:
  - py
  - python
  - pythonw
  - pyw
  ProductCode: '{2528e662-d535-44b5-82ab-3b0cd1175719}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.14.8150.0
    UpgradeCode: '{AF37ADBF-A448-569B-983A-EE8E6DEC0484}'
  ElevationRequirement: elevatesSelf
- Architecture: arm64
  InstallerType: burn
  Scope: user
  InstallerUrl: https://www.python.org/ftp/python/3.14.8/python-3.14.8-arm64.exe
  InstallerSha256: 53BA74B5B4370EB823FE0005EEDEAB907479F7339CECB11EFEA0E75AB5F10CFC
  InstallerSwitches:
    InstallLocation: DefaultJustForMeTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=0 PrependPath=1
  UpgradeBehavior: install
  Commands:
  - py
  - python
  - pythonw
  - pyw
  ProductCode: '{3f8eacc5-effa-4709-b9c9-600cc826a812}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.14.8150.0
    UpgradeCode: '{2F1F7880-E1EB-54EA-B512-067E199D4E88}'
- Architecture: arm64
  InstallerType: burn
  Scope: machine
  InstallerUrl: https://www.python.org/ftp/python/3.14.8/python-3.14.8-arm64.exe
  InstallerSha256: 53BA74B5B4370EB823FE0005EEDEAB907479F7339CECB11EFEA0E75AB5F10CFC
  InstallerSwitches:
    InstallLocation: DefaultAllUsersTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=1 PrependPath=1
  UpgradeBehavior: install
  Commands:
  - py
  - python
  - pythonw
  - pyw
  ProductCode: '{3f8eacc5-effa-4709-b9c9-600cc826a812}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.14.8150.0
    UpgradeCode: '{2F1F7880-E1EB-54EA-B512-067E199D4E88}'
  ElevationRequirement: elevatesSelf
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: python.exe
  - RelativeFilePath: pythonw.exe
  InstallerUrl: https://www.python.org/ftp/python/3.14.8/python-3.14.8-win32.zip
  InstallerSha256: 6C83621F4F02C5E026D8132D9622DD79CA28B69232602406D84410F2F551DA9D
  Commands:
  - python
  - pythonw
  ArchiveBinariesDependOnPath: true
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: python.exe
  - RelativeFilePath: pythonw.exe
  InstallerUrl: https://www.python.org/ftp/python/3.14.8/python-3.14.8-amd64.zip
  InstallerSha256: 4873947A8AFC037846B180312B83C744A4146A851CFD316A75C3125A4D8299DA
  Commands:
  - python
  - pythonw
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: python.exe
  - RelativeFilePath: pythonw.exe
  InstallerUrl: https://www.python.org/ftp/python/3.14.8/python-3.14.8-arm64.zip
  InstallerSha256: B147A5719D871F5B16B18A7DA8533DB1926F06018C2B00F1ECD20444F7A40057
  Commands:
  - python
  - pythonw
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
