# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GoLang.Go
PackageVersion: 1.27.2
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
Commands:
- go
- gofmt
FileExtensions:
- go
ReleaseDate: 2026-10-08
Installers:
- Architecture: x86
  InstallerUrl: https://go.dev/dl/go1.27.2.windows-386.msi
  InstallerSha256: C0765105821D2FB884439FCCD95BEFC7BD6E29A60BDF1E790464A68E6A888143
  ProductCode: '{52159A2B-4850-46E0-A32E-6BF41C3EBB4F}'
  AppsAndFeaturesEntries:
  - DisplayName: Go Programming Language 386 go1.27.2
    UpgradeCode: '{1C3114EA-08C3-11E1-9095-7FCA4824019B}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\Go'
- Architecture: x64
  InstallerUrl: https://go.dev/dl/go1.27.2.windows-amd64.msi
  InstallerSha256: DC673C9207A83F95031549FAFE72CC0B4C4554A1C16B373D875E90CF8D995ED9
  ProductCode: '{D19793D5-E7D3-4560-8F3E-7608ACDD4163}'
  AppsAndFeaturesEntries:
  - DisplayName: Go Programming Language amd64 go1.27.2
    UpgradeCode: '{22EA7650-4AC6-4001-BF29-F4B8775DB1C0}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Go'
- Architecture: arm64
  InstallerUrl: https://go.dev/dl/go1.27.2.windows-arm64.msi
  InstallerSha256: F7B5FC37B49962098F6DE76CE81B49EB6F657767CE4B1678560F650E5E422B06
  ProductCode: '{F93F9B47-6489-4DFC-8B1C-20BE7A9005C8}'
  AppsAndFeaturesEntries:
  - DisplayName: Go Programming Language arm64 go1.27.2
    UpgradeCode: '{21ADE9A3-3FDD-4BA6-BEA6-C85ABADC9488}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Go'
ManifestType: installer
ManifestVersion: 1.12.0
