# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.LightCraft
PackageVersion: 0.2.1
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- UpgradeCode: '{229BB552-5EFD-479A-BA86-8CB6D926390C}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/storytold/lightcraft/releases/download/v0.2.1/lightcraft-0.2.1-windows-x64.msi
  InstallerSha256: C364BFD25F0D2110D0C7C8C1EF8A3C084848922017176E793CBA9A62123374C4
  ProductCode: '{D5B5409B-5262-4517-9EA0-EC445B2CEDBC}'
- Architecture: x86
  InstallerUrl: https://github.com/storytold/lightcraft/releases/download/v0.2.1/lightcraft-0.2.1-windows-x86.msi
  InstallerSha256: AF086D310C13EA62B092E4946DA63C134AA8E22333558CFDBC864CC278520B2D
  ProductCode: '{CA556D0A-340C-4B41-9437-62AACABF58D4}'
ManifestType: installer
ManifestVersion: 1.12.0
