# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Predidit.Kazumi
PackageVersion: 2.3.7.0
PackageLocale: zh-CN
Publisher: Predidit
PublisherUrl: https://kazumi.app/
PublisherSupportUrl: https://github.com/Predidit/Kazumi/issues
PackageName: Kazumi
PackageUrl: https://github.com/Predidit/Kazumi
License: GPL-3.0-only
LicenseUrl: https://github.com/Predidit/Kazumi/blob/HEAD/LICENSE
ShortDescription: 基于自定义规则的番剧采集与在线观看应用。
Description: Kazumi 是一个使用 Flutter 开发的基于自定义规则的番剧采集与在线观看程序，支持流媒体在线观看、弹幕和基于 Anime4K 的实时超分辨率。它支持使用基于 XPath 语法的最多五行选择器构建自己的规则，并支持规则导入与规则分享。
Tags:
- 动漫
- 动画
- 弹幕
- 番剧
- 视频
ReleaseNotes: |-
  - 改进的视频截图功能 (#1697 #1144) (@Predidit)
  - 新增弹幕简繁转换设置 (#1108 #1923) (@Predidit)
  - 番剧详情页面现在支持复制标题与保存封面 (#2575) (@Predidit)
  - 现在可以在滑动快进时滑至播放器边缘取消操作 (#2592) (@Predidit)
  - 新增 Bangumi 番剧条目 ECH 加速选项 (@Predidit)
  - 修复手动检索弹幕时搜索记录无法保留的问题 (@moonrailgun)
  - 修复部分视频来源无法触发人机验证的问题 (#2578) (@jzy834894319)
  - 修复 Linux 平台打开播放器、切换剧集或播放结束时可能崩溃的问题 (#2587) (@Predidit)
  - 修复桌面平台设置子页面窗口控制按钮重复显示的问题 (#2589) (@Predidit)
  - 修复切换原生标题栏设置后窗口控制按钮显示异常的问题 (@Predidit)
ReleaseNotesUrl: https://github.com/Predidit/Kazumi/releases/tag/2.3.7
Documentations:
- DocumentLabel: 文档
  DocumentUrl: https://kazumi.app/docs/
ManifestType: defaultLocale
ManifestVersion: 1.12.0
