# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Predidit.Kazumi
PackageVersion: 2.3.7.0
PackageLocale: en-US
ShortDescription: A rule-based anime collection and streaming application.
Description: Kazumi is a Flutter-based application for collecting and streaming anime from custom rules. It supports online streaming, danmaku (bullet comments), and real-time super resolution based on Anime4K. Rules can be built with up to five lines of XPath-based selectors, and rule import and sharing are supported.
Tags:
- anime
- danmaku
- danmu
- streaming
- video
Documentations:
- DocumentLabel: Docs
  DocumentUrl: https://kazumi.app/docs/
ManifestType: locale
ManifestVersion: 1.12.0
