# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Youqu.ToDesk
PackageVersion: 4.7.7.1
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Protocols:
- todesk
ProductCode: ToDesk
ReleaseDate: 2025-05-15
Installers:
- Architecture: x86
  InstallerUrl: https://dl.todesk.com/irrigation/ToDesk_4.7.7.1.exe
  InstallerSha256: DCB8BB6244FD82ED26E1390F33FB6362AD01948D48B2449F6AFEE907D60B4C71
ManifestType: installer
ManifestVersion: 1.10.0
