# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SergeyMoskalev.CarambaSwitcher.Pro
PackageVersion: 2026.09.26.2
InstallerType: inno
Scope: machine
ProductCode: '{B7E4B0C2-9B1A-4F3E-8D2A-1C5E7A9F60D3}_is1'
ReleaseDate: 2026-09-26
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Caramba Switcher'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.caramba-switcher.com/files/win/CarambaSwitcherProSetup-latest.exe
  InstallerSha256: AB3A737478ED11892242A2289ED2CF4190CB55445D34A2EED125FDA1979DFAF3
ManifestType: installer
ManifestVersion: 1.12.0
