# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: muutot.Clipboard
PackageVersion: 1.7.2
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/muutot/Clipboard/releases/download/v1.7.2/Clipboard_1.7.2_x64-setup.exe
  InstallerSha256: 4B127E47AAEC4BA1CB3E8CA399C3BEF770819234D31A0139893E2384AF56C6FC
  ProductCode: Clipboard
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Clipboard'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/muutot/Clipboard/releases/download/v1.7.2/Clipboard_1.7.2_x64_en-US.msi
  InstallerSha256: C3D02D3375F7FE5E60A466C68826328BE489B28F229A0188F30426AA8B649486
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{3AEE4FC7-B2C5-4A98-90A6-65E868298441}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{D2C48E63-D3DF-5D07-9516-57DF96E4A9D4}'
ManifestType: installer
ManifestVersion: 1.12.0
