# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.si
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win32/si/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: B1E8C80BA9665EF6249391AE734E0F6B7DFC2C0F3C62107F225431697BB00B93
  ProductCode: Firefox Developer Edition 145.0 (x86 si)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64/si/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 2B8AA18F7B572BC237A9ECA2483B127B339508F283857145C44F2E5BE283C1CD
  ProductCode: Firefox Developer Edition 145.0 (x64 si)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64-aarch64/si/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 669BD57770E6B44DDEC076E992010A40C35274BFF88E65D645BC70058D0AB69E
  ProductCode: Firefox Developer Edition 145.0 (arm64 si)
ManifestType: installer
ManifestVersion: 1.10.0
