# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tencent.QQMusic
PackageVersion: "22.75"
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: silence=1
  SilentWithProgress: silence=1
  InstallLocation: installdir="<INSTALLPATH>"
  Custom: runafterinstall=no
UpgradeBehavior: install
FileExtensions:
- aac
- ac3
- aif
- aiff
- ape
- au
- caf
- cue
- dff
- dsf
- dts
- flac
- lrc
- m4a
- m4r
- mflac
- mgg
- mid
- mp3
- mpc
- ogg
- opus
- qmc0
- qmc2
- qmc3
- qmc4
- qmc6
- qmc8
- qmcflac
- qrc
- qsc3
- tac
- tkm
- tta
- wav
- wma
- wv
ProductCode: QQMusic
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://c.y.qq.com/cgi-bin/file_redirect.fcg?bid=dldir&file=ecosfile%2Fmusic_clntupate%2Fpc%2Fother%2FQQMusic_Setup_2275.exe&sign=1-fafc954a8e5af0f07d60f585426ab253067628c30c79839430666377ebab14a4-6aca068d
  InstallerSha256: 6BC4BFB9428A2E166D07D0B873A5447B6FA12817401023B967EDADDF59ACC042
- Architecture: x86
  InstallerUrl: https://c.y.qq.com/cgi-bin/file_redirect.fcg?bid=dldir&file=ecosfile%2Fmusic_clntupate%2Fpc%2Fother%2FQQMusic_Setup_2275.exe&sign=1-fafc954a8e5af0f07d60f585426ab253067628c30c79839430666377ebab14a4-6aca068d
  InstallerSha256: 6BC4BFB9428A2E166D07D0B873A5447B6FA12817401023B967EDADDF59ACC042
ManifestType: installer
ManifestVersion: 1.12.0
