# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.th
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win32/th/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 03EB4068412116D79C31357EBC15E6E8682358FEFA9DE3E0733B2109DC005A58
  ProductCode: Firefox Developer Edition 145.0 (x86 th)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64/th/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 11EE6F2C27E567DCF8FD56E86EF27C095AE6B00EDA2FDE7333D96E44C5143501
  ProductCode: Firefox Developer Edition 145.0 (x64 th)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64-aarch64/th/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 31A432A06B0C424CA5E763F0E94AEAE735BFDC4296067AFDCC53E3A60960F5ED
  ProductCode: Firefox Developer Edition 145.0 (arm64 th)
ManifestType: installer
ManifestVersion: 1.10.0
