# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenLogic.OpenJDK.11.JDK
PackageVersion: 11.0.32.9
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Custom: ADDLOCAL=ALL
UpgradeBehavior: install
Commands:
- jar
- jarsigner
- java
- javac
- javadoc
- javap
- javaw
- jconsole
- jdeprscan
- jdeps
- jlink
- jmod
- jps
- jshell
- jstat
- keytool
FileExtensions:
- class
- jar
- java
- jsp
ProductCode: '{C7007139-4746-41BE-9616-2496E928C700}'
ReleaseDate: 2026-08-06
AppsAndFeaturesEntries:
- DisplayName: OpenLogic-OpenJDK JDK with Hotspot 11.0.32+9 (x64)
  UpgradeCode: '{7B269F4A-2DA7-43DC-A1AF-C6D0C1839962}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\OpenLogic\jdk-11.0.32.9-hotspot'
Installers:
- Architecture: x64
  InstallerUrl: https://builds.openlogic.com/downloadJDK/openlogic-openjdk/11.0.32+9/openlogic-openjdk-11.0.32+9-windows-x64.msi
  InstallerSha256: 25F55655A127E53A5DABCD6BBC20BA4C39971CAD54A3DE64812C69AC79C81F99
ManifestType: installer
ManifestVersion: 1.12.0
