# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.BraveOrigin.Nightly
PackageVersion: 156.1.99.29
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Origin-Nightly
ReleaseDate: 2026-10-09
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.29/BraveOriginStandaloneSilentNightlySetup32.exe
  InstallerSha256: 4ADCEE5C65C49E814B45D882FC3A272BD6F10CE677B63086805B6FABB6D056B2
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.29/BraveOriginStandaloneNightlySetup32.exe
  InstallerSha256: E7D11447127CF611A10BCD13354FA371FE28DF3394E8171A9270D8E9A5767051
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.29/BraveOriginStandaloneSilentNightlySetup.exe
  InstallerSha256: 62E9EC170CAE18121B19CBF1B17755F3A48A8EB48DBA148E09706887C1523BE3
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.29/BraveOriginStandaloneNightlySetup.exe
  InstallerSha256: 9B361E6D9A7004491495A17DC2449F2961CED904FC2EEAE8BC8B209E44148CAF
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.29/BraveOriginStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: 93B211AF3C7C8B8EA26EDBB9F7E7287C3B88FEED034A83480925CDDC52E46AAC
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.29/BraveOriginStandaloneNightlySetupArm64.exe
  InstallerSha256: 37DEC5186DB2A852A2FED4A6BD30671757F2EF19A7129159AC5C031DC3953336
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
