# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Nimbalyst.Nimbalyst
PackageVersion: 0.80.6
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
FileExtensions:
- markdown
- md
ProductCode: fe58d461-527f-5843-8c07-27b4ab6d3d90
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nimbalyst/nimbalyst/releases/download/v0.80.6/Nimbalyst-Windows-x64.exe
  InstallerSha256: B7F2E307E94F438980F83AB59490D5B969C7D66B0904C857D22E616771670C94
- Architecture: arm64
  InstallerUrl: https://github.com/nimbalyst/nimbalyst/releases/download/v0.80.6/Nimbalyst-Windows-arm64.exe
  InstallerSha256: 7532B1F0922AF31BA2D1EE878765D90CFEABF82CFA58CD21A24FDCD97856CE49
ManifestType: installer
ManifestVersion: 1.12.0
