# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: chelal233.NexusLauncher
PackageVersion: 1.0.3
InstallerType: nullsoft
ProductCode: 4775e92d-a8b9-5c77-9c17-cfe9f608d98c
ReleaseDate: 2026-09-26
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\Nexus Launcher'
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/chelal233/dsh-nexus/releases/download/v1.0.3/dsh-nexus_1.0.3_windows_x64.exe
  InstallerSha256: 2be44b61d3cfec6913d3c5c5f56b7e70b119c020baa4fc5fffbf9491b76adb24
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/chelal233/dsh-nexus/releases/download/v1.0.3/dsh-nexus_1.0.3_windows_x64.exe
  InstallerSha256: 2be44b61d3cfec6913d3c5c5f56b7e70b119c020baa4fc5fffbf9491b76adb24
  InstallerSwitches:
    Custom: /allusers
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/chelal233/dsh-nexus/releases/download/v1.0.3/dsh-nexus_1.0.3_windows_arm64.exe
  InstallerSha256: f8332dee57e77f038d36862e591a0bb3c1f0eb7290055e41494ae43c9240f021
  InstallerSwitches:
    Custom: /currentuser
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/chelal233/dsh-nexus/releases/download/v1.0.3/dsh-nexus_1.0.3_windows_arm64.exe
  InstallerSha256: f8332dee57e77f038d36862e591a0bb3c1f0eb7290055e41494ae43c9240f021
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
