# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: chelal233.NexusLauncher
PackageVersion: 1.0.3
InstallerType: nullsoft
ProductCode: 4775e92d-a8b9-5c77-9c17-cfe9f608d98c
ReleaseDate: 2026-09-26
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\Nexus Launcher'
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/chelal233/dsh-nexus/releases/download/v1.0.3/dsh-nexus_1.0.3_windows_x64.exe
  InstallerSha256: 2BE44B61D3CFEC6913D3C5C5F56B7E70B119C020BAA4FC5FFFBF9491B76ADB24
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/chelal233/dsh-nexus/releases/download/v1.0.3/dsh-nexus_1.0.3_windows_x64.exe
  InstallerSha256: 2BE44B61D3CFEC6913D3C5C5F56B7E70B119C020BAA4FC5FFFBF9491B76ADB24
  InstallerSwitches:
    Custom: /allusers
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/chelal233/dsh-nexus/releases/download/v1.0.3/dsh-nexus_1.0.3_windows_arm64.exe
  InstallerSha256: F8332DEE57E77F038D36862E591A0BB3C1F0EB7290055E41494AE43C9240F021
  InstallerSwitches:
    Custom: /currentuser
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/chelal233/dsh-nexus/releases/download/v1.0.3/dsh-nexus_1.0.3_windows_arm64.exe
  InstallerSha256: F8332DEE57E77F038D36862E591A0BB3C1F0EB7290055E41494AE43C9240F021
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
