# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Alibaba.QoderCLI.CN
PackageVersion: 1.1.65
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: qoderclicn.exe
  PortableCommandAlias: qodercn
Commands:
- qodercn
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://static.qoder.com.cn/qoder-cli-cn/releases/1.1.65/qoderclicn-windows-x64.zip
  InstallerSha256: E565C71E35D9419C1715A6A1BB49CC719C9615CD25224F85B1AF39B2B2C5E642
- Architecture: arm64
  InstallerUrl: https://static.qoder.com.cn/qoder-cli-cn/releases/1.1.65/qoderclicn-windows-arm64.zip
  InstallerSha256: 12951B9C93EB985DF6504DEF5B6875D664977B1BAF8236EDB42D1240889A0496
ManifestType: installer
ManifestVersion: 1.12.0
