# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: newdee.Magpie
PackageVersion: 0.5.9
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/newdee/magpie/releases/download/v0.5.9/magpie_0.5.9_x64-setup.exe
  InstallerSha256: 2EFB421C71B1001FBB6C52C09D2BEDB7F28ECA5D4DCEA5675C6C6194AEDF8BF8
  ProductCode: magpie
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/newdee/magpie/releases/download/v0.5.9/magpie_0.5.9_x64_en-US.msi
  InstallerSha256: A14B232B95DC759E7BD0AA8C950CDEAAD9718D5C745C80632220A46BAD79D31B
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{4457BBEC-2DE0-4A1F-A247-26E583790E9F}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{285F4DB5-673C-524F-B28E-235FEC26AD24}'
ManifestType: installer
ManifestVersion: 1.12.0
