# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Doublebridge.ROSETTAeCTDViewer
PackageVersion: 6.6.1.2079
InstallerType: msi # Advanced Installer
Scope: machine
InstallerSwitches:
  InstallLocation: APPDIR="<INSTALLPATH>"
ProductCode: '{F079421B-7B86-466A-8FC4-DA4307238092}'
ReleaseDate: 2026-08-25
AppsAndFeaturesEntries:
- DisplayName: ROSETTA eCTD Viewer Desktop Edition R6.6.1
  UpgradeCode: '{1E73D09C-935F-4D3F-96B2-B678CC71D97A}'
Installers:
- Architecture: x86
  InstallerUrl: https://www.ectdviewer.com/Rosetta/phoenix/download/desktop/R661/6u2QEP/Setup_ROSETTA_eCTD_Viewer_6.6.1.2079.msi
  InstallerSha256: 7F022023B4A54FCEBB57EF87234476783EE05A3B693293BAF940685727D6C827
ManifestType: installer
ManifestVersion: 1.12.0
