# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WonderIdea.FlipPDFPlus.Corporate
PackageVersion: 8.1.11
InstallerType: zip
NestedInstallerType: inno
NestedInstallerFiles:
- RelativeFilePath: Flip_PDF_Plus_Corp_8.1.11_x64.exe
Scope: machine
UpgradeBehavior: install
FileExtensions:
- flbx
ProductCode: F75236D8-6FA2-4899-AF36-EFF67C50098F_is1
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://static.flipbuilder.com/download/flippdf2/Flip_PDF_Plus_Corp_x64.zip
  InstallerSha256: 2D9B2C01A7B1CB262FDA7B3E67B9F2077645CF11D0381EF430072401E6A8E80A
ManifestType: installer
ManifestVersion: 1.12.0
