# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: newdee.Magpie
PackageVersion: 0.6.3
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/newdee/magpie/releases/download/v0.6.3/magpie_0.6.3_x64-setup.exe
  InstallerSha256: B0B863E68F259F7FABEE0F3ABE450B850A3B87C9A11CE6ED7E311F8DA19A3925
  ProductCode: magpie
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/newdee/magpie/releases/download/v0.6.3/magpie_0.6.3_x64_en-US.msi
  InstallerSha256: 2C0D50E9F95AB8A01938A2DC7966E75F28AB588AA8DD12053B5CAADFA49DB7FC
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{9AB4169E-786A-4B2B-BB4E-9B1158A83EA1}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{285F4DB5-673C-524F-B28E-235FEC26AD24}'
ManifestType: installer
ManifestVersion: 1.12.0
