# Created with YamlCreate.ps1 v2.4.6 $debug=NVS1.CRLF.7-5-0.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.10.0.schema.json

PackageIdentifier: ConnectWise.ScreenConnect
PackageVersion: 25.2.3.9216
PackageLocale: zh-CN
# Publisher:
# PublisherUrl:
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
# PackageName:
# PackageUrl:
License: 专有软件
# LicenseUrl:
# Copyright:
# CopyrightUrl:
ShortDescription: 远程支持与访问软件，助您更快解决IT问题
# Description:
# Moniker:
Tags:
- 远程
- 远程协助
- 远程支持
- 远程桌面
- 远程访问
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
Documentations:
- DocumentLabel: 文档
  DocumentUrl: https://docs.connectwise.com/ScreenConnect_Documentation
ManifestType: locale
ManifestVersion: 1.10.0
