# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.it
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win32/it/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 38B93FDF40B03B450251CD1C1E6B5924A8A30830BADADA9C4058F258CDD3491C
  ProductCode: Firefox Developer Edition 145.0 (x86 it)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64/it/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 585482A6AD35EC98DE2FAF5515FD687350C529F35EEA6ED2A785A1C0503B7EA5
  ProductCode: Firefox Developer Edition 145.0 (x64 it)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64-aarch64/it/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: BD79E5BFFB2F103142EA585CB988F682240C41DE5C80F711517C11B5F04476AE
  ProductCode: Firefox Developer Edition 145.0 (arm64 it)
ManifestType: installer
ManifestVersion: 1.10.0
