# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Amazon.KindlePreviewer
PackageVersion: 4.0.1
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
FileExtensions:
- epub
- htm
- html
- kpf
- mobi
- opf
- prc
- xhtml
ProductCode: Kindle Previewer 3
ReleaseDate: 2026-09-22
Installers:
- Architecture: x64
  InstallerUrl: https://d2bzeorukaqrvt.cloudfront.net/KPR4/KindlePreviewerSetup.exe
  InstallerSha256: 8DB9CDAF79DBF76BBAC286A0CF2A4B0262E80BA4B339BC6818E06F18A84475EC
ManifestType: installer
ManifestVersion: 1.12.0
