# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TheBrowserCompany.Arc
PackageVersion: 1.126.0.382
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.18362.0
InstallerType: msix
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCLibs.Desktop.14
  - PackageIdentifier: Microsoft.WindowsAppRuntime.1.5
PackageFamilyName: TheBrowserCompany.Arc_ttt1ap7aakyb4
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://releases.arc.net/windows/prod/1.126.0.382/Arc.x64.msix
  InstallerSha256: CB7D25E50D9EEB089556317B6D62BB3B850210603C7D26956328A05E83622EFE
  SignatureSha256: B572D62140B378A35D9E620473348D706871F4EA15D3DF727F97BB5CF398C18F
- Architecture: arm64
  InstallerUrl: https://releases.arc.net/windows/prod/1.126.0.382/Arc.arm64.msix
  InstallerSha256: 3F73AB8103D14D6140B3900F5E12B8397206171C064C8999F6AB41BDC31B4E7E
  SignatureSha256: 47753E41FE52799BB7B4CC5C52725B7DF6CB2E4B55A2C7CA0D557E2EB6FF3EDD
ManifestType: installer
ManifestVersion: 1.12.0
