# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: mikf.gallery-dl
PackageVersion: 1.32.16
PackageLocale: en-US
Publisher: Mike Fährmann
PublisherUrl: https://github.com/mikf
PublisherSupportUrl: https://github.com/mikf/gallery-dl/issues
Author: Mike Fährmann
PackageName: gallery-dl
PackageUrl: https://github.com/mikf/gallery-dl
License: GPL-2.0
LicenseUrl: https://github.com/mikf/gallery-dl/blob/master/LICENSE
Copyright: 2014-2026 Mike Fährmann
ShortDescription: Command-line program to download image galleries and collections from several image hosting sites
Description: gallery-dl is a command-line program to download image galleries and collections from several image hosting sites. It is a cross-platform tool with many configuration options and powerful filenaming capabilities.
Tags:
- download
- downloader
- gallery
- image
- photo
- picture
ReleaseNotes: |-
  Extractors
  - Additions
    - [toyhouse] add extractor for character galleries (cb#493)
    - [xenforo] support darkwanderer.net (gh#9805)
  - bellazon
    - warn on files hidden for guests (cb#489)
  - common
    - check for empty cookie values (cb#490)
  - deviantart
    - support numeric fav.me links (cb#495)
  - fapello
    - extract model_name & aliases metadata (pr#487)
  - imxtw
    - update domain to imx.bz (gh#9802)
  - instagram
    - fix user lookups by ID (cb#465 cb#466 cb#484 gh#9773 gh#9787)
    - fix avatar extractor (cb#466 cb#484 gh#9773)
    - fix highlights extractor (cb#484 gh#9786 gh#9793)
    - fix KeyError: 'width' (gh#9793)
    - update stories-tray extractor
    - improve doc_id extraction
  - kemono
    - fix thumbnail check (gh#9792)
  - myfigurecollection
    - fix items without filename
    - improve user pictures extraction
  - paheal
    - fix file_url & date extraction (gh#9791)
  - pawchive
    - fix deferred files marked as preview_only
    - handle deferred main post files
  - tapas
    - improve username & password login cookie handling (cb#497)
  - toyhouse
    - bypass Content Warning on image links
    - fix art extractor
  - xhamster
    - fix gallery extractor (pr#498)
ReleaseNotesUrl: https://codeberg.org/mikf/gallery-dl/releases/tag/v1.32.16
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/mikf/gallery-dl/wiki
ManifestType: defaultLocale
ManifestVersion: 1.12.0
