# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: gcnanmu.BowenMusic
PackageVersion: 0.1.0
InstallerType: nullsoft
Scope: user
ProductCode: BowenMusic
ReleaseDate: 2026-10-08
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\BowenMusic'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ldm0715/bowen_music/releases/download/v0.1.0/BowenMusic_0.1.0_x64_setup.exe
  InstallerSha256: 2586C1C8128CA869253747546FD6FD2DD606F1E3DB9E18E537F27A52EF94EC67
ManifestType: installer
ManifestVersion: 1.12.0
