# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.sq
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win32/sq/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 2FAFA099AEBB797224D3D4229A26B52C53F44C9FC764CD61C1A40D35E182714C
  ProductCode: Firefox Developer Edition 145.0 (x86 sq)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64/sq/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 7B675C74A3FCD7E575841A771F1A3D22EBAC32D07E82C56B0430BBB21EE4EE57
  ProductCode: Firefox Developer Edition 145.0 (x64 sq)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64-aarch64/sq/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 152D44E52BC51017CD9D5FD8D11F28DEAB94B65A0EEDA0437DA444AD0AB05518
  ProductCode: Firefox Developer Edition 145.0 (arm64 sq)
ManifestType: installer
ManifestVersion: 1.10.0
