# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Cyberbotics.Webots
PackageVersion: R2025a
PackageLocale: en-US
Publisher: Cyberbotics, Ltd.
PublisherUrl: https://cyberbotics.com/
PublisherSupportUrl: https://github.com/cyberbotics/webots/issues
Author: Cyberbotics, Ltd.
PackageName: Webots
PackageUrl: https://cyberbotics.com/
License: Apache-2.0
LicenseUrl: https://github.com/cyberbotics/webots/blob/HEAD/LICENSE
ShortDescription: Open-source robot simulator for modeling, programming, and simulating robots, vehicles, and mechanical systems.
Description: |-
  Webots provides a complete development environment to model, program, and simulate robots, vehicles, and mechanical systems. It is a beginner friendly software that is meant to introduce newcomers to the world of robotics.
  Webots offers a large collection of professionally developed robot models, sensors, actuators, and objects that can be shared through the community. It includes a physics engine, a set of cross-platform development tools with a graphical interface, and native support for programming robots in C, C++, Python, ROS, ROS 2, and other interfaces. Simulations run on Windows, Linux, and macOS, and scenes are described in VRML-based world files (.wbt) that can be edited in the built-in scene editor.
Tags:
- robot-simulator
- robotics
- ros
- simulation
ReleaseNotes: |-
  Some new robot model, new demos, improved ROS 2 support, and many other improvements.

  It is recommended to proceed with this update.

  See the official announcement and the complete change log for details.
ReleaseNotesUrl: https://github.com/cyberbotics/webots/releases/tag/R2025a
Documentations:
- DocumentLabel: User Guide
  DocumentUrl: https://cyberbotics.com/doc/reference/index
ManifestType: defaultLocale
ManifestVersion: 1.12.0
