# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Cyberbotics.Webots
PackageVersion: R2025a
PackageLocale: zh-CN
ShortDescription: 开源机器人仿真器，用于对机器人、车辆和机械系统进行建模、编程和仿真。
Description: |-
  Webots 提供了一套完整的开发环境，用于对机器人、车辆和机械系统进行建模、编程和仿真。它是一款对新手友好的软件，旨在引导初学者走进机器人学的世界。
  Webots 提供大量专业制作的机器人模型、传感器、执行器和可共享的物体资源。它内置物理引擎、一套带图形界面的跨平台开发工具，并原生支持使用 C、C++、Python、ROS、ROS 2 等接口为机器人编程。仿真可在 Windows、Linux 和 macOS 上运行，场景以基于 VRML 的世界文件（.wbt）描述，可在内置场景编辑器中编辑。
Tags:
- ros
- 仿真
- 机器人
- 机器人仿真
ManifestType: locale
ManifestVersion: 1.12.0
