# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Hitencent.JisuPDF
PackageVersion: 3.0.0.3039
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
FileExtensions:
- pdf
ProductCode: 极速PDF阅读器
ReleaseDate: 2025-03-31
Installers:
- Architecture: x86
  InstallerUrl: https://dl.jisupdf.com/jisupdf_setup_3.0.0.3039.exe
  InstallerSha256: 73AE2C3F7CC65FF9FF1A46784A1D7E10F504C6FC9468D1290AF36B916772C43B
ManifestType: installer
ManifestVersion: 1.9.0
