# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Anthropic.Claude
PackageVersion: 2.31226.1
Protocols:
- claude
ReleaseDate: 2026-10-09
Installers:
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://downloads.claude.ai/releases/win32/x64/2.31226.1/Claude-8576520051724193e9f74fc538f9ce8125e9ddd2.msix
  InstallerSha256: ECD354206B5F00C4A7B47E15F4779BE8E7385E7074E2CA4A8424A8ADAC75ABD3
  SignatureSha256: 88D2E326DF352CE177D9D1C567AC03B98D6188458C85A367897E6719452F509E
  PackageFamilyName: Claude_pzs8sxrjxfjjc
  Capabilities:
  - internetClient
  RestrictedCapabilities:
  - localSystemServices
  - packagedServices
  - runFullTrust
  - unvirtualizedResources
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://downloads.claude.ai/releases/win32/arm64/2.31226.1/Claude-8576520051724193e9f74fc538f9ce8125e9ddd2.msix
  InstallerSha256: B4476D80B725F1C18A7C2DD8E48A4E70B143C6EDEAD0B6E305C6ADCC802FDD52
  SignatureSha256: D1AB7EF73020A29476B5EEE306F550DD1BB63DEA66E19FB9CC36739D26EE7D1A
  PackageFamilyName: Claude_pzs8sxrjxfjjc
  Capabilities:
  - internetClient
  RestrictedCapabilities:
  - localSystemServices
  - packagedServices
  - runFullTrust
  - unvirtualizedResources
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.claude.ai/releases/win32/x64/2.31226.1/Claude-8576520051724193e9f74fc538f9ce8125e9ddd2.exe
  InstallerSha256: 27A103D944E1F165BDE6E38330EDA87F5C9FADC6D1BEC338B882739A0748569C
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
  ProductCode: AnthropicClaude
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.claude.ai/releases/win32/arm64/2.31226.1/Claude-8576520051724193e9f74fc538f9ce8125e9ddd2.exe
  InstallerSha256: A9AB41A595CA9705E90444C36B7B0E32E487BD541E0F112ED6D391EC04D996FF
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
  ProductCode: AnthropicClaude
ManifestType: installer
ManifestVersion: 1.12.0
