# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenJS.NodeJS
PackageVersion: 26.11.1
Commands:
- corepack
- node
- npm
- npx
FileExtensions:
- cjs
- js
- mjs
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v26.11.1/node-v26.11.1-x64.msi
  InstallerSha256: 5001C8E78D39593864339FB1A8C94C1AE19809BFFDE71E64B473D56F1F9726D3
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  UpgradeBehavior: install
  ProductCode: '{9F81CA7F-D80F-4772-B9FD-4EDF04C96438}'
  ElevationRequirement: elevatesSelf
- Architecture: arm64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v26.11.1/node-v26.11.1-arm64.msi
  InstallerSha256: 0C6B692D5C084F08DC44BA8F96EC21E45B120BEB493943E3976E089E293140ED
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  UpgradeBehavior: install
  ProductCode: '{72A67354-3EA5-4B6F-904C-C67BDD6D58C4}'
  ElevationRequirement: elevatesSelf
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: node-v26.11.1-win-x64/node.exe
    PortableCommandAlias: node
  InstallerUrl: https://nodejs.org/dist/v26.11.1/node-v26.11.1-win-x64.zip
  InstallerSha256: 97F36A8A9684FF0D3E35758B4610FEF5B628A5880E96F2CCC11240E5DAF9934E
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: node-v26.11.1-win-arm64/node.exe
    PortableCommandAlias: node
  InstallerUrl: https://nodejs.org/dist/v26.11.1/node-v26.11.1-win-arm64.zip
  InstallerSha256: 8DD03ADD3ED431EB436306F9ABE946434BCE928D2BF967B04117DC3755051208
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
