# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SuperDaniel-cn.BeanDesk
PackageVersion: 0.2.7
InstallerType: nullsoft
Scope: user
ProductCode: BeanDesk
ReleaseDate: 2026-10-10
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\BeanDesk'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SuperDaniel-cn/BeanDesk/releases/download/v0.2.7/BeanDesk_0.2.7_x64-setup.exe
  InstallerSha256: B0BE65FDF950AF4BDB08334E4C915C050D7A2D65A98924602293F79A564E260D
ManifestType: installer
ManifestVersion: 1.12.0
