# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KIR.Szafir
PackageVersion: 2.0.0.708
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: ApplicationFolder="<INSTALLPATH>"
FileExtensions:
- asice
- asics
- enc
- sig
- tst
- xades
ReleaseDate: 2026-06-10
AppsAndFeaturesEntries:
- UpgradeCode: '{2847D93B-0AE6-451A-875F-56CFF149B72B}'
Installers:
- Architecture: x86
  InstallerUrl: https://cdn.elektronicznypodpis.pl/Szafir/Szafir_2.0.0_b708_x86_jre11.msi
  InstallerSha256: 00757809FCB59A5B6A99932E6A383212023DA9ED3309356EF72D09DDA0EC6360
  ProductCode: '{99A4B10D-43F2-4D0E-85DC-89990C9C15ED}'
- Architecture: x64
  InstallerUrl: https://cdn.elektronicznypodpis.pl/Szafir/Szafir_2.0.0_b708_x64_jre11.msi
  InstallerSha256: 228F261927AAA885F5E12A679E21BD693DFDF26BFDEE626107C8F58C55DE6AD5
  ProductCode: '{3578F20E-B160-4BB6-9413-54B72B97834B}'
ManifestType: installer
ManifestVersion: 1.12.0
