# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Python.Python.3.15
PackageVersion: 3.15.0
FileExtensions:
- py
- pyc
- pyd
- pyo
- pyw
- pyz
- pyzw
ReleaseDate: 2026-10-09
Installers:
- Architecture: x86
  InstallerType: burn
  Scope: user
  InstallerUrl: https://www.python.org/ftp/python/3.15.0/python-3.15.0.exe
  InstallerSha256: 222F79DF7D2D5653871C09AEF73DD77623514A356CA7F4A4F3BA5B9217E55E8A
  InstallerSwitches:
    InstallLocation: DefaultJustForMeTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=0 PrependPath=1
  UpgradeBehavior: install
  Commands:
  - py
  - python
  - pythonw
  - pyw
  ProductCode: '{3aca6b4e-2d0d-489d-ab1f-d1327261e432}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.15.150.0
    UpgradeCode: '{B80393E9-4F6F-536A-B976-708C55818896}'
- Architecture: x86
  InstallerType: burn
  Scope: machine
  InstallerUrl: https://www.python.org/ftp/python/3.15.0/python-3.15.0.exe
  InstallerSha256: 222F79DF7D2D5653871C09AEF73DD77623514A356CA7F4A4F3BA5B9217E55E8A
  InstallerSwitches:
    InstallLocation: DefaultAllUsersTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=1 PrependPath=1
  UpgradeBehavior: install
  Commands:
  - py
  - python
  - pythonw
  - pyw
  ProductCode: '{3aca6b4e-2d0d-489d-ab1f-d1327261e432}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.15.150.0
    UpgradeCode: '{B80393E9-4F6F-536A-B976-708C55818896}'
  ElevationRequirement: elevatesSelf
- Architecture: x64
  InstallerType: burn
  Scope: user
  InstallerUrl: https://www.python.org/ftp/python/3.15.0/python-3.15.0-amd64.exe
  InstallerSha256: 67D9A63EB145A34AA939F02EADBF8C57F21FCDD6DECB901CCAC578D2D1F01D6F
  InstallerSwitches:
    InstallLocation: DefaultJustForMeTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=0 PrependPath=1
  UpgradeBehavior: install
  Commands:
  - py
  - python
  - pythonw
  - pyw
  ProductCode: '{c7d15cec-c713-485e-96e3-2c16dadd28a1}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.15.150.0
    UpgradeCode: '{6EA9D647-C064-5462-B172-7CD89592450E}'
- Architecture: x64
  InstallerType: burn
  Scope: machine
  InstallerUrl: https://www.python.org/ftp/python/3.15.0/python-3.15.0-amd64.exe
  InstallerSha256: 67D9A63EB145A34AA939F02EADBF8C57F21FCDD6DECB901CCAC578D2D1F01D6F
  InstallerSwitches:
    InstallLocation: DefaultAllUsersTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=1 PrependPath=1
  UpgradeBehavior: install
  Commands:
  - py
  - python
  - pythonw
  - pyw
  ProductCode: '{c7d15cec-c713-485e-96e3-2c16dadd28a1}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.15.150.0
    UpgradeCode: '{6EA9D647-C064-5462-B172-7CD89592450E}'
  ElevationRequirement: elevatesSelf
- Architecture: arm64
  InstallerType: burn
  Scope: user
  InstallerUrl: https://www.python.org/ftp/python/3.15.0/python-3.15.0-arm64.exe
  InstallerSha256: BB1C5123CC63D7BB37962EA7BF65E2B06389BE9E5D48B6B532346D42AE487C4F
  InstallerSwitches:
    InstallLocation: DefaultJustForMeTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=0 PrependPath=1
  UpgradeBehavior: install
  Commands:
  - py
  - python
  - pythonw
  - pyw
  ProductCode: '{74341593-9669-4ec3-ba91-3d1457aa86f8}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.15.150.0
    UpgradeCode: '{58B358DF-B562-5E2B-83FE-753EAC0D97A2}'
- Architecture: arm64
  InstallerType: burn
  Scope: machine
  InstallerUrl: https://www.python.org/ftp/python/3.15.0/python-3.15.0-arm64.exe
  InstallerSha256: BB1C5123CC63D7BB37962EA7BF65E2B06389BE9E5D48B6B532346D42AE487C4F
  InstallerSwitches:
    InstallLocation: DefaultAllUsersTargetDir=<INSTALLPATH>
    Custom: InstallAllUsers=1 PrependPath=1
  UpgradeBehavior: install
  Commands:
  - py
  - python
  - pythonw
  - pyw
  ProductCode: '{74341593-9669-4ec3-ba91-3d1457aa86f8}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 3.15.150.0
    UpgradeCode: '{58B358DF-B562-5E2B-83FE-753EAC0D97A2}'
  ElevationRequirement: elevatesSelf
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: python.exe
  - RelativeFilePath: pythonw.exe
  InstallerUrl: https://www.python.org/ftp/python/3.15.0/python-3.15.0-win32.zip
  InstallerSha256: C6414F4EF486EF7B6929C3430A439F5CF1CF71287AF676E1866CE6FB272C1474
  Commands:
  - python
  - pythonw
  ArchiveBinariesDependOnPath: true
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: python.exe
  - RelativeFilePath: pythonw.exe
  InstallerUrl: https://www.python.org/ftp/python/3.15.0/python-3.15.0-amd64.zip
  InstallerSha256: 6B1A3F885CE416CF3A68AF203E62203664EB5224D8D0C1D2A1945FDDEC5C500B
  Commands:
  - python
  - pythonw
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: python.exe
  - RelativeFilePath: pythonw.exe
  InstallerUrl: https://www.python.org/ftp/python/3.15.0/python-3.15.0-arm64.zip
  InstallerSha256: EA12D07E104CCD2AAB594E47B265975060EDCA385A3EEA8121CDD233E3F41203
  Commands:
  - python
  - pythonw
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
