# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.DriveAnalyzer
PackageVersion: 1.0.1.4
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente Drive Analyzer 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/driveanalyzerx86
  InstallerSha256: 9A9099116CE0F84EC104CD3239C6DC870F83F183B62D33BEC121FB8941377D3D
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/driveanalyzerx64
  InstallerSha256: EE5DFEFB510CB7B02A420BDD6C23F3854653FB195D3260BE32101F6E0CE6A272
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/driveanalyzerarm64
  InstallerSha256: BD32C7A5F619BE10F63A3EF8E93E98B91529676D49AD846366F5A2B3777450B3
ManifestType: installer
ManifestVersion: 1.12.0
