# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: OpenLogic.OpenJDK.25.JRE
PackageVersion: 25.0.4.7
PackageLocale: zh-CN
ShortDescription: OpenLogic 提供的免费、经过认证的 OpenJDK 25（JRE）构建版，含 HotSpot 虚拟机。
Description: |-
  OpenLogic 提供 OpenJDK 多个版本的免费认证构建版，覆盖多种操作系统与架构。这些构建版可由 OpenLogic 的商业支持服务提供保障，也可在没有任何支持承诺的情况下自由使用。
  本包在 Windows 上安装 OpenJDK 25 JRE（HotSpot 虚拟机）。安装程序会将该运行时注册到 Windows 的“程序和功能”中，把相关工具目录加入 PATH，并关联 .jar 文件以便直接运行。
ManifestType: locale
ManifestVersion: 1.12.0
