# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Paseo.Paseo
PackageVersion: 0.11.2
InstallerType: nullsoft
ProductCode: ca8eee31-e786-591a-8405-a3710823b93a
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/getpaseo/paseo/releases/download/v0.11.2/Paseo-Setup-0.11.2-x64.exe
  InstallerSha256: 9F70D95ECB70FDA4B6DED63E8D3CF7C2E213AE4E39A1D2C3CD1C37E370052C47
  InstallerSwitches:
    Custom: /currentuser
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Paseo'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/getpaseo/paseo/releases/download/v0.11.2/Paseo-Setup-0.11.2-x64.exe
  InstallerSha256: 9F70D95ECB70FDA4B6DED63E8D3CF7C2E213AE4E39A1D2C3CD1C37E370052C47
  InstallerSwitches:
    Custom: /allusers
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Paseo'
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/getpaseo/paseo/releases/download/v0.11.2/Paseo-Setup-0.11.2-arm64.exe
  InstallerSha256: DBCDECE2DF232A8A497E57FDECA83C315304C3DE4B85C33D453C14F81517BD3D
  InstallerSwitches:
    Custom: /currentuser
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Paseo'
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/getpaseo/paseo/releases/download/v0.11.2/Paseo-Setup-0.11.2-arm64.exe
  InstallerSha256: DBCDECE2DF232A8A497E57FDECA83C315304C3DE4B85C33D453C14F81517BD3D
  InstallerSwitches:
    Custom: /allusers
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\Paseo'
ManifestType: installer
ManifestVersion: 1.12.0
