# Created with YamlCreate.ps1 v2.5.0 $debug=NVS1.CRLF.7-5-2.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.10.0.schema.json

PackageIdentifier: GoldenSoftware.Grapher
PackageVersion: 25.2.292
PackageLocale: zh-CN
# Publisher:
# PublisherUrl:
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
# PackageName:
# PackageUrl:
License: 专有软件
# LicenseUrl:
# Copyright:
# CopyrightUrl:
ShortDescription: Grapher 可帮助工程师和科学家解读复杂的数据集，并将其转化为易于理解、适合发表的图表。
Description: |-
  Grapher 是一款易于使用的 2D 和 3D 技术绘图软件包，适用于科学家、工程师、商务专业人士或任何需要快速轻松生成出版级图表的用户。Grapher 是一款高效且功能强大的绘图程序，能够满足您各种复杂的绘图需求。您可以使用它为演示文稿、论文、市场营销、分析、销售等制作生动的图表和图形。
  使用 Grapher 创建图表非常简单，只需选择图表类型、选定数据文件，然后点击“打开”按钮即可。Grapher 会为每个新图表自动选择合理的默认设置，但所有图表设置均可进行修改。例如，您可以更改刻度线间隔、刻度标签、坐标轴标签、坐标轴长度、网格线、线条颜色、符号样式等。您还可以向图表中添加图例、图像、拟合曲线以及绘图对象。若要将相同的自定义设置应用于多个图表，您可以创建包含首选样式的 Grapher 模板。您还可以使用 Golden Software 的 Scripter 程序或任何支持 Active X 自动化的程序，实现数据处理和图表创建的自动化。图表完成后，您可以将其以多种格式导出，用于演示文稿和出版物中。
# Moniker:
Tags:
- 可视化
- 图形
- 图示
- 图表
- 绘图
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
Documentations:
- DocumentLabel: 快速入门指南
  DocumentUrl: https://downloads.goldensoftware.com/guides/GrapherQSG.pdf
ManifestType: locale
ManifestVersion: 1.10.0
