# Created with YamlCreate.ps1 v2.5.0 $debug=NVS1.CRLF.7-5-2.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: GoldenSoftware.Grapher
PackageVersion: 25.2.292
PackageLocale: en-US
Publisher: Golden Software
PublisherUrl: https://www.goldensoftware.com/
PublisherSupportUrl: https://support.goldensoftware.com/
PrivacyUrl: https://goldensoftware.com/privacy-policy/
Author: Golden Software, LLC
PackageName: Grapher
PackageUrl: https://www.goldensoftware.com/products/grapher/
# PackageUrl: https://www.goldensoftware.com/support/download-install/
License: Proprietary
LicenseUrl: https://www.goldensoftware.com/wp-content/uploads/2024/07/GoldenSoftwareLLC_EndUserLicenseAgreement.pdf
Copyright: Copyright © 1993-2025, Golden Software, LLC
CopyrightUrl: https://www.goldensoftware.com/wp-content/uploads/2024/07/GoldenSoftwareLLC_EndUserLicenseAgreement.pdf
ShortDescription: Grapher helps engineers and scientists interpret complex datasets and transform them into understandable, publication-ready graphs.
Description: |-
  Grapher is an easy-to-use 2D & 3D technical graphing package for scientists, engineers, business professionals, or anyone who needs to generate publication quality graphs quickly and easily. Grapher is an efficient and powerful graphing program for all of your most complex graphing needs. Create exciting graphs and plots for presentations, papers, marketing, analysis, sales, and more.
  With Grapher, creating a graph is as easy as choosing the graph type, selecting the data file, and clicking the Open button. Grapher automatically selects reasonable default settings for each new graph, though all of the graph settings can be modified. For example, you can change tick mark spacing, tick labels, axis labels, axis length, grid lines, line colors, symbol styles, and more. You can add legends, images, fit curves, and drawing objects to the graph. To apply the same custom settings to several graphs, you can create a Grapher template containing the preferred styles. Automate data processing and graph creation using Golden Software's Scripter program or any Active X automation program. Once the graph is complete, you can export it in a variety of formats for use in presentations and publications.
# Moniker:
Tags:
- diagram
- graph
- graphics
- plot
- visualization
ReleaseNotes: |-
  New Features and Improvements
  - Additional pages for documents use same layout as previous page
  - Improved properties and functionality of automatic and custom bins
  - Apply prefix and postfix font properties to multiple objects at once
  Fixes
  - Median calculation for first and third quartiles for box plots. Note this will affect how existing projects with box plots look when opening since the corrected calculation will be done when loading the document.
  - Worksheet references lost in text objects
  - Error bars retained when converting between plot types
  - Crash setting Defaults for line style with no document open
  - Creating ternary plots from worksheet view
  - Automation error when using files that can’t be found
  - Automation for grouped box plot minor labels
  - Crashes when starting up and shutting down
  - Crash using linked object name on multiple graphs
  - Legend sample text draw order
  - Undo and redo issues with wind chart
  - Clipping limits for polar bar charts when changing data
  - Automation with converting between 2D and 3D types
  - Linked axis setting when repositioned after duplicating
  - Between fill property updates
  - Crash setting wind chart bar width to 0
  - Rose chart property settings for auto and custom
  - Edit classes dialog up and down buttons on first launch
ReleaseNotesUrl: https://support.goldensoftware.com/hc/articles/228070288
PurchaseUrl: https://www.goldensoftware.com/products/pricing/
# InstallationNotes:
Documentations:
- DocumentLabel: Quick Start Guide
  DocumentUrl: https://downloads.goldensoftware.com/guides/GrapherQSG.pdf
ManifestType: defaultLocale
ManifestVersion: 1.10.0
