# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Herdr.Herdr
PackageVersion: 0.9.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: herdr.exe
  PortableCommandAlias: herdr
Commands:
- herdr
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-09-29
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/herdrdev/herdr/releases/download/v0.9.3/herdr-windows-x86_64.zip
  InstallerSha256: C75B1FA49F7A3BA4B8B11789912A6147E4214A3B6FD3556D0F80076C8887D795
ManifestType: installer
ManifestVersion: 1.12.0
