# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BtbN.FFmpeg.LGPL
PackageVersion: N-127032-g6ae491a26c-20260930
InstallerType: zip
NestedInstallerType: portable
Commands:
- ffmpeg
- ffplay
- ffprobe
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127032-g6ae491a26c-win64-lgpl\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127032-g6ae491a26c-win64-lgpl\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127032-g6ae491a26c-win64-lgpl\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-30-13-08/ffmpeg-N-127032-g6ae491a26c-win64-lgpl.zip
  InstallerSha256: C73AD424C5F9D94DD48815B4D3531E57130CB9F5C3DC8F21F4AA4E1FDB0658E3
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127032-g6ae491a26c-winarm64-lgpl\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127032-g6ae491a26c-winarm64-lgpl\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127032-g6ae491a26c-winarm64-lgpl\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-30-13-08/ffmpeg-N-127032-g6ae491a26c-winarm64-lgpl.zip
  InstallerSha256: CEC4353287A44B0B9DE49000961E6161A3393E8BF56CC9B18717D8906735B121
ManifestType: installer
ManifestVersion: 1.12.0
