# Created with YamlCreate.ps1 v2.4.6 $debug=NVS1.CRLF.7-5-1.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: RemoteUtilities.Host
PackageVersion: 7.6.2.0
PackageLocale: en-US
Publisher: Remote Utilities Pte. Ltd.
PublisherUrl: https://www.remoteutilities.com/
PublisherSupportUrl: https://www.remoteutilities.com/support/
PrivacyUrl: https://www.remoteutilities.com/about/privacy-policy.php
Author: Remote Utilities Pte. Ltd.
PackageName: Remote Utilities - Host
PackageUrl: https://www.remoteutilities.com/download/
License: Proprietary
LicenseUrl: https://www.remoteutilities.com/about/eula.php
Copyright: Copyright © 2009-2024 Remote Utilities Pte. Ltd. All rights reserved.
CopyrightUrl: https://www.remoteutilities.com/about/eula.php
ShortDescription: Install on the remote PC to allow remote access.
# Description:
# Moniker:
Tags:
- remote
- remote-access
- remote-control
- remote-desktop
ReleaseNotes: |-
  - Fixed flickering of tooltips near connections in the main Viewer window.
  - Fixed random display of the Host settings protection window during installation.
  - Minor fixes and improvements.
ReleaseNotesUrl: https://www.remoteutilities.com/product/release-notes.php
PurchaseUrl: https://www.remoteutilities.com/buy/
# InstallationNotes:
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://www.remoteutilities.com/support/docs/
- DocumentLabel: Knowledge Base
  DocumentUrl: https://www.remoteutilities.com/support/kb/
ManifestType: defaultLocale
ManifestVersion: 1.10.0
