# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Liaoyuanxinghuo.DSHManager
PackageVersion: 0.3.14
PackageLocale: zh-CN
Publisher: dshpm
PublisherUrl: https://github.com/Liaoyuanxinghuo
PublisherSupportUrl: https://github.com/Liaoyuanxinghuo/DSH-Plugin-Manager/issues
Author: Liaoyuanxinghuo
PackageName: DSH Manager
PackageUrl: https://github.com/Liaoyuanxinghuo/DSH-Plugin-Manager
License: CC-BY-NC-SA-4.0
LicenseUrl: https://github.com/Liaoyuanxinghuo/DSH-Plugin-Manager/blob/HEAD/LICENSE
ShortDescription: 面向 DSH (DeepSeek Harness) 的桌面图形管理工具
Description: 面向 DSH 的桌面管理工具。在图形界面中完成 DSH 多版本下载管理、Profile 管理（整合包管理）、插件安装与管理、整合包（.dspack）导出 / 导入 / 市场、多实例独立启动，无需手敲命令行。无需本地拥有任何环境，也无需手动安装 DSH，开箱即用。
Tags:
- deepseek
- deepseek-harness
- dsh
ReleaseNotes: V0.3.14:修复插件使用相关逻辑
ReleaseNotesUrl: https://github.com/Liaoyuanxinghuo/DSH-Plugin-Manager/releases/tag/V0.3.14
ManifestType: defaultLocale
ManifestVersion: 1.12.0
