# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Liaoyuanxinghuo.DSHManager
PackageVersion: 0.3.14
InstallerType: nullsoft
Scope: user
ProductCode: DSH Manager
ReleaseDate: 2026-10-04
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\DSH Manager'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Liaoyuanxinghuo/DSH-Plugin-Manager/releases/download/V0.3.14/DSH.Manager_0.3.14_x64-setup.exe
  InstallerSha256: 0797F2588CD52D99A2B054FF380A9DE2A00F9B2F6BEBC5F618CB8465FD1F24D4
ManifestType: installer
ManifestVersion: 1.12.0
