# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: CHERRY.UTILITY
PackageVersion: "3.12"
PackageLocale: en-US
Publisher: Cherry SE
PublisherUrl: https://www.cherry.de/en-us/company/about-cherry
PublisherSupportUrl: https://www.cherry.de/en-us/contact
PrivacyUrl: https://www.cherry.de/en-us/data-privacy
Author: Cherry SE
PackageName: CHERRY Utility Software
PackageUrl: https://www.cherry.de/en-us/products/software-services/cherry-utility
License: Freeware (Terms & Conditions)
LicenseUrl: https://www.cherry.de/en-us/terms-conditions
Copyright: Copyright 2026 Cherry SE
CopyrightUrl: https://www.cherry.de/en-us/usage-notices
ShortDescription: The solution for high-end input devices.
Description: |-
  The CHERRY UTILITY software is the solution for professionals, enthusiasts and gamers with a compatible CHERRY product*. Lighting control, macro programming and numerous detailed settings allow you to customize your hardware.
  Individual assignment of all keys: Program your CHERRY keyboard/mouse* to suit your taste: shortcuts, text modules, macros, open files/folders/programs/websites, multimedia.
  Fine-tuned lighting control: Choose from countless colors and lighting effects and create your own lighting concept.
  ProScroll Technology: With roughly 288 million possible combinations, ProScroll offers an unprecedented level of customization for a scroll wheel. Combine seven adjustable parameters to create a scrolling experience tailored precisely to your needs.
  Works with dedicated CHERRY keyboards and mice: You can use CHERRY UTILITY to directly reprogram your CHERRY keyboard or mouse*. The personalized settings are stored directly in the input device. This means that no software needs to be running actively in the background.
Tags:
- keyboard
- lighting
- macro
- mouse
- rgb
ReleaseNotes: |-
  CHANGES IN V3.12 FROM 2026/09/23:
  New Features:
  Device Support:
  - Added support for Pixiu 99 (ANSI layout)
    - System shortcut keylock
    - Configuration of key sounds
    - Audio Sync feature for light effects
    - 3 different HW Profiles
    - Disable single keys via key actions
  - Added support for MX Board 3.0s Pro NBL (ANSI layout)
  - Added support for MX Board 3.0s Pro RGB (ANSI layout)
  - Added support for MX Board 3.0s Pro RGB Wireless (ANSI layout)
    - Additional Light effects
    - Switch between Win/Mac mode via SW
    - 2 different layers (default and FN) of key actions for each WIN and MAC Mode
    - Snappy Tap
    - 3 different HW Profiles
    - Disable single keys via key actions
    - FW Update
  - Added support for Cherry Xtrfy LumiPad - Pokémon Edition
  Software Update:
  - Added a hint on how to switch between HW profiles via the keyboard
  - Improved stability of device communication
  Firmware Update:
  - Added latest MX 3.0S Pro firmware versions
  Bug Fixes:
  - Pixiu 98: Macro actions were not saved on the first attempt
ReleaseNotesUrl: https://www.cherry.de/fileadmin/media/Corporate/Documents/EN/20260923_Cherry_Utility_Software_x32-3.12-ReleaseNotes.pdf
ManifestType: defaultLocale
ManifestVersion: 1.12.0
