# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: CHERRY.UTILITY
PackageVersion: "3.12"
PackageLocale: zh-CN
PublisherUrl: https://www.cherry.cn/
PublisherSupportUrl: https://www.cherry.cn/contact.html
PackageUrl: https://www.cherry.cn/cherryutility.html
License: 免费软件
ShortDescription: 兼容各种 CHERRY 产品的高端输入设备解决方案
Description: |-
  CHERRY Utility 实用软件是一个兼容各种 CHERRY 产品的高端输入设备解决方案，适用与对于产品不太了解的新手或专业人士，具有灯光控制，宏编程和许多详细设置功能，允许您自定义您的硬件。
  按键功能单独分配：可以根据您的需求，对您的 CHERRY 键盘/鼠标按键进行编程，分配不一样的功能，例如：文本模块，宏命令，打开文件程序/网站，多媒体等。
  丰富的灯光设置：可以随意设置每个键盘按键的灯光颜色，打造属于你独一无二的键盘灯效。
  打造你的专属 CHERRY 键鼠：您可将所有个性化设置直接存储在你的 CHERRY 键盘或鼠标中，更换电脑设备也能继续使用，而不必每次打开软件进行设置。
ManifestType: locale
ManifestVersion: 1.12.0
