# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CHERRY.UTILITY
PackageVersion: "3.12"
InstallerType: inno
Scope: machine
ProductCode: '{BAB5DAF3-92D2-4A22-ABD0-E55EAE2C6CE6}_is1'
ReleaseDate: 2026-09-23
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\CHERRY Utility Software'
Installers:
- Architecture: x86
  InstallerUrl: https://www.cherry.de/fileadmin/media/Corporate/Software/CHERRY_Utility_Software_x32-3.12.exe
  InstallerSha256: 2FA52325747EE96B560F8BA8C304FEDC10D4AB75389258BFD8001168AF4BB238
ManifestType: installer
ManifestVersion: 1.12.0
