# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.DriveAnalyzer
PackageVersion: 1.0.1.2
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente Drive Analyzer 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/driveanalyzerx86
  InstallerSha256: E6A80B2CDB668B5BBBDA9AD567AB6A5BE31068FB39FF85F3343D6ACF0E4B17B9
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/driveanalyzerx64
  InstallerSha256: D44EF40AD2B68AD9AE8C307090D6F46EDF5F45C1BC122198E5F8C7066BF35DA0
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/driveanalyzerarm64
  InstallerSha256: FEC2239687788A9E2165D2B1BED809846C934207A85A0F323984E89CB815F59D
ManifestType: installer
ManifestVersion: 1.12.0
