# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BtbN.FFmpeg.GPL.9.0
PackageVersion: 9.0.2-20260930
InstallerType: zip
NestedInstallerType: portable
Commands:
- ffmpeg
- ffplay
- ffprobe
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-n9.0.2-17-g2a571b6068-win64-gpl-9.0\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-n9.0.2-17-g2a571b6068-win64-gpl-9.0\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-n9.0.2-17-g2a571b6068-win64-gpl-9.0\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-30-13-08/ffmpeg-n9.0.2-17-g2a571b6068-win64-gpl-9.0.zip
  InstallerSha256: A0E45723C72141975F51D8666302E614711745F3102B704CA3F82C897A58D278
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-n9.0.2-17-g2a571b6068-winarm64-gpl-9.0\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-n9.0.2-17-g2a571b6068-winarm64-gpl-9.0\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-n9.0.2-17-g2a571b6068-winarm64-gpl-9.0\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-30-13-08/ffmpeg-n9.0.2-17-g2a571b6068-winarm64-gpl-9.0.zip
  InstallerSha256: 6DCD0626F9F6D6C7323565E57410E9F37ED14A85946EC9EA9CAFF294CA32F5C0
ManifestType: installer
ManifestVersion: 1.12.0
