# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: try2love.CodexMobileBridge
PackageVersion: 1.3.0
InstallerType: nullsoft
ProductCode: 36883bea-4af2-555e-ace9-54ede116018b
ReleaseDate: 2026-10-03
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\Codex Mobile Bridge'
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/try2love/codex-mobile-bridge/releases/download/v1.3.0/Codex-Mobile-Bridge-1.3.0-Windows-x64-Setup.exe
  InstallerSha256: 5DEBDE2422C04C2EFC8DA6643DF0F67265652792DD5CC6A6D1A922F2B1408BA6
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/try2love/codex-mobile-bridge/releases/download/v1.3.0/Codex-Mobile-Bridge-1.3.0-Windows-x64-Setup.exe
  InstallerSha256: 5DEBDE2422C04C2EFC8DA6643DF0F67265652792DD5CC6A6D1A922F2B1408BA6
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
