# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EvercraftLabs.Maestri
PackageVersion: 0.20.2
InstallerType: nullsoft # electron-builder
FileExtensions:
- maestri
- maestripartitura
- maestripartituras
ProductCode: 52dc607b-902a-5d3f-9b71-7727ed012ff4
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.maestri.dev/win/x64/Maestri-Setup-0.20.2-x64.exe
  InstallerSha256: 9FC305D2465F5AC65B14D10A47B42F953232214AEDC6C591938119EB4477B5D3
  InstallerSwitches:
    Custom: /currentuser
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Maestri'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.maestri.dev/win/x64/Maestri-Setup-0.20.2-x64.exe
  InstallerSha256: 9FC305D2465F5AC65B14D10A47B42F953232214AEDC6C591938119EB4477B5D3
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Maestri'
ManifestType: installer
ManifestVersion: 1.12.0
