# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BtbN.FFmpeg.GPL.Shared
PackageVersion: N-127021-ge0c94b2d1c-20260930
InstallerType: zip
NestedInstallerType: portable
Commands:
- ffmpeg
- ffplay
- ffprobe
ReleaseDate: 2026-09-30
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-win64-gpl-shared\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-win64-gpl-shared\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-win64-gpl-shared\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-30-13-08/ffmpeg-N-127021-ge0c94b2d1c-win64-gpl-shared.zip
  InstallerSha256: 15CB5093F88593216751FF61C671A48DB04677715DDA1FD46F0BD4C4EA1AF692
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-winarm64-gpl-shared\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-winarm64-gpl-shared\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-winarm64-gpl-shared\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-30-13-08/ffmpeg-N-127021-ge0c94b2d1c-winarm64-gpl-shared.zip
  InstallerSha256: 3CEA4638B2CDBDE052A9975B1206AE8E89D7CED63559556CEB6849B9964CC1C4
ManifestType: installer
ManifestVersion: 1.12.0
