# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SchneeHertz.PiDeepSeekPet
PackageVersion: 0.5.0
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
ProductCode: ebb29a08-9239-5d73-9f05-b1cbb03107d0
ReleaseDate: 2026-09-24
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/SchneeHertz/pi-deepseek-pet/releases/download/v0.5.0/Pi-DeepSeek-Pet-0.5.0-Setup.exe
  InstallerSha256: F24B5DFAA40973247216390D42BC99725437776A718A7B759B035147BD94146A
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/SchneeHertz/pi-deepseek-pet/releases/download/v0.5.0/Pi-DeepSeek-Pet-0.5.0-Setup.exe
  InstallerSha256: F24B5DFAA40973247216390D42BC99725437776A718A7B759B035147BD94146A
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
