# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MINECO.AFORIX
PackageVersion: "10.5"
InstallerType: inno
Scope: user
UpgradeBehavior: install
FileExtensions:
- aforixd
- aforixm
- aforixn
- aforixp
- afxd
- afxm
- afxp
ProductCode: '{FBD0B5E1-C144-4A57-A674-26A47718B360}_is1'
ReleaseDate: 2026-05-26
InstallationMetadata:
  DefaultInstallLocation: '%AppData%\AFORIX'
Installers:
- Architecture: x86
  InstallerUrl: https://oficinavirtual.comercio.gob.es/AFORIXUpdater/InstaladorAforix.exe
  InstallerSha256: F801F0473522BFC883A647D62156367E1636A20D518B7D5028E083EB9A25E613
ManifestType: installer
ManifestVersion: 1.12.0
