# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Mineco.AFORIX
PackageVersion: "10.5"
PackageLocale: es-ES
Publisher: Ministerio de Economía, Comercio y Empresa
PublisherUrl: https://www.mineco.gob.es/
PublisherSupportUrl: https://oficinavirtual.comercio.gob.es/AFORIXUpdater/contacto.aspx
PackageName: AFORIX
PackageUrl: https://oficinavirtual.comercio.gob.es/AFORIXUpdater/
License: Privativo
ShortDescription: Programa de ayuda para la cumplimentación de los formularios de declaración de inversiones exteriores.
Description: |-
  AFORIX es el programa de ayuda para la cumplimentación de los formularios de declaración de inversiones exteriores (D-1A, D-1B, D-2A, D-2B, D-4, D-5A, D-5B, D-7A, D-7B, D-8, DP-1, DP-2, DP-3 y DP-4) por medios informáticos.
  La aplicación permite el guardado y recuperación de los datos de las declaraciones, así como confeccionar plantillas con aquellos datos que se repitan en varias declaraciones. Con AFORIX podrá corregir fácilmente los errores detectados, ya que el programa realiza validaciones básicas para una correcta cumplimentación, previa a la presentación telemática o impresión de las declaraciones.
Tags:
- declaraciones
- españa
- formularios
- inversiones-exteriores
ReleaseNotesUrl: https://oficinavirtual.comercio.gob.es/AFORIXUpdater/
Documentations:
- DocumentLabel: FAQ
  DocumentUrl: https://oficinavirtual.comercio.gob.es/AFORIXUpdater/faq.aspx
ManifestType: defaultLocale
ManifestVersion: 1.12.0
