# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: MINECO.AFORIX
PackageVersion: "10.5"
PackageLocale: zh-CN
License: 专有软件
ShortDescription: 用于填写西班牙对外投资申报表的辅助程序。
Description: |-
  AFORIX 是西班牙商业国务秘书处推出的辅助程序，用于在电脑上填写对外投资申报表（D-1A、D-1B、D-2A、D-2B、D-4、D-5A、D-5B、D-7A、D-7B、D-8、DP-1、DP-2、DP-3 和 DP-4）。

  该应用可保存和恢复申报数据，并可根据多份申报中重复的数据创建模板。它执行基本验证，便于在以电子方式提交或打印申报表之前纠正错误。
Tags:
- 对外投资
- 申报
- 表单
- 西班牙
ManifestType: locale
ManifestVersion: 1.12.0
