# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Havysoft.MassTube
PackageVersion: 22.1.7.226
PackageLocale: en-US
Publisher: Havy Alegria
PublisherUrl: https://www.havysoft.cl/
PublisherSupportUrl: https://www.havysoft.cl/contacto.html
Author: Havy Alegria
PackageName: MassTube
PackageUrl: https://www.havysoft.cl/masstube.html
License: Freeware
LicenseUrl: https://www.havysoft.cl/acuerdo.html
Copyright: Copyright © 2026 Havy Alegria. All Rights Reserved.
ShortDescription: Video and music downloader for YouTube with support for 4K, 8K, and multiple audio formats.
Description: |-
  MassTube is a powerful video and music downloader app for YouTube. Get your favorite content in 4K, Full HD, MP3, OGG, FLAC, AAC (M4A), Vevo, 8K and more easily and quickly, so you can play them anywhere as a single media file, in offline mode and without ads.

  Key features
  - Simple and easy-to-use user interface.
  - Get downloadable video formats from URLs by simply dragging and dropping the links from the web browser into the app window.
  - Supported native video formats: MP4 (AV1, H264 codecs) and MKV (VP9 codec).
  - Supported native video resolutions: 8K 4320p, 4K 2160p, FHD 1080p, and HD 720p.
Tags:
- downloader
- video
- video-downloader
- youtube
ManifestType: defaultLocale
ManifestVersion: 1.12.0
