# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Havysoft.MassTube
PackageVersion: 22.1.7.226
PackageLocale: zh-CN
License: 免费软件
ShortDescription: YouTube 视频与音乐下载器，支持 4K、8K 和多种音频格式。
Description: |-
  MassTube 是一款功能强大的 YouTube 视频与音乐下载应用。轻松快速地获取 4K、全高清、MP3、OGG、FLAC、AAC（M4A）、Vevo、8K 等格式的内容，随时随地以单个媒体文件离线播放，无广告。

  主要功能
  - 简单易用的用户界面。
  - 只需将网页浏览器中的链接拖放到应用窗口，即可获取可下载的视频格式。
  - 支持的原生视频格式：MP4（AV1、H264 编码）和 MKV（VP9 编码）。
  - 支持的原生视频分辨率：8K 4320p、4K 2160p、FHD 1080p 和 HD 720p。
Tags:
- youtube
- 下载器
- 视频
- 视频下载
ManifestType: locale
ManifestVersion: 1.12.0
