# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: dl1bz.deskHPSDR
PackageVersion: 2.8.7c
PackageLocale: en-US
Publisher: Heiko Amft, DL1BZ
PublisherUrl: https://github.com/dl1bz
PublisherSupportUrl: https://github.com/dl1bz/deskhpsdr/issues
Author: Heiko Amft, DL1BZ
PackageName: deskHPSDR
PackageUrl: https://github.com/dl1bz/deskhpsdr
License: GPL-3.0-only
LicenseUrl: https://github.com/dl1bz/deskhpsdr/blob/HEAD/LICENSE
ShortDescription: SDR transceiver application for OpenHPSDR protocol 1 and 2 amateur radio transceivers.
Description: deskHPSDR by DL1BZ is an mature Open Source desktop application for Hamradio OpenHPSDR SDR transceivers that has been under active development for years. SDR devices based on the OpenHPSDR protocol P1 or P2 are fully supported and both protocol versions are fully supported. It is designed and built as an advanced SDR transceiver front-end application for macOS, Linux and WINDOWS for "every-day-use" and runs now extremely stable and reliable. deskHPSDR is largely based on the WDSP software library by Warren C. Pratt (NR0V), similar to other SDR applications like Thetis for WINDOWS.
Tags:
- ham-radio
- sdr
- transceiver
ReleaseNotes: |-
  deskHPSDR 2.8.7
  Changes:
  - new release after the most extensive code audit I ever long prepared and made
  - extend the audit to the WDSP-2.10 library with code corrections
  WINDOWS 2.8.7a:
  - full audit of the WDSP-2.10 library with code corrections
  - found and fix a crash behaviour of deskHPSDR if using ZOOM > 13 at panadapter, which I was investigating since a few days
  WINDOWS 2.8.7b:
  - fix GTK menu dialog lifecycle and callback handling
  WINDOWS 2.8.7c:
  - fix theme switching without recreating Screen menu
  - change compiler from gcc to clang
  The x86_64 Intel version is build against Xcode 26.3 and corresonding clang under macOS 15 "Sequoia".
  The ARM version is build with the lastest Xcode 27.0 version / clang currently under macOS 26 "Tahoe".
  The Windows version (64bit native) is build against MSYS2 UCRT64 under Windows 11 Pro.
  73 Heiko, DL1BZ
  Maintainer deskHPSDR project
  Note: deskHPSDR get seamless updates. The used version numbering (e.g. 2.7.40) is only a requirement for the release option at Github. But the crucial factor is the commit state, which is part of the download filename. Compare it, from time to time I replace the downloads with newer deskHPSDR versions, but without changing the actual version number. Support always required the use of the latest deskHPSDR version.
  Note 2: I never create or publish deskHPSDR binaries or appimages for Linux.
ReleaseNotesUrl: https://github.com/dl1bz/deskhpsdr/releases/tag/2.8.7
ManifestType: defaultLocale
ManifestVersion: 1.12.0
