# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: dl1bz.deskHPSDR
PackageVersion: 2.8.7c
PackageLocale: zh-CN
ShortDescription: 面向 OpenHPSDR 协议 1 和 2 业余无线电收发器的 SDR 应用程序。
Description: deskHPSDR 由 DL1BZ 开发，是一款成熟的开源桌面应用程序，专用于业余无线电 OpenHPSDR SDR 收发信机，多年来一直处于积极开发中。它全面支持基于 OpenHPSDR P1 或 P2 协议的 SDR 设备，对这两种协议版本均提供完整支持。该程序专为 macOS、Linux 和 WINDOWS 设计构建，是一款面向“日常使用”的高级 SDR 收发信机前端应用程序，目前运行极其稳定可靠。与 WINDOWS 上的 Thetis 等其他 SDR 应用程序类似，deskHPSDR 很大程度上基于 Warren C. Pratt (NR0V) 的 WDSP 软件库。
Tags:
- sdr
- 业余无线电
ManifestType: locale
ManifestVersion: 1.12.0
