# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: dl1bz.deskHPSDR
PackageVersion: 2.8.7c
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: '{FE9E4D98-38CA-4C61-A336-1B3E820BEA8A}_is1'
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dl1bz/deskhpsdr/releases/download/2.8.7/Setup-deskHPSDR-2.8.7c-win64.exe
  InstallerSha256: 6A304FB06BC4E0C3F44B6825940FF88F35D0B6E633BA9064FA24776455ED5CCB
ManifestType: installer
ManifestVersion: 1.12.0
