# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Anthropic.Claude
PackageVersion: 2.26454.2
Protocols:
- claude
ReleaseDate: 2026-10-07
Installers:
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://downloads.claude.ai/releases/win32/x64/2.26454.2/Claude-75afdd18501b9670ae33bfb7c0cd88567ce76994.msix
  InstallerSha256: 563E8E1D7CD340E65F89C6B336C2ED0F52CCBA07E60301DBD1C664F4ED3A6937
  SignatureSha256: 26F6371BC319CB296BC845C0D06266EBA0C84B2863B5F03205D4CA58ADC1F845
  PackageFamilyName: Claude_pzs8sxrjxfjjc
  Capabilities:
  - internetClient
  RestrictedCapabilities:
  - localSystemServices
  - packagedServices
  - runFullTrust
  - unvirtualizedResources
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://downloads.claude.ai/releases/win32/arm64/2.26454.2/Claude-75afdd18501b9670ae33bfb7c0cd88567ce76994.msix
  InstallerSha256: 85EEFADED377505AF78DB73EEDF53D6826FEA3BBC022F1FB851BC298369A05C0
  SignatureSha256: 0B2B197A91409E45F4D92E4888F65B5A524386AAC3AB0B3C0A20E00D45051843
  PackageFamilyName: Claude_pzs8sxrjxfjjc
  Capabilities:
  - internetClient
  RestrictedCapabilities:
  - localSystemServices
  - packagedServices
  - runFullTrust
  - unvirtualizedResources
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.claude.ai/releases/win32/x64/2.26454.2/Claude-75afdd18501b9670ae33bfb7c0cd88567ce76994.exe
  InstallerSha256: A3DAC17A6A47A2261AD42A9DBBDB650141D46718C068BF33D362E5C9B17EE8A3
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
  ProductCode: AnthropicClaude
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.claude.ai/releases/win32/arm64/2.26454.2/Claude-75afdd18501b9670ae33bfb7c0cd88567ce76994.exe
  InstallerSha256: F91F5B15E1A4656ED8458EF33639B2A60A48F45FD3A388CEBA485EF0C29C4FAF
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
  ProductCode: AnthropicClaude
ManifestType: installer
ManifestVersion: 1.12.0
