# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.sv-SE
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win32/sv-SE/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 0D6693E35488821592A4F0A42E47F87C08E0DC7168E64B176EB1AB5C46F61797
  ProductCode: Firefox Developer Edition 145.0 (x86 sv-SE)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64/sv-SE/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 010290F422348DCE530885CC9FDAD4F80132943A2AF7BD05AB6191FC38204351
  ProductCode: Firefox Developer Edition 145.0 (x64 sv-SE)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64-aarch64/sv-SE/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 694554C0C7A798B1E5FCC2DBA3A1E8A26F50EB4FC52F2BADF6CA67C6B8334CDB
  ProductCode: Firefox Developer Edition 145.0 (arm64 sv-SE)
ManifestType: installer
ManifestVersion: 1.10.0
