# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenLogic.OpenJDK.21.JDK
PackageVersion: 21.0.12.8
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Custom: ADDLOCAL=ALL
UpgradeBehavior: install
Commands:
- jar
- jarsigner
- java
- javac
- javadoc
- javap
- javaw
- jconsole
- jdeprscan
- jdeps
- jlink
- jmod
- jps
- jshell
- jstat
- keytool
FileExtensions:
- class
- jar
- java
- jsp
ProductCode: '{21FBAC45-371C-4A47-B40D-E7013F41C4CD}'
ReleaseDate: 2026-08-06
AppsAndFeaturesEntries:
- DisplayName: OpenLogic-OpenJDK JDK with Hotspot 21.0.12+8 (x64)
  UpgradeCode: '{B66D9143-5173-42CA-B35C-FD904DFD39F0}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\OpenLogic\jdk-21.0.12.8-hotspot'
Installers:
- Architecture: x64
  InstallerUrl: https://builds.openlogic.com/downloadJDK/openlogic-openjdk/21.0.12+8/openlogic-openjdk-21.0.12+8-windows-x64.msi
  InstallerSha256: B5C174CA14856773EDD0C171F9D9E4471EC7B4FB50B3FC6F64680C417F27F86B
ManifestType: installer
ManifestVersion: 1.12.0
