# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BtbN.FFmpeg.GPL.Shared.9.0
PackageVersion: 9.0.2-20260930
InstallerType: zip
NestedInstallerType: portable
Commands:
- ffmpeg
- ffplay
- ffprobe
ReleaseDate: 2026-09-30
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-n9.0.2-17-g2a571b6068-win64-gpl-shared-9.0\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-n9.0.2-17-g2a571b6068-win64-gpl-shared-9.0\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-n9.0.2-17-g2a571b6068-win64-gpl-shared-9.0\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-30-13-08/ffmpeg-n9.0.2-17-g2a571b6068-win64-gpl-shared-9.0.zip
  InstallerSha256: 3DA6C7B60BB9CCD73EC5B5E815BA804A0879EB362BA0E3BEEBCE50174C022696
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-n9.0.2-17-g2a571b6068-winarm64-gpl-shared-9.0\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-n9.0.2-17-g2a571b6068-winarm64-gpl-shared-9.0\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-n9.0.2-17-g2a571b6068-winarm64-gpl-shared-9.0\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-30-13-08/ffmpeg-n9.0.2-17-g2a571b6068-winarm64-gpl-shared-9.0.zip
  InstallerSha256: 92460CF103340012D41413B557669902538F040E0C953ABC1D719750DCD5F8A8
ManifestType: installer
ManifestVersion: 1.12.0
