# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Alibaba.QoderCLI.CN
PackageVersion: 1.1.68
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: qoderclicn.exe
  PortableCommandAlias: qodercn
Commands:
- qodercn
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://static.qoder.com.cn/qoder-cli-cn/releases/1.1.68/qoderclicn-windows-x64.zip
  InstallerSha256: 80D92E434090E21DCC24CFE28D4D5D717AF34FE3E97A3A09A8A7DA2180F0FFD1
- Architecture: arm64
  InstallerUrl: https://static.qoder.com.cn/qoder-cli-cn/releases/1.1.68/qoderclicn-windows-arm64.zip
  InstallerSha256: 1CBC82322B2BBB8E3C17FE3E97B478F52856DB69EA0937E9D240B752CD910696
ManifestType: installer
ManifestVersion: 1.12.0
