# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: llxisdsh.ConstAPI
PackageVersion: 0.1.58
InstallerType: nullsoft
Scope: user
ProductCode: CONST API
ReleaseDate: 2026-09-30
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\CONST API'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/llxisdsh/const-api-public/releases/download/client-v0.1.58/const-api_0.1.58_windows-x86_64-setup.exe
  InstallerSha256: 61D9F37CC3115E53402FAAB4C80B27AC2E14ACA4A274D2518639B32886DB5D85
ManifestType: installer
ManifestVersion: 1.12.0
