# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Havysoft.MemEmotics
PackageVersion: 3.3.0.171
PackageLocale: es-CL
License: Gratuito
ShortDescription: Divertido juego de Memorice inspirado en los famosos emojis, con 3 desafiantes niveles de dificultad.
Description: 'MemEmotics es un divertido juego de Memorice inspirado en los famosos emojis de los chats y redes sociales, con 3 desafiantes niveles de dificultad. Consiste en encontrar las parejas de los 20 emojis que están repartidos como naipes en diferentes posiciones en la mesa virtual: en total 40 naipes ocultos y ordenados en forma aleatoria, y quien consiga encontrar todos los emojis en el menor tiempo posible y con la menor cantidad de fallos es el ganador. Disfruta escuchando una increíble banda sonora mientras juegas.'
Tags:
- emoji
- juego
- memorice
ManifestType: locale
ManifestVersion: 1.12.0
