# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Havysoft.MemEmotics
PackageVersion: 3.3.0.171
PackageLocale: en-US
Publisher: Havy Alegria
PublisherUrl: https://www.havysoft.cl/
PublisherSupportUrl: https://www.havysoft.cl/contacto.html
Author: Havy Alegria
PackageName: MemEmotics
PackageUrl: https://www.havysoft.cl/mememotics.html
License: Freeware
LicenseUrl: https://www.havysoft.cl/acuerdo.html
Copyright: Copyright © 2026 Havy Alegria. All Rights Reserved.
ShortDescription: Memory puzzle game inspired by chat emojis, with three difficulty levels.
Description: 'MemEmotics is a fun memory game inspired by the famous emojis of chats and social networks, with three challenging difficulty levels. Find the pairs of the 20 emojis spread out like playing cards in different positions on the virtual table: 40 hidden cards randomly ordered, and whoever finds all the emojis in the shortest time and with the fewest misses wins. Enjoy an amazing soundtrack while you play.'
Tags:
- emoji
- game
- memory-game
ManifestType: defaultLocale
ManifestVersion: 1.12.0
