# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Havysoft.MemEmotics
PackageVersion: 3.3.0.171
PackageLocale: zh-CN
License: 免费软件
ShortDescription: 以聊天表情符号为主题的记忆拼图游戏，含三个难度级别。
Description: MemEmotics 是一款以聊天和社交网络中著名 emoji 表情为主题趣味记忆游戏，包含三个具有挑战性的难度级别。找出散布在虚拟桌面上不同位置的 20 个 emoji 的配对：40 张隐藏卡牌随机排列，用最短的时间和最少的失误找出全部 emoji 即为获胜。游戏过程中还可以欣赏精彩的配乐。
Tags:
- emoji
- 游戏
- 记忆游戏
ManifestType: locale
ManifestVersion: 1.12.0
