# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Plenom.kuandoBusylight.Webex
PackageVersion: 1.0.21.0
InstallerType: zip
NestedInstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
ReleaseDate: 2026-10-08
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: Busylight4WebexSetup.msi
  InstallerUrl: https://www.plenom.com/download/208271/
  InstallerSha256: FE785A3F4D117EDDF6DF53FA30000281CCBDC31743B8FC72E2B8F413CB4BBB4A
  ProductCode: '{1010A317-D64D-4168-BF90-475660A5A63D}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{B71AB582-5439-48AD-84A6-9713E679622D}'
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: Busylight4WebexSetup64.msi
  InstallerUrl: https://www.plenom.com/download/208271/
  InstallerSha256: FE785A3F4D117EDDF6DF53FA30000281CCBDC31743B8FC72E2B8F413CB4BBB4A
  ProductCode: '{7AC3F86E-87AA-42EE-9FB0-8299B4C37FC3}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{95D4B6DC-01C4-4233-BF16-425031E1FE47}'
ManifestType: installer
ManifestVersion: 1.12.0
