# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Nightly
PackageVersion: 155.1.99.25
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser
ReleaseDate: 2026-10-08
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.25/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: D3523E703454B894192CD676D7570AE6A9D779A9C70704F88E2FF65A514020CF
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.25/BraveBrowserStandaloneNightlySetup32.exe
  InstallerSha256: 268DD650684B68B4B3A410B6127E012B611DA6D10DDA7705990C209718309435
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.25/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: 71A37807E9014E19A459328ABF909163F064FCA3F8399583DF8BD5CD324D906B
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.25/BraveBrowserStandaloneNightlySetup.exe
  InstallerSha256: F3ACDB51A9FA3ACA840BF072BE7A73E160465525E01570AF2ADB2C88ABB7BD62
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.25/BraveBrowserStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: B65C41E4F683BEA33D2C943494DE38801FEF22FA4F7A1260E17B9A16F954D9BE
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.25/BraveBrowserStandaloneNightlySetupArm64.exe
  InstallerSha256: E4623CB5728DF4C04B25CEFDD823626DFA89D26D8979FD260DFB32629326F037
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
