# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: liukaizheng.Zevria
PackageVersion: 0.1.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: zevria.exe
  PortableCommandAlias: zevria
Commands:
- zevria
Dependencies:
  PackageDependencies:
  - PackageIdentifier: BurntSushi.ripgrep.MSVC
  - PackageIdentifier: Git.Git
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/liukaizheng/zevria/releases/download/v0.1.0/zevria-v0.1.0-x86_64-pc-windows-msvc.zip
  InstallerSha256: 50C13D1C773287D83C239352A70104D749959D014AFB44F30990C8E13EA948EB
ManifestType: installer
ManifestVersion: 1.12.0
