# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.PdfCraft
PackageVersion: 0.4.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- UpgradeCode: '{EA00C367-7270-4C50-9D8B-A7A5C88AD27F}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/storytold/pdfcraft/releases/download/v0.4.0/pdfcraft-0.4.0-windows-x86.msi
  InstallerSha256: 1FB6F55AC82BAD3E268F8F1AF4D0DBC64F0F27F2817E505BF4F94971B0AAB4D7
  ProductCode: '{43E8495F-330F-4759-B8B8-9D5353511B6B}'
- Architecture: x64
  InstallerUrl: https://github.com/storytold/pdfcraft/releases/download/v0.4.0/pdfcraft-0.4.0-windows-x64.msi
  InstallerSha256: 76E61E2791CAB97273C0D900DC95411C1114699386E9C381A07E5FE31A643E3A
  ProductCode: '{5F056693-2240-48D6-A44A-B7BC5EBF819A}'
- Architecture: arm64
  InstallerUrl: https://github.com/storytold/pdfcraft/releases/download/v0.4.0/pdfcraft-0.4.0-windows-arm64.msi
  InstallerSha256: 15A564BCDE1B848CFAF4FED3E7F109DF26AEF1024369DDD5410868EAB0D02FF8
  ProductCode: '{0D2C5EA4-5B3C-4CDA-866D-A363BA8CD995}'
ManifestType: installer
ManifestVersion: 1.12.0
