# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.et
PackageVersion: "145.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win32/et/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: EA15802840015C99BFC996922DE527F5539F330C286F0A5AE76B31D07CF33B39
  ProductCode: Firefox Developer Edition 145.0 (x86 et)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64/et/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 478EF5C7E6B5CD2CB754CFA08268E3CBA8CF28371092594725CFD1B00EACEB94
  ProductCode: Firefox Developer Edition 145.0 (x64 et)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/145.0b7/win64-aarch64/et/Firefox%20Setup%20145.0b7.exe
  InstallerSha256: 27479545D8B489D08B7B0F88DFDD58D1B13347B3B48995FF53BA0A798A3640D0
  ProductCode: Firefox Developer Edition 145.0 (arm64 et)
ManifestType: installer
ManifestVersion: 1.10.0
