# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.ach
PackageVersion: "151.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Firefox Developer Edition
ReleaseDate: 2026-05-04
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/151.0b6/win32/ach/Firefox%20Setup%20151.0b6.exe
  InstallerSha256: E3CCC17D18B686651A35F6689B48C289B19CCCDA41A42F3940ED1047C090B8F9
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/151.0b6/win64/ach/Firefox%20Setup%20151.0b6.exe
  InstallerSha256: 5F2AD8F2D4E91346EDF48C2B8167706EC0838E9E484EE1959D0DA39EF01313BA
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/151.0b6/win64-aarch64/ach/Firefox%20Setup%20151.0b6.exe
  InstallerSha256: E3EFF894D0F3A308290405928F330E8476F9A64D3DA038B54891724D2FF2B3CF
ManifestType: installer
ManifestVersion: 1.12.0
