# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BrowserOS.BrowserClawServer
PackageVersion: 0.0.59
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: resources\bin\browseros-claw-server.exe
Commands:
- browseros-claw-server
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/browseros-ai/BrowserOS/releases/download/claw-server/v0.0.59/browseros-claw-server-rust-resources-windows-x64.zip
  InstallerSha256: 0A6C6C8EA2EE76393AF3D3F1F59EDDCA2B76365C81A7EAA8D931AA38733BC305
ManifestType: installer
ManifestVersion: 1.12.0
