# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.DesignCraft
PackageVersion: 0.4.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- UpgradeCode: '{49E87D30-BB68-4896-AA1D-F45C833CFC3C}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/storytold/designcraft/releases/download/v0.4.0/designcraft-0.4.0-windows-x86.msi
  InstallerSha256: B8FB1D4ABD6F64B97CB41DEF2C177ED557E230FCB5BAB8ECBCB4C8499E5846E3
  ProductCode: '{DCE10BC6-6959-42D6-ACFD-A2C274F2F3E4}'
- Architecture: x64
  InstallerUrl: https://github.com/storytold/designcraft/releases/download/v0.4.0/designcraft-0.4.0-windows-x64.msi
  InstallerSha256: 83863D97C3ADE9245087952D8A7A9A9240F5652F645A13C6A9E84626B7560F5C
  ProductCode: '{9ACC8763-0E9D-4844-A9CE-6848B48BB2C3}'
- Architecture: arm64
  InstallerUrl: https://github.com/storytold/designcraft/releases/download/v0.4.0/designcraft-0.4.0-windows-arm64.msi
  InstallerSha256: 107CC4A32159D95C259F272725C93282E143F1719D9CB56289A75E09D6811928
  ProductCode: '{1AF2513D-C297-4883-A03E-5638E97F80F9}'
ManifestType: installer
ManifestVersion: 1.12.0
