# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.DeckCraft
PackageVersion: 0.3.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
FileExtensions:
- deckcraft
- potx
- ppsx
- pptx
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- UpgradeCode: '{6F9C69E7-7825-40D2-BF26-C274DA676425}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/storytold/deckcraft/releases/download/v0.3.0/deckcraft-0.3.0-windows-x86.msi
  InstallerSha256: 9201EF1D337B47E99BF638D5477CBD41F41CFBA4C4660C213B510E3233DC7467
  ProductCode: '{C737CC1D-275F-4098-80B2-D8910832371C}'
- Architecture: x64
  InstallerUrl: https://github.com/storytold/deckcraft/releases/download/v0.3.0/deckcraft-0.3.0-windows-x64.msi
  InstallerSha256: 707AD46D6A17428291A0193CB7F1AAF8D5BF103D2202381F770B233845586B4D
  ProductCode: '{64015A08-4D7C-4A61-A15E-6BB1A2BF8F9D}'
- Architecture: arm64
  InstallerUrl: https://github.com/storytold/deckcraft/releases/download/v0.3.0/deckcraft-0.3.0-windows-arm64.msi
  InstallerSha256: E18EFF23CD16C250091A6E5641DE5AFF84A465EF21AE045F6A89240CCFA77746
  ProductCode: '{A79480A0-4A6F-430D-9502-48ABB3813691}'
ManifestType: installer
ManifestVersion: 1.12.0
