# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.de
PackageVersion: "151.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Firefox Developer Edition
ReleaseDate: 2026-05-06
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/151.0b7/win32/de/Firefox%20Setup%20151.0b7.exe
  InstallerSha256: 2DE5563B99AA2AB9ED4523464C147B1D25E11615D3D71B8E51BD336605B8F1C7
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/151.0b7/win64/de/Firefox%20Setup%20151.0b7.exe
  InstallerSha256: 93815F139ABE35D5632ACB54C8A65A841BAFF69F2BC35F8478DECE93A545B7B8
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/151.0b7/win64-aarch64/de/Firefox%20Setup%20151.0b7.exe
  InstallerSha256: 086476609534C0AE0EA49E8EAE898754FA0EDF0F3035312F7D7D266A805218E8
ManifestType: installer
ManifestVersion: 1.12.0
