# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TandemHealth.Tandem
PackageVersion: 2026.3.9
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
Protocols:
- tandemhealth
ProductCode: Tandem
Installers:
- Architecture: x64
  InstallerUrl: https://tandemhealth.blob.core.windows.net/tandem-public/native/Tandem-win-Setup.exe
  InstallerSha256: 16E236CC07939D2C9C268396753D8D399962E007826DD3030C5CF33277491D25
ManifestType: installer
ManifestVersion: 1.12.0
