# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: kdlbs.KanDev
PackageVersion: 0.97.0
InstallerType: nullsoft
Scope: user
ProductCode: Kandev
ReleaseDate: 2026-10-04
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Kandev'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kdlbs/kandev/releases/download/v0.97.0/kandev-desktop-windows-x64-Kandev_0.97.0_x64-setup.exe
  InstallerSha256: 8365040EFEF1FAB97770B7537A46F74BDD2047404140AB2FE77208BB820D80B1
ManifestType: installer
ManifestVersion: 1.12.0
