# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PTV.Viswalk.2026
PackageVersion: 2026.00-10
InstallerType: inno
Scope: machine
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Wibu-Systems.CodeMeterRuntimeKit
ProductCode: '{VISWALK_260_B02CC8DE-A297-11DE-82EA-0019990EF7FA}_IS0_is1'
ReleaseDate: 2026-08-05
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\PTV Vision\PTV Viswalk 2026'
Installers:
- Architecture: x64
  InstallerUrl: https://cgi.ptvgroup.com/visionSetups/Setups/VISWALK/260/Setup_VISWALK_2026.00-10_x64.exe
  InstallerSha256: 0B10D955C6AF177C36494E2AC31F3BB6203A6F88B8AD248B280E71F87D9D549B
ManifestType: installer
ManifestVersion: 1.12.0
