# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: CometNetwork.BitComet
PackageVersion: "2.13"
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Protocols:
- bc
- bc_bak
- magnet
FileExtensions:
- bc!
- torrent
ReleaseDate: 2025-04-13
Installers:
- Architecture: x86
  InstallerUrl: https://download.bitcomet.com/achive/BitComet_2.13_setup.exe
  InstallerSha256: 48C31EEB5B823599AB5C7B13BB49930896419DD77AC7907C5FE9785D7732DF24
  ProductCode: BitComet
- Architecture: x64
  InstallerUrl: https://download.bitcomet.com/achive/BitComet_2.13_setup.exe
  InstallerSha256: 48C31EEB5B823599AB5C7B13BB49930896419DD77AC7907C5FE9785D7732DF24
  ProductCode: BitComet_x64
ManifestType: installer
ManifestVersion: 1.10.0
