# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: CometNetwork.BitComet
PackageVersion: "2.13"
PackageLocale: en-US
Publisher: CometNetwork
PublisherUrl: https://www.bitcomet.com/en
PublisherSupportUrl: https://wiki.bitcomet.com/
PrivacyUrl: https://wiki.bitcomet.com/privacy_policy
PackageName: BitComet
PackageUrl: https://www.bitcomet.com/en
License: Freeware
LicenseUrl: https://www.bitcomet.com/en/license
Copyright: (C) 2003-2024 BitComet.com
CopyrightUrl: https://www.bitcomet.com/en/copyright
ShortDescription: A free C++ BitTorrent Download Client
Description: BitComet is a free BitTorrent download client which is powerful, super-fast and easy-to-use.
Tags:
- bittorrent
- bt
- download
- magnet
- p2p
- share
- sharing
- torrent
- upload
ReleaseNotes: |-
  GUI Improved: A prompt is added to the proxy server option to indicate that only IP addresses are supported, not domain names
  GUI Improved: A prompt message is added to the listening port on the remote access settings page
  WebUI：Implement task piece graphs
  WebUI：Implement flow graph
  WebUI：The bottom bar displays status information
  WebUI：Added CometID sign in dialog
  WebUI：Added mobile APP binding function
  WebUI：The console mode program does not allow disabling the WebUI
  WebUI：Fixed the issue of menu operation on touchscreen devices
  WebUI：Fixed task switch refresh when auto-refresh was disabled
  WebUI：Avoid legacy remote access page requests for favicon.ico
  Core Improved: Win32 editions supports file names including emoji characters
  Core Bugfix: The algorithm for blocking peers who transmit erroneous data multiple times has failed
  Core Bugfix: When moving BT task files to other directories on the same drive, the files of non-BT tasks in the folder will be moved together, regardless of whether selecting Move all files in the subfolder of the task
  Core Bugfix: The task list is sorted incorrectly by task size, and the BT task size should exclude the size of the padded area of the file boundary
ReleaseNotesUrl: https://www.bitcomet.com/en/changelog
Documentations:
- DocumentLabel: FAQ
  DocumentUrl: https://wiki.bitcomet.com/frequently_asked_questions
ManifestType: defaultLocale
ManifestVersion: 1.10.0
