# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenLogic.OpenJDK.17.JRE
PackageVersion: 17.0.20.8
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Custom: ADDLOCAL=ALL
UpgradeBehavior: install
Commands:
- java
- javaw
- jfr
- jrunscript
- keytool
- kinit
- klist
- ktab
- rmiregistry
FileExtensions:
- class
- jar
- java
- jsp
ProductCode: '{9FA458E3-145A-4387-8283-89EB0C1DCE87}'
ReleaseDate: 2026-08-06
AppsAndFeaturesEntries:
- DisplayName: OpenLogic-OpenJDK JRE with Hotspot 17.0.20+8 (x64)
  UpgradeCode: '{292C9239-6BF6-4226-B55D-073F85BCFB3E}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\OpenLogic\jre-17.0.20.8-hotspot'
Installers:
- Architecture: x64
  InstallerUrl: https://builds.openlogic.com/downloadJDK/openlogic-openjdk-jre/17.0.20+8/openlogic-openjdk-jre-17.0.20+8-windows-x64.msi
  InstallerSha256: 207EE713A35BDEDC7A8CBFA1B41DD745604F8891E96EFBEFFA7C5A89D5E9AE57
ManifestType: installer
ManifestVersion: 1.12.0
