# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Klakk.Klakk
PackageVersion: 1.4.0
PackageLocale: zh-CN
PublisherSupportUrl: https://tryklakk.com/zh/support/
PrivacyUrl: https://tryklakk.com/zh/windows/privacy/
License: 专有软件
ShortDescription: 在常用 Windows 应用中，让每次敲击都有更带感的反馈。
Description: Klakk 可在你平时使用的 Windows 应用中，随着每次按键播放机械键盘音效。内置 14 套从柔和到清脆的键盘音效，音量随心调整，并跟随 Windows 当前音频输出，扬声器和耳机均可使用。
Tags:
- 打字
- 键盘
- 键盘音效
ManifestType: locale
ManifestVersion: 1.12.0
