# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Autodesk.SingleSignOn
PackageVersion: 14.1.3.1803
PackageLocale: en-US
Publisher: Autodesk, Inc.
# PublisherUrl: https://www.autodesk.com/
# PublisherSupportUrl: https://www.autodesk.com/support
# PrivacyUrl: https://www.autodesk.com/company/legal-notices-trademarks/privacy-statement
Author: Autodesk, Inc.
PackageName: Autodesk Single Sign On Component
# PackageUrl: https://www.autodesk.com/support/technical/article/caas/tsarticles/ts/A785RG35hP8oUR96WrYkn.html
License: Proprietary
# LicenseUrl: https://www.autodesk.com/company/terms-of-use/general-terms
Copyright: © 2026 Autodesk, Inc. All rights reserved.
# CopyrightUrl: https://www.autodesk.com/company/terms-of-use/general-terms
ShortDescription: A sign-in component that works with versions 2020 and later of Autodesk software.
Description: The Autodesk Single Sign On Component (AdSSO) provides the sign-in experience for versions 2020 and later of Autodesk software. The component is backward compatible with older Autodesk product releases, and Autodesk recommends always installing the latest available version for better security and performance.
Tags:
- autodesk
- sso
ManifestType: defaultLocale
ManifestVersion: 1.12.0
