# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: apernet.Hysteria
PackageVersion: 2.13.0
InstallerType: portable
Commands:
- hysteria
ReleaseDate: 2026-10-05
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/HyNetworks/hysteria/releases/download/app/v2.13.0/hysteria-windows-386.exe
  InstallerSha256: 92A47F51B71234DAAA6E7DF139AD4FA35160338F47AB7A2EB99C930D54BD1819
- Architecture: x64
  InstallerUrl: https://github.com/HyNetworks/hysteria/releases/download/app/v2.13.0/hysteria-windows-amd64.exe
  InstallerSha256: 162EF8FE55DC7EC810DDA662908F8E65EC36BD6DA39CB87C3BD66184AB68F067
- Architecture: arm64
  InstallerUrl: https://github.com/HyNetworks/hysteria/releases/download/app/v2.13.0/hysteria-windows-arm64.exe
  InstallerSha256: B22D223025299801CB018CAB35120CB8F4F9FE2E73E44B9E60A48963F7DC91E7
ManifestType: installer
ManifestVersion: 1.12.0
