# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.CraftLauncher
PackageVersion: 0.1.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-10-10
AppsAndFeaturesEntries:
- UpgradeCode: '{1AC08DBF-D4CF-4BA4-A81E-CAA5C1004974}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/storytold/craft-launcher/releases/download/v0.1.0/artcraft-launcher-0.1.0-windows-x86.msi
  InstallerSha256: B434BDF9D519509DBDF9C47485550B094FE19EB52B47E16A4DEB537CBE14272B
  ProductCode: '{CC65F7DA-F28B-407F-AB45-1B5C52174A28}'
- Architecture: x64
  InstallerUrl: https://github.com/storytold/craft-launcher/releases/download/v0.1.0/artcraft-launcher-0.1.0-windows-x64.msi
  InstallerSha256: CC974661803ED88AEFB2773C23B51D26E6633338377A8E9D38C5E53F8EAF7F3F
  ProductCode: '{C04E317F-BC5C-447D-8164-966AA5B828A4}'
- Architecture: arm64
  InstallerUrl: https://github.com/storytold/craft-launcher/releases/download/v0.1.0/artcraft-launcher-0.1.0-windows-arm64.msi
  InstallerSha256: 8157C7CFDD59502604767237AECD0DF63E5293408219B1CC2212CAAB077EF8F8
  ProductCode: '{74C47C0B-FF53-433B-8D0D-D1696F62ACB4}'
ManifestType: installer
ManifestVersion: 1.12.0
