# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Testsmith.APISpector
PackageVersion: 0.7.2
InstallerType: nullsoft
Scope: user
ProductCode: 95cc2717-24c6-5b98-ad69-d94d625ca35a
ReleaseDate: 2026-09-30
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\@testsmithapi-spector'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/testsmith-io/api-spector/releases/download/0.7.2/API-Spector-Setup-0.7.2.exe
  InstallerSha256: BA9E69F3420492B3EB892C91C4B6F060D4F97D09313B8471D556415A0D52684F
ManifestType: installer
ManifestVersion: 1.12.0
