# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: metasequoiaime.MetasequoiaIME
PackageVersion: 0.9.5
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
ProductCode: '{A7C3E91F-4B2D-4E8A-9F1C-6D5E8B0A2C4D}_is1'
ReleaseDate: 2026-10-05
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/metasequoiaime/msime-windows/releases/download/v0.9.5/MetasequoiaIME_Setup_v0.9.5.exe
  InstallerSha256: 6641A5BBEC4CB374BBC54EB1DFF1B3AEAD6A2E6A0E4190EAB994223EE296AEA5
ManifestType: installer
ManifestVersion: 1.12.0
