# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Hitencent.JisuPDFEditor
PackageVersion: "3.0"
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
FileExtensions:
- pdf
ProductCode: 极速PDF编辑器
ReleaseDate: 2025-03-05
Installers:
- Architecture: x86
  InstallerUrl: https://dl.jisupdfeditor.com/jisupdfeditor_setup_3.0.6.3.exe
  InstallerSha256: C94A32651AFD13151AA3244B7945F9AF19309018C7D178B271CEB15C178D5ED9
ManifestType: installer
ManifestVersion: 1.9.0
