# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Hitencent.JisuPDFEditor
PackageVersion: "3.0"
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
FileExtensions:
- pdf
ProductCode: 极速PDF编辑器
ReleaseDate: 2025-05-08
Installers:
- Architecture: x86
  InstallerUrl: https://dl.jisupdfeditor.com/jisupdfeditor_setup_3.0.6.5.exe
  InstallerSha256: 12E66F7FE35EC4FB66FDB6D7DFE5214CECDF94B6F4CEB353EC22F7DA029EB40C
ManifestType: installer
ManifestVersion: 1.10.0
