# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: egoist.Waku
PackageVersion: 0.1.20
InstallerType: inno
Scope: user
ProductCode: '{8B6C6E4A-3E0F-4F0B-9C5F-2E0E9C4B7A11}_is1'
ReleaseDate: 2026-10-02
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\Waku'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/egoist/waku/releases/download/v0.1.20/Waku-0.1.20-x86_64-Setup.exe
  InstallerSha256: 71931591C67E56714429E19A38B6C30BE2AFA76AA38A485ADD8C75407AEFF2B6
ManifestType: installer
ManifestVersion: 1.12.0
