# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BtbN.FFmpeg.LGPL.Shared
PackageVersion: N-127021-ge0c94b2d1c-20260930
InstallerType: zip
NestedInstallerType: portable
Commands:
- ffmpeg
- ffplay
- ffprobe
ReleaseDate: 2026-09-30
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-win64-lgpl-shared\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-win64-lgpl-shared\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-win64-lgpl-shared\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-30-13-08/ffmpeg-N-127021-ge0c94b2d1c-win64-lgpl-shared.zip
  InstallerSha256: 2CC3DD0BAF74EBD68A3FCEAF771DF8351A7A6D69694D05F43B16BB0C966EC909
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-winarm64-lgpl-shared\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-winarm64-lgpl-shared\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-winarm64-lgpl-shared\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-30-13-08/ffmpeg-N-127021-ge0c94b2d1c-winarm64-lgpl-shared.zip
  InstallerSha256: 60A4863501134269E4797B3BD4F7EDA7B9271B71B35231BD6DFE46699887A638
ManifestType: installer
ManifestVersion: 1.12.0
