# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Anthropic.Claude
PackageVersion: 2.26454.0
Protocols:
- claude
ReleaseDate: 2026-10-06
Installers:
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://downloads.claude.ai/releases/win32/x64/2.26454.0/Claude-98e3cc1cd15d9a6adac008c6e9aac52e08f0f1b1.msix
  InstallerSha256: D8514A1356B334852C665D98ED778DB53DF78AD38E136A8C142BDBE020B68A74
  SignatureSha256: 7322C94BCCC496CF4841BF1463481532ED70284E9DDA037FB60256B1F9935826
  PackageFamilyName: Claude_pzs8sxrjxfjjc
  Capabilities:
  - internetClient
  RestrictedCapabilities:
  - localSystemServices
  - packagedServices
  - runFullTrust
  - unvirtualizedResources
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://downloads.claude.ai/releases/win32/arm64/2.26454.0/Claude-98e3cc1cd15d9a6adac008c6e9aac52e08f0f1b1.msix
  InstallerSha256: 3D56E881383A8BF948BE77E810BAC9E685B79D91EC7BB85177F0908C47B4F44F
  SignatureSha256: 089967375E9ABA2340FF14CDD84794E38BC8D354F6E67D8192338A9C17EBA0E8
  PackageFamilyName: Claude_pzs8sxrjxfjjc
  Capabilities:
  - internetClient
  RestrictedCapabilities:
  - localSystemServices
  - packagedServices
  - runFullTrust
  - unvirtualizedResources
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.claude.ai/releases/win32/x64/2.26454.0/Claude-98e3cc1cd15d9a6adac008c6e9aac52e08f0f1b1.exe
  InstallerSha256: 7716E92167A7800E65D10E64F75C8FC52F499BFDE56D2A8A319BC5C957AABE82
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
  ProductCode: AnthropicClaude
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.claude.ai/releases/win32/arm64/2.26454.0/Claude-98e3cc1cd15d9a6adac008c6e9aac52e08f0f1b1.exe
  InstallerSha256: C3B66138A7ADAC4417F0E9E18EB9F8047FBF8488D7BA1E03B628CD63BC0A5332
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
  ProductCode: AnthropicClaude
ManifestType: installer
ManifestVersion: 1.12.0
