# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: lbjlaq.AntigravityTools
PackageVersion: 4.9.6
UpgradeBehavior: install
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/lbjlaq/Antigravity-Manager/releases/download/v4.9.6/Antigravity.Tools_4.9.6_x64-setup.exe
  InstallerSha256: 03725CD33B910C559232B30E7FD64A9A2391C17346576232966205B470E96EAA
  ProductCode: Antigravity Tools
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Antigravity Tools'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/lbjlaq/Antigravity-Manager/releases/download/v4.9.6/Antigravity.Tools_4.9.6_x64_en-US.msi
  InstallerSha256: 5AC5FE7648F5AEC58707A1AC3ACE5AEF6BD8243F0E608F6822DB0F5FB058ED12
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{35C673AA-E519-434F-B0A7-C02B1DF75908}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{E6D0D59B-1948-5950-A427-E2A516157557}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Antigravity Tools'
ManifestType: installer
ManifestVersion: 1.12.0
