# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: lidge-jun.OpenCodex
PackageVersion: 2.78.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
ProductCode: '{1FCB109A-AB74-43C5-981C-3B72EF8A4028}'
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- UpgradeCode: '{505158BD-FA60-5623-B931-DA1576D39069}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/lidge-jun/opencodex/releases/download/v2.78.0/OpenCodex-2.78.0-windows-x64.msi
  InstallerSha256: 79444B699B43A14A238B3602D5C1105415AF31C36BA2ACFA54593F87856DE49A
ManifestType: installer
ManifestVersion: 1.12.0
