# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.PasswordManager
PackageVersion: 1.0.3.1
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente Password Manager 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/passwordmanagerx86
  InstallerSha256: B084EC1D11DDCBB0D233586723A5CDFC5A3EEC167416F650E84BA86B6EE9E366
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/passwordmanagerx64
  InstallerSha256: 2908DCE60A4D07CE6A6CD43D1580E898B608D55F8F738797D1A82B3F464494C2
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/passwordmanagerarm64
  InstallerSha256: A8EED1119837B1957F66D32DF1B3EF8595886D79CD3EEF45001D0335678D468F
ManifestType: installer
ManifestVersion: 1.12.0
