# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.GridCraft
PackageVersion: 0.3.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
FileExtensions:
- csv
- tsv
- xlsm
- xlsx
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- UpgradeCode: '{5511327B-F305-41BE-92D0-EB84944E7C4D}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/storytold/gridcraft/releases/download/v0.3.0/gridcraft-0.3.0-windows-x86.msi
  InstallerSha256: 840B21D5154FE7F6251505CB7092D3981A446D36B942212A63E5C720D28A8BAC
  ProductCode: '{8F143ADD-3C8D-46A8-98B6-671FA56DDCDB}'
- Architecture: x64
  InstallerUrl: https://github.com/storytold/gridcraft/releases/download/v0.3.0/gridcraft-0.3.0-windows-x64.msi
  InstallerSha256: 0764D69B1E600D49AC9EACB1ECFB0F1AC4AA416C16549B9BABC28780C2FCFB84
  ProductCode: '{581AB578-9D81-4567-82F4-BEE77A5238DE}'
- Architecture: arm64
  InstallerUrl: https://github.com/storytold/gridcraft/releases/download/v0.3.0/gridcraft-0.3.0-windows-arm64.msi
  InstallerSha256: 2AE9ADB0009C3503AD9AC4D6FD675265BAB66AAC2CA9CEC1A5B33BEFE50D4AFA
  ProductCode: '{124273AF-50D0-47BC-8018-BFA5823F87B9}'
ManifestType: installer
ManifestVersion: 1.12.0
