# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DBeaver.DBeaver.Community
PackageVersion: 26.2.2
InstallerType: nullsoft
FileExtensions:
- sql
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/26.2.2/dbeaver-ce-26.2.2-windows-x86_64.exe
  InstallerSha256: 6DE2427F0EA760424C1F34B9EC056B1F18878576BD5054850DAA0CEFBFB90A79
  InstallerSwitches:
    Custom: /currentuser
  ProductCode: DBeaver (current user)
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/26.2.2/dbeaver-ce-26.2.2-windows-x86_64.exe
  InstallerSha256: 6DE2427F0EA760424C1F34B9EC056B1F18878576BD5054850DAA0CEFBFB90A79
  InstallerSwitches:
    Custom: /allusers
  ProductCode: DBeaver
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/26.2.2/dbeaver-ce-26.2.2-windows-aarch64.exe
  InstallerSha256: 75FDFED00B511B2E3B2C8D5230E078DB14A75C1EEE62CAC92A02ADD8787ACABB
  InstallerSwitches:
    Custom: /currentuser
  ProductCode: DBeaver (current user)
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/26.2.2/dbeaver-ce-26.2.2-windows-aarch64.exe
  InstallerSha256: 75FDFED00B511B2E3B2C8D5230E078DB14A75C1EEE62CAC92A02ADD8787ACABB
  InstallerSwitches:
    Custom: /allusers
  ProductCode: DBeaver
ManifestType: installer
ManifestVersion: 1.12.0
