# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.ast
PackageVersion: "151.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Firefox Developer Edition
ReleaseDate: 2026-05-04
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/151.0b6/win32/ast/Firefox%20Setup%20151.0b6.exe
  InstallerSha256: A6D113B2F846344CD01A3E0F0B9D48107DFE32251BEE00F18A11DB3248602557
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/151.0b6/win64/ast/Firefox%20Setup%20151.0b6.exe
  InstallerSha256: 124A931C5CA5E7E8BAD0B56DB2E9358242BB7A21DC81E12A1FE54611010C71A2
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/151.0b6/win64-aarch64/ast/Firefox%20Setup%20151.0b6.exe
  InstallerSha256: 3F394A50C1C5C11158B5EF5572F10B56CC26FBF9F89BB267DE64935253B629DC
ManifestType: installer
ManifestVersion: 1.12.0
