# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: KDE.Kapman
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: kapman
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/games/kapman/master/windows/kapman-master-766-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: F361BC578F4DE71F7F59228ECC9C367C36BE90B858B966392759739948B0511E
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/games/kapman/master/windows/kapman-master-766-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: F361BC578F4DE71F7F59228ECC9C367C36BE90B858B966392759739948B0511E
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.10.0
