# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Qingfeng.HeyboxWow
PackageVersion: 2.0.13
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
ProductCode: e87df3d8-3e5c-5367-8ffd-a8367ca20271
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://static.max-c.com/static/heybox/heybox_desktop/v2.6.15/4604ef62d9ad/win/x64/heybox-desktop-2.6.15-win-x64--at_RgTvYtmttANW.exe
  InstallerSha256: AD34895E608EC7148D6940C06A34065439D333436F5524F2DA8610FEEA576D13
ManifestType: installer
ManifestVersion: 1.12.0
