# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ImageMagick.ImageMagick.Q8
PackageVersion: 7.1.2.33
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Commands:
- compare
- composite
- conjure
- identify
- magick
- mogrify
- montage
- stream
ReleaseDate: 2026-10-10
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-33/ImageMagick-7.1.2-33-Q8-x86-dll.exe
  InstallerSha256: 899A88A61BD75EEBAF072EBDB29D78730824CE64A1E79A64918A6C8691F8FAB7
  ProductCode: ImageMagick 7.1.2 Q8 (32-bit)_is1
- Architecture: x64
  InstallerUrl: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-33/ImageMagick-7.1.2-33-Q8-x64-dll.exe
  InstallerSha256: 1F9798C5CDE7871BC78E6A7E9B4BA7B62D3614D7021A34FC3B13CD868195022F
  ProductCode: ImageMagick 7.1.2 Q8 (64-bit)_is1
- Architecture: arm64
  InstallerUrl: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-33/ImageMagick-7.1.2-33-Q8-arm64-dll.exe
  InstallerSha256: 9AB7C4C7693B2E6B2B355BE548590C31D15EDDFB965002226B99156B89DD035A
  ProductCode: ImageMagick 7.1.2 Q8 (arm64)_is1
ManifestType: installer
ManifestVersion: 1.12.0
