# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Amazon.WorkspacesClient
PackageVersion: 5.35.0.3249
PackageLocale: en-US
Publisher: Amazon Web Services, Inc
PublisherUrl: https://aws.amazon.com/
PublisherSupportUrl: https://console.aws.amazon.com/support/home/
PrivacyUrl: https://aws.amazon.com/privacy/
Author: Amazon Web Services, Inc
PackageName: Amazon WorkSpaces
PackageUrl: https://clients.amazonworkspaces.com/
License: Proprietary
LicenseUrl: https://clients.amazonworkspaces.com/app-terms.html
Copyright: © 2026 Amazon Web Services, Inc. or its affiliates. All rights reserved.
CopyrightUrl: https://aws.amazon.com/trademark-guidelines/
ShortDescription: Amazon WorkSpaces plays nice with everyone. Access your personal Windows environment on Android, iOS, Fire, Mac, PC, Chromebook, and Linux devices.
Moniker: workspaces
Tags:
- amazon
- aws
- workspaces
ReleaseNotes: |-
  - [Windows] Improved full screen mode in the new client experience, adding a dedicated full screen button in the toolbar and a convenient dropdown to choose between full screen modes anytime.
  - [Windows] Added language support for French, German, Portuguese, Spanish, Japanese, Korean, and Chinese in the new client experience (available under Settings).
  - [Windows] Added an option to "Show in folder" to file upload notifications in the new client experience, simplifying the navigation to the uploaded file's location.
  - [Windows] Re-enabled support for honoring printer preferences when printing from a session, which had been temporarily disabled in version 5.34.1.
  - [Windows] Improved the message shown when choosing Try New WorkSpaces to clarify that PCoIP-based WorkSpaces and WorkSpaces Pools are not supported in the new client experience.
  - [Windows] Fixed an issue in the new client experience that allowed connecting to a WorkSpace that was not available, such as one under maintenance, under certain conditions.
  - [Windows] Fixed an issue in the new client experience that prevented signing in after the sign-in page had been open for about 30 minutes.
  - [Windows] Fixed an issue that prevented the Settings and self-service options in the new client experience from displaying correctly when a high contrast theme was enabled or changed in the local Windows device.
  - [Windows] Reduced the size of the client installer.
  - [Windows] Updated the DCV SDK.
  - [Windows] Updated the WebView2 SDK.
  - [Windows] Additional bug fixes and enhancements.
ReleaseNotesUrl: https://d2td7dqidlhjx7.cloudfront.net/prod/global/windows/relnotes.html
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://docs.aws.amazon.com/workspaces/latest/userguide/amazon-workspaces-clients.html
ManifestType: defaultLocale
ManifestVersion: 1.12.0
