# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AnkioTomas.QQPet
PackageVersion: 0.4.0
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: 7a7efa50-34d4-5545-b88e-be04524bf06e
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AnkioTomas/qqpet/releases/download/v0.4.0/QQPet.Setup.0.4.0.exe
  InstallerSha256: D43640AF6A43592DA3175AFF7AF053E91C8C297C72C1AAAB65306EEB1CB5336F
ManifestType: installer
ManifestVersion: 1.12.0
