# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.SoundCraft
PackageVersion: 0.3.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
FileExtensions:
- aif
- aiff
- flac
- mid
- midi
- mp3
- scraft
- wav
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- UpgradeCode: '{EE53D3E5-D0AE-40F9-808D-9417FDEBF61A}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/storytold/soundcraft/releases/download/v0.3.0/soundcraft-0.3.0-windows-x86.msi
  InstallerSha256: A0BB9E8E68A34270F4C08B652313ABF2E797A40F3FFA72777A771F81983EACA7
  ProductCode: '{1F8F4E20-FC80-4505-B46B-927471AE3E5A}'
- Architecture: x64
  InstallerUrl: https://github.com/storytold/soundcraft/releases/download/v0.3.0/soundcraft-0.3.0-windows-x64.msi
  InstallerSha256: CB084EF5EFC9BE5151FA52D345656CE17AE511776E32F39ED510517DBDB0BDC8
  ProductCode: '{3E714387-0F95-4F16-8314-A3BCA1F995EE}'
- Architecture: arm64
  InstallerUrl: https://github.com/storytold/soundcraft/releases/download/v0.3.0/soundcraft-0.3.0-windows-arm64.msi
  InstallerSha256: BA77DC5E7E10250C163EE4F98B046096D9DC355AB45045F4376E382EBC54972D
  ProductCode: '{222702CC-BECC-4DFD-B569-8E5373AB3BDE}'
ManifestType: installer
ManifestVersion: 1.12.0
