# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Akregator
PackageVersion: 6.8.40
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: akregator
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/pim/akregator/master/windows/akregator-master-2877-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 0C254F2FB6124A9C487F3041149A8249DE0DBAC18B609077BB2CCD22BF34770B
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/pim/akregator/master/windows/akregator-master-2877-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 0C254F2FB6124A9C487F3041149A8249DE0DBAC18B609077BB2CCD22BF34770B
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
