# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: wxyhgk.RetainPDF
PackageVersion: 4.2.5
InstallerType: nullsoft
ProductCode: fdd679c8-99a1-5279-9f69-6a7036bdc046
ReleaseDate: 2026-09-19
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\RetainPDF'
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/wxyhgk/retain-pdf/releases/download/v4.2.5/RetainPDF-Windows-4.2.5-Setup.exe
  InstallerSha256: 5BC79BD14B452456D1CBB8A1EDC56552260BF2F088DEDA1EE010E14E025C485E
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/wxyhgk/retain-pdf/releases/download/v4.2.5/RetainPDF-Windows-4.2.5-Setup.exe
  InstallerSha256: 5BC79BD14B452456D1CBB8A1EDC56552260BF2F088DEDA1EE010E14E025C485E
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
