# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DaveWeaver.Silo
PackageVersion: 0.72.0
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/silo-code/silo/releases/download/silo-v0.72.0/Silo_0.72.0_x64-setup.exe
  InstallerSha256: 236228C7BEA28A206E4DA8C96DD9D83189F58565686F677F2BB9DE7F50FF9B92
  ProductCode: Silo
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Silo'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/silo-code/silo/releases/download/silo-v0.72.0/Silo_0.72.0_x64_en-US.msi
  InstallerSha256: CF60649E4E2D8017AAB0DC6B7631ED03A6F315B07DB2DF9EDCB26244C5880CD6
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{F4EE050E-25CF-433E-9557-CC5E5B876947}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{CEC0B5C0-A863-5F28-9580-E325823813BE}'
ManifestType: installer
ManifestVersion: 1.12.0
