# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: anglee0323.AntigravityToolsLite
PackageVersion: 4.7.6
InstallerType: nullsoft
Scope: user
ProductCode: Antigravity Tools Lite
ReleaseDate: 2026-09-26
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Antigravity Tools Lite'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/anglee0323/antigravity-tools-lite/releases/download/v4.7.6/Antigravity-Tools-Lite-4.7.6-windows-x64-setup.exe
  InstallerSha256: 53167E6AC78B2C1FCDFFE843208A76EDE056024E2C24B45BCA54491C00C3029D
ManifestType: installer
ManifestVersion: 1.12.0
