# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.10.0.schema.json

PackageIdentifier: ConnectWise.ScreenConnect
PackageVersion: 25.2.4.9229
PackageLocale: zh-CN
License: 专有软件
ShortDescription: 远程支持与访问软件，助您更快解决IT问题
Tags:
- 远程
- 远程协助
- 远程支持
- 远程桌面
- 远程访问
Documentations:
- DocumentLabel: 文档
  DocumentUrl: https://docs.connectwise.com/ScreenConnect_Documentation
ManifestType: locale
ManifestVersion: 1.10.0
