# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WEP-56.Tlegado
PackageVersion: 0.1.0
InstallerType: portable
Commands:
- tlegado
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/WEP-56/Tlegado/releases/download/v0.1.0/tlegado-win32-x64.exe
  InstallerSha256: 8CA16AFF2FC3960E05C8A333E1AC57DD8BB7A8B40DEE89C5D318B3DF6BDD9CAA
ManifestType: installer
ManifestVersion: 1.12.0
