# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Dewesoft.DSCalibrator
PackageVersion: "2026.2"
InstallerType: inno
Scope: machine
ProductCode: DSCalibrator_is1
ReleaseDate: 2026-10-06
ElevationRequirement: elevationRequired
InstallationMetadata:
  DefaultInstallLocation: C:\DSCalibrator\DSCalibrator5
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.dewesoft.com/other-software/DSCalibrator_261005124259_x64_release_2026_2.exe
  InstallerSha256: 7A7961B23131C94783F409139117CD3C5370826C06847B10161A017B7CC8E587
  AppsAndFeaturesEntries:
  - DisplayVersion: 2026.2 x64 (RELEASE)
- Architecture: x86
  InstallerUrl: https://downloads.dewesoft.com/other-software/DSCalibrator_261005124937_x86_release_2026_2.exe
  InstallerSha256: F67B463E89E93423BA5CA10A51000F57B0437AD367987908EA39D3AC3B45843C
  AppsAndFeaturesEntries:
  - DisplayVersion: 2026.2 x86 (RELEASE)
ManifestType: installer
ManifestVersion: 1.12.0
