# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Kontact
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: Kontact
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/pim/kontact/master/windows/kontact-master-2850-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 585798DB9734A33E29131A02F17053335CE6D44AE465876B0D5E496C89A805B7
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/pim/kontact/master/windows/kontact-master-2850-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 585798DB9734A33E29131A02F17053335CE6D44AE465876B0D5E496C89A805B7
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
