# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenLogic.OpenJDK.25.JDK
PackageVersion: 25.0.4.7
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Custom: ADDLOCAL=ALL
UpgradeBehavior: install
Commands:
- jar
- jarsigner
- java
- javac
- javadoc
- javap
- javaw
- jconsole
- jdeprscan
- jdeps
- jlink
- jmod
- jps
- jshell
- jstat
- keytool
FileExtensions:
- class
- jar
- java
- jsp
ProductCode: '{0786C6E3-25DB-4A82-85DE-15BE0EB4D662}'
ReleaseDate: 2026-08-06
AppsAndFeaturesEntries:
- DisplayName: OpenLogic-OpenJDK JDK with Hotspot 25.0.4+7 (x64)
  UpgradeCode: '{E0E8F852-612A-4C72-802E-9B59F070B179}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\OpenLogic\jdk-25.0.4.7-hotspot'
Installers:
- Architecture: x64
  InstallerUrl: https://builds.openlogic.com/downloadJDK/openlogic-openjdk/25.0.4+7/openlogic-openjdk-25.0.4+7-windows-x64.msi
  InstallerSha256: 1E67BB643F6BC2466F530B5792FF230ABA8815EC9139576683BA393554327E35
ManifestType: installer
ManifestVersion: 1.12.0
