# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: lehhair.PiUI
PackageVersion: 0.6.21
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: PiUI
ReleaseDate: 2026-08-23
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/lehhair/PiUI/releases/download/v0.6.21/PiUI_0.6.21_x64-setup.exe
  InstallerSha256: D350E816413F5A9ECCE2CA71AE09327BB06D6E793B40DC7BBC98834342F663E9
ManifestType: installer
ManifestVersion: 1.12.0
