# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Folge.Folge
PackageVersion: 1.40.2
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: a6386432-8ff6-5fc0-8bfc-252affc43de8
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.folge.me/Folge-1.40.2.exe
  InstallerSha256: 7EAA41F9F6135D77F638F1FF617B73F7A90808AFDCF9CD79346BA1181028667D
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.folge.me/Folge-1.40.2.exe
  InstallerSha256: 7EAA41F9F6135D77F638F1FF617B73F7A90808AFDCF9CD79346BA1181028667D
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
