# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Pixeval.Pixeval
PackageVersion: 5.0.13
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
ProductCode: Pixeval
ReleaseDate: 2026-08-21
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Pixeval'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Pixeval/Pixeval/releases/download/5.0.13/Pixeval-win-x64-Setup.exe
  InstallerSha256: 224A1F7C66A235A6F2242AA4C4D97943CD722C669728456F24A0E0FF4C89C1C7
- Architecture: x86
  InstallerUrl: https://github.com/Pixeval/Pixeval/releases/download/5.0.13/Pixeval-win-x86-Setup.exe
  InstallerSha256: 5B42D7DA3F9D3BBFE15D58D38BF424D9987D4F72E4EEDB84A08DE3F86FFBA54E
- Architecture: arm64
  InstallerUrl: https://github.com/Pixeval/Pixeval/releases/download/5.0.13/Pixeval-win-arm64-Setup.exe
  InstallerSha256: A1E766F5C3A6CCC865E50991906395D40BC246B4B5F6FFA2AC92A642E43F574F
ManifestType: installer
ManifestVersion: 1.12.0
