# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Pixeval.Pixeval
PackageVersion: 5.0.13
PackageLocale: en-US
ShortDescription: A powerful, fast and beautiful third-party Pixiv client built on .NET and Avalonia
Description: Pixeval is a feature-rich third-party Pixiv desktop client. It offers an illustrator-friendly way to browse illustrations, novels, and user profiles, with high-quality batch downloading, zoomable viewing, tag search, and bookmark management, plus dark themes and a multilingual interface.
Tags:
- pixiv
ManifestType: locale
ManifestVersion: 1.12.0
