# Created with YamlCreate.ps1 v2.5.0 $debug=NVS1.CRLF.7-5-2.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.10.0.schema.json

PackageIdentifier: GoldenSoftware.LicenseAdministrator
PackageVersion: 4.1.420
PackageLocale: zh-CN
# Publisher:
# PublisherUrl:
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
# PackageName:
# PackageUrl:
License: 专有软件
# LicenseUrl:
# Copyright:
# CopyrightUrl:
ShortDescription: 许可证管理器的用户界面。
# Description:
# Moniker:
# Tags:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: locale
ManifestVersion: 1.10.0
