# Created with YamlCreate.ps1 v2.5.0 $debug=NVS1.CRLF.7-5-2.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: GoldenSoftware.LicenseAdministrator
PackageVersion: 4.1.420
PackageLocale: en-US
Publisher: Golden Software
PublisherUrl: https://www.goldensoftware.com/
PublisherSupportUrl: https://licensehelp.goldensoftware.com/
PrivacyUrl: https://goldensoftware.com/privacy-policy/
Author: Golden Software, LLC
PackageName: License Administrator
PackageUrl: https://www.goldensoftware.com/support/download-install/
License: Proprietary
LicenseUrl: https://www.goldensoftware.com/wp-content/uploads/2024/07/GoldenSoftwareLLC_EndUserLicenseAgreement.pdf
Copyright: Copyright © 1993-2025, Golden Software, LLC
CopyrightUrl: https://www.goldensoftware.com/wp-content/uploads/2024/07/GoldenSoftwareLLC_EndUserLicenseAgreement.pdf
ShortDescription: A user interface to the license manager.
# Description:
# Moniker:
# Tags:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.10.0
