# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: DBVis.DBVisualizer
PackageVersion: 26.2.4
PackageLocale: en-US
Publisher: DbVis Software AB
PublisherUrl: https://www.dbvis.com/
PublisherSupportUrl: https://www.dbvis.com/support/
PrivacyUrl: https://www.dbvis.com/privacy/
Author: DbVis Software AB
PackageName: DbVisualizer
PackageUrl: https://www.dbvis.com/download/
License: Proprietary
LicenseUrl: https://www.dbvis.com/eula/
Copyright: Copyright 2026.
CopyrightUrl: https://www.dbvis.com/eula/
ShortDescription: DbVisualizer is the SQL Client and Database Tool with the highest user satisfaction. It connects to all popular databases and runs on Win, macOS & Linux.
Moniker: dbvis
Tags:
- database
- db2
- develop
- development
- ide
- mssql
- mysql
- postgres
- postgresql
- programming
- sql
- sqlite
ReleaseNotes: |-
  Improvements
  Command Line Support (dbviscmd)
  Support reading passwords from a file or environment variable in dbviscmd
  DB Support: Amazon Athena
  Add authentication options to the connection setup for Amazon Athena
  DB Support: MariaDB
  Add support for roles in MariaDB
  Bugs Fixed
  AI
  AI Assistant permissions may override stricter SQL Commander permissions
  Command Line Support (dbviscmd)
  Changing a password with dbviscmd leaves the old password in the password store
  DB Support: Azure SQL
  DB Support: SQL Server
  Can't connect to Azure SQL or SQL Server using an IPv6 address
  DB Support: DynamoDB
  Data tab doesn't show the current row range when paging through DynamoDB results
  DB Support: Informix
  Source code may not be available for some procedures and functions in Informix
  DB Support: Oracle
  Clone User omits grant options and Java permissions in Oracle
  Database Objects Tree
  Error when reloading a mounted connection folder
  Grid Component
  Quick search field shows too little of the search text
  Quick search highlights matches in columns excluded from the search
  Notifications
  Error during application shutdown
  Notifications triggered using @notify may appear in the wrong window
  OS Support: macOS
  Double-clicking the title bar ignores the macOS system setting
  Performance/Stability
  Error dialog can't be closed
  Procedure Editor
  Procedure editor may display incorrect source code when it contains international characters
  Procedure Editor
  SQL Commander
  Error after undo in the editor
  SQL Commander
  Error when closing a SQL Commander tab
  Tab groups in floating windows may appear empty after restart
  SSH
  Can't connect through an SSH tunnel when IPv6 is used
  SSH jump server is ignored when using SSHJ
ReleaseNotesUrl: https://www.dbvis.com/releasenotes/
PurchaseUrl: https://www.dbvis.com/buy/
Documentations:
- DocumentLabel: User Guide
  DocumentUrl: https://www.dbvis.com/docs/ug/
ManifestType: defaultLocale
ManifestVersion: 1.12.0
