# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: PTV.Visum.2026
PackageVersion: 2026.01-10
PackageLocale: en-US
Publisher: PTV Group
PublisherUrl: https://www.ptvgroup.com/
PublisherSupportUrl: https://support.ptvgroup.com/
PrivacyUrl: https://www.ptvgroup.com/en/terms-privacy
Author: PTV Planung Transport Verkehr GmbH
PackageName: PTV Visum
PackageUrl: https://www.ptvgroup.com/en/products/ptv-visum
License: Proprietary
LicenseUrl: https://www.ptvgroup.com/en/terms-privacy
Copyright: © PTV Planung Transport Verkehr GmbH
CopyrightUrl: https://www.ptvgroup.com/en/terms-privacy
ShortDescription: The leading software for multimodal transportation modeling and planning.
Description: PTV Visum is the world's leading transport planning software. It is the standard for macroscopic modelling of transport networks and transport demand, public transport planning, and for the development of transport strategies and solutions. With PTV Visum, you create transportation models that provide insights for long-term strategic planning and short-term operational use.
Tags:
- planning
- simulation
- traffic
- transport
ReleaseNotesUrl: https://cgi.ptvgroup.com/visionSetups/Setups/VISUM/260/Release%20Notes_Visum_2026.01-10_EN.pdf
ManifestType: defaultLocale
ManifestVersion: 1.12.0
