# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: PTV.Visum.2026
PackageVersion: 2026.01-10
PackageLocale: zh-CN
License: 专有软件
ShortDescription: 全球领先的交通规划软件，面向多模式交通建模与规划。
Description: PTV Visum 是世界上技术领先的交通规划软件。它是交通网络与交通需求宏观建模、公共交通规划以及交通战略与方案制定的标准软件。使用 PTV Visum 构建交通模型，可为长期战略规划和短期运营应用提供洞察。
Tags:
- 交通
- 交通模拟
- 交通规划
ManifestType: locale
ManifestVersion: 1.12.0
