# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: newdee.Magpie
PackageVersion: 0.6.5
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/newdee/magpie/releases/download/v0.6.5/magpie_0.6.5_x64-setup.exe
  InstallerSha256: BE0CCDA8FABF96B179AFC122E448DCA8C54B029255CA0434BECCAE7812CB39BF
  ProductCode: magpie
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/newdee/magpie/releases/download/v0.6.5/magpie_0.6.5_x64_en-US.msi
  InstallerSha256: 2B9A5869CFC401E91334E7D290A4EFA1A7868853EDBE33EEFCAE944276E032B4
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{0D9E6687-32DE-493C-A691-47347DCB7B20}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{285F4DB5-673C-524F-B28E-235FEC26AD24}'
ManifestType: installer
ManifestVersion: 1.12.0
