# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: 333-wg.Pi-Wm
PackageVersion: 0.1.16
InstallerType: nullsoft
ProductCode: be5eb76e-ae89-5bc1-9213-c7b407b73ba3
ReleaseDate: 2026-10-03
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\Pi-Wm'
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/333-wg/pi-wm/releases/download/v0.1.16/Pi-Wm-0.1.16-Setup-x64.exe
  InstallerSha256: 547581556e310e1a3adbee655c6e5006750b83eaa505d58e23b3e87e9551f810
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/333-wg/pi-wm/releases/download/v0.1.16/Pi-Wm-0.1.16-Setup-x64.exe
  InstallerSha256: 547581556e310e1a3adbee655c6e5006750b83eaa505d58e23b3e87e9551f810
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
