# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Frameio.FrameioDrive
PackageVersion: 1.13.0
InstallerType: nullsoft
Scope: machine
ProductCode: 9ef9ce05-1520-5942-91ce-45d9ec96f49a
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Frame.io Drive'
Installers:
- Architecture: x64
  InstallerUrl: https://drive.frame.io/releases/stable/win32/x64/Frame.io%20Drive%201.13.0%20Setup.exe
  InstallerSha256: 160FF0AB12BA9AFDD977D622FE178A39AE6572FC747983ABF7622A8DAF42CBF5
ManifestType: installer
ManifestVersion: 1.12.0
