# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BtbN.FFmpeg.GPL
PackageVersion: N-127021-ge0c94b2d1c-20260930
InstallerType: zip
NestedInstallerType: portable
Commands:
- ffmpeg
- ffplay
- ffprobe
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-win64-gpl\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-win64-gpl\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-win64-gpl\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-30-13-08/ffmpeg-N-127021-ge0c94b2d1c-win64-gpl.zip
  InstallerSha256: 85C4A4636B93D681A07588FFA6F1D8F5C064D9C3FB0622066662906B6FD718A1
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-winarm64-gpl\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-winarm64-gpl\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127021-ge0c94b2d1c-winarm64-gpl\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-30-13-08/ffmpeg-N-127021-ge0c94b2d1c-winarm64-gpl.zip
  InstallerSha256: 5E6560100382843F6BC6E163C958ED4F0F5A2E479E63FAF101B998D349915A43
ManifestType: installer
ManifestVersion: 1.12.0
