# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Creality.CrealityPrint
PackageVersion: 7.3.0
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Protocols:
- crealityprintlink
FileExtensions:
- 3mf
- cxprj
- gcode
- stl
ProductCode: CrealityPrint-7
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/CrealityOfficial/CrealityPrint/releases/download/v7.3.0/CrealityPrint_7.3.0.6157_Release.exe
  InstallerSha256: 69AB8DE07DD1B7C86A04F3D96881A9D9FD6ADD1C8AB228D87F8F11BDB528A46C
- InstallerLocale: zh-CN
  Architecture: x64
  InstallerUrl: https://file-cdn.creality.com/file/a6c16f2aa51b97c4d549e503353f41e1/CrealityPrint_7.3.0.6157_Release.exe
  InstallerSha256: 69AB8DE07DD1B7C86A04F3D96881A9D9FD6ADD1C8AB228D87F8F11BDB528A46C
ManifestType: installer
ManifestVersion: 1.12.0
