# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Readwise.Reader
PackageVersion: 0.1.3269
PackageLocale: zh-CN
License: 专有软件
ShortDescription: 首款面向重度读者的"稍后读"应用
Description: |-
  将所有内容保存到一处，克服信息过载，即时搜索，像专业人士一样标注。

  所有阅读汇聚一处。无需在几十个阅读应用之间来回切换，只需要一个：我们称之为 Reader。

  - 网页标注：使用 Reader 浏览器扩展，在开放的网页上自由划线标注。
  - RSS：在 Reader 中轻松订阅你喜爱网站的 RSS 源，不错过任何更新。
  - PDF：把 PDF 上传到 Reader，通过全文搜索彻底读完那个被遗忘的文件夹。
Tags:
- pdf
- rss
- 电子书
- 稍后阅读
ManifestType: locale
ManifestVersion: 1.12.0
