# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Readwise.Reader
PackageVersion: 0.1.3269
PackageLocale: en-US
Publisher: readwise
PublisherUrl: https://readwise.io/
PublisherSupportUrl: https://docs.readwise.io/reader
PrivacyUrl: https://readwise.io/privacy
Author: Readwise, Inc.
PackageName: Readwise Reader
PackageUrl: https://readwise.io/read
License: Proprietary
LicenseUrl: https://readwise.io/tos
Copyright: © Readwise 2026
CopyrightUrl: https://readwise.io/tos
ShortDescription: The first read-it-later app built for power readers
Description: |-
  Save everything to one place to overcome content overload, search instantly, and highlight like a pro.

  All your reading in one place. No more juggling dozens of reading apps. Just one: we call it Reader.

  - Web highlighting: freely highlight and annotate the open web using the Reader browser extension.
  - RSS: easily subscribe to the RSS feeds of your favorite websites in Reader to never miss a post.
  - PDFs: upload yours to Reader to finally get through that forgotten folder, with full-text search.
Tags:
- ebook
- pdf
- read-it-later
- rss
ReleaseNotesUrl: https://readwise.io/changelog
ManifestType: defaultLocale
ManifestVersion: 1.12.0
