# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Readwise.Reader
PackageVersion: 0.1.3269
UpgradeBehavior: install
Protocols:
- wiseread
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/readwiseio/reader-desktop-releases/releases/download/reader-desktop-v0.1.3269/Reader_0.1.3269_x64-setup.exe
  InstallerSha256: D68517C91E2F7B236EEE2BB3E4FCDD1455A5CFD7AD6A47450A7C5D0C90DFE51F
  ProductCode: Reader
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Reader'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/readwiseio/reader-desktop-releases/releases/download/reader-desktop-v0.1.3269/Reader_0.1.3269_x64_en-US.msi
  InstallerSha256: A2BB061F01A312A54825ED77B7E6CD064BB51C4514E21F96C0E02463D148F33D
  ProductCode: '{26BE7BF6-877D-4DFD-808A-602556F1109F}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{8C88C1AD-4BA2-5A3C-9E5F-45B76A862470}'
ManifestType: installer
ManifestVersion: 1.12.0
