# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JetBrains.Rider
PackageVersion: 2026.2.3
InstallerType: nullsoft
InstallerSwitches:
  Log: /LOG="<LOGPATH>"
UpgradeBehavior: uninstallPrevious
FileExtensions:
- cs
- cshtml
- csproj
- ipr
- sln
- slnf
ProductCode: JetBrains Rider 2026.2.3
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- DisplayVersion: 262.10968.135
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.jetbrains.com/rider/JetBrains.Rider-2026.2.3.exe
  InstallerSha256: ADDDE2D0D6A32FDA6447E689D2888F9579BF8A9D6730C3645AB0E4E0CB6D2483
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.jetbrains.com/rider/JetBrains.Rider-2026.2.3.exe
  InstallerSha256: ADDDE2D0D6A32FDA6447E689D2888F9579BF8A9D6730C3645AB0E4E0CB6D2483
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://download.jetbrains.com/rider/JetBrains.Rider-2026.2.3-aarch64.exe
  InstallerSha256: 040DF9451EBCE93B56C6352E6CDAD3630E5AB08A6B15DEEF3BD93F098203EBE3
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://download.jetbrains.com/rider/JetBrains.Rider-2026.2.3-aarch64.exe
  InstallerSha256: 040DF9451EBCE93B56C6352E6CDAD3630E5AB08A6B15DEEF3BD93F098203EBE3
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
