# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ProteoWizard.ProteoWizard
PackageVersion: 3.0.26279
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
ProductCode: '{86F1D983-971C-44D2-9CF2-D47B1A2AEB03}'
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- UpgradeCode: '{644795C6-012A-49B7-A47F-E46E164D3689}'
Installers:
- Architecture: x64
  InstallerUrl: https://mc-tca-01.s3.us-west-2.amazonaws.com/ProteoWizard/bt83/4203871/pwiz-setup-3.0.26279.796129c-x86_64.msi
  InstallerSha256: 90D408374ABC9458857F268FCD52018512C07C5169EBC523A3E90144351955E2
ManifestType: installer
ManifestVersion: 1.12.0
