# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ByteDance.DoubaoWork
PackageVersion: 2.32.1
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --command=quiet_install
  SilentWithProgress: --command=quiet_install
  InstallLocation: --target_dir="<INSTALLPATH>"
  Log: --log_dir="<LOGPATH>"
ProductCode: DoubaoWork
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/doubao_pc/2.32.1/DoubaoWork_installer_2.32.1.exe
  InstallerSha256: D1FBB780FAFBAE6865993ED36DFD395AFFA0DB275C216E7C8004CDEC68BF5478
- Architecture: arm64
  InstallerUrl: https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/doubao_pc/2.32.1/DoubaoWork_Arm64_installer_2.32.1.exe
  InstallerSha256: 44026D8C3139E188D0904C39C07932A38F956042B3BCA5741CF67FA0FC6194AE
ManifestType: installer
ManifestVersion: 1.12.0
