# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FlamingoAI.OpenFrameConsole
PackageVersion: 0.0.23
InstallerType: nullsoft
Scope: user
Protocols:
- openframe-console
ProductCode: OpenFrame Console
ReleaseDate: 2026-10-09
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\OpenFrame Console'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/flamingo-stack/openframe-saas-desktop/releases/download/0.0.23/OpenFrame-Console_0.0.23_x64-setup.exe
  InstallerSha256: 16B2F3F936F001C5B101C4B9E0504B4FBF6F5C547FA621A671DA2496C0DFF787
- Architecture: arm64
  InstallerUrl: https://github.com/flamingo-stack/openframe-saas-desktop/releases/download/0.0.23/OpenFrame-Console_0.0.23_arm64-setup.exe
  InstallerSha256: D763A1000D4B1A0AD68D7E339D585B12D7148734A0D414BCDDE35F72A1A4DAFE
ManifestType: installer
ManifestVersion: 1.12.0
