# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ayangweb.BongoCat
PackageVersion: 2.2.0
InstallerType: nullsoft
ProductCode: BongoCat
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/ayangweb/BongoCat/releases/download/v2.2.0/BongoCat_2.2.0_x64.exe
  InstallerSha256: 3F486A5A07416B50682E244A4E37BBB84F9E69DE2F15138EB0E90649C5F73834
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/ayangweb/BongoCat/releases/download/v2.2.0/BongoCat_2.2.0_x64.exe
  InstallerSha256: 3F486A5A07416B50682E244A4E37BBB84F9E69DE2F15138EB0E90649C5F73834
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
