# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: ayangweb.BongoCat
PackageVersion: 2.2.0
PackageLocale: zh-CN
Publisher: ayangweb
PublisherUrl: https://github.com/ayangweb
PublisherSupportUrl: https://github.com/ayangweb/BongoCat/issues
PackageName: BongoCat
PackageUrl: https://github.com/ayangweb/BongoCat
License: MIT
LicenseUrl: https://github.com/ayangweb/BongoCat/blob/HEAD/LICENSE
Copyright: Copyright (c) 2026 ayangweb
ShortDescription: "\U0001F431 跨平台桌宠 BongoCat，为桌面增添乐趣！"
Description: |-
  🐱 跨平台桌宠 BongoCat，为桌面增添乐趣！
  功能介绍
  - 适配 macOS、Windows 和 Linux (x11)。
  - 根据据键盘或鼠标操作，同步移动鼠标或敲击键盘。
  - 支持导入自定义模型，自由打造专属猫咪形象。
  - 完全开源，代码公开透明，绝不收集任何用户数据。
  - 支持离线运行，无需联网，保护用户隐私。
ReleaseNotes: |-
  ✨ 新功能
  - 新增「模型窗口 → 窗口行为 → 无操作时隐藏」配置项。
  - 新增「模型窗口 → 窗口行为 → 无操作时隐藏延迟」配置项。
  - 新增「模型窗口 → 窗口行为 → 按住修饰键进行交互」配置项。
  - 新增「输入与交互 → 鼠标 → 强制移动鼠标」配置项。
  - 新增「模型行为 → 重复触发同一表情时关闭它」配置项。
  - 「快捷键 → 模型行为快捷键」支持重命名。
  🐛 问题修复
  - 修复模型纹理边缘出现明显羽化的问题。
  - 修复部分 Bongo-Cat-Mver 模型转换后按键图显示错位的问题。
  🎨 界面
  - 将「应用与系统 → 启动与桌面 → 登录时启动」更名为「开机自启动」。
ReleaseNotesUrl: https://github.com/ayangweb/BongoCat/releases/tag/v2.2.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
