# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: ayangweb.BongoCat
PackageVersion: 2.2.0
PackageLocale: en-US
ShortDescription: "\U0001F431 Cross-platform desktop pet BongoCat, adding fun to your desktop!"
Description: |-
  🐱 Cross-platform desktop pet BongoCat, adding fun to your desktop!
  Features:
  - Compatible with macOS, Windows, and Linux (x11).
  - Synchronizes mouse movements or keyboard taps based on your keyboard or mouse actions.
  - Supports importing custom models to freely create your unique cat avatar.
  - Fully open-source with transparent code—absolutely no user data collection.
  - Works offline—no internet required, ensuring user privacy.
ReleaseNotes: |-
  ✨ Features
  - Added a "Model window → Window behavior → Hide when idle" setting.
  - Added a "Model window → Window behavior → Idle hide delay" setting.
  - Added a "Model window → Window behavior → Hold a modifier key to interact" setting.
  - Added an "Input & interaction → Mouse → Force mouse movement" setting.
  - Added a "Model behavior → Turn off an expression when triggered again" setting.
  - Added renaming support to "Shortcuts → Model behavior shortcuts".
  🐛 Bug Fixes
  - Fixed noticeable soft fringes around model texture edges.
  - Fixed misplaced key images in some converted Bongo-Cat-Mver models.
  🎨 Interface
  - Renamed "App & system → Startup & desktop → Open at login" to "Run at startup".
ManifestType: locale
ManifestVersion: 1.12.0
