# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenLogic.OpenJDK.8.JRE
PackageVersion: 8.0.502.07
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Custom: ADDLOCAL=ALL
UpgradeBehavior: install
Commands:
- java
- javaw
- jjs
- keytool
- kinit
- klist
- ktab
- orbd
- pack200
- policytool
- rmid
- rmiregistry
- servertool
- tnameserv
- unpack200
FileExtensions:
- class
- jar
- java
- jsp
ReleaseDate: 2026-08-06
Installers:
- Architecture: x64
  InstallerUrl: https://builds.openlogic.com/downloadJDK/openlogic-openjdk-jre/8u502-b07/openlogic-openjdk-jre-8u502-b07-windows-x64.msi
  InstallerSha256: 6A4909352FF96993B1AC33FCC0B47E1E5547F9F6368CD59933C7CF1950EEE287
  ProductCode: '{4AC73E04-EB9E-4E2A-B389-C40515DE6310}'
  AppsAndFeaturesEntries:
  - DisplayName: OpenLogic-OpenJDK JRE with Hotspot 8u502-b07 (x64)
    UpgradeCode: '{E7EDB6B9-3711-4879-8C10-EE5212F26E00}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\OpenLogic\jre-8.0.502.07-hotspot'
- Architecture: x86
  InstallerUrl: https://builds.openlogic.com/downloadJDK/openlogic-openjdk-jre/8u502-b07/openlogic-openjdk-jre-8u502-b07-windows-x32.msi
  InstallerSha256: 8C3833CC0DB102F99ADEC94577C92662A2847E25C3D3E8E096DFC2FEBD40E9DA
  ProductCode: '{B21BDB14-931B-4213-9568-F35BF572B2B9}'
  AppsAndFeaturesEntries:
  - DisplayName: OpenLogic-OpenJDK JRE with Hotspot 8u502-b07 (x86)
    UpgradeCode: '{F084F959-153B-4F07-B6C7-F9ACD4F56C94}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\OpenLogic\jre-8.0.502.07-hotspot'
ManifestType: installer
ManifestVersion: 1.12.0
