# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ByteDance.CapCut
PackageVersion: 9.6.0.4097
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /silent_install=1
  SilentWithProgress: /silent_install=1
  InstallLocation: /install_path="<INSTALLPATH>"
  Upgrade: /update_install
UpgradeBehavior: install
Protocols:
- capcut
ProductCode: CapCut
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://sf16-web-tos-buz.capcutstatic.com/obj/capcut-web-buz-sg/packages/CapCut_9_6_0_4097_capcutpc_0_creatortool.exe
  InstallerSha256: 16EFD5C47F7D5349A6D1BEC46FDF43F109EA63CFBD04687BE54C79F6F1626311
ManifestType: installer
ManifestVersion: 1.12.0
