# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: sodahub-org.SodaM
PackageVersion: 0.1.7
PackageLocale: en-US
ShortDescription: A native Soda Music desktop client built with GPUI and Rust.
Description: SodaM is a native Soda Music desktop client built on GPUI and libresoda for Linux, macOS, and Windows desktops. It focuses on an operating feel close to the official client, stable local playback, lossless playback for member accounts, and a clean, adaptive theme system.
Tags:
- album
- artist
- audio
- music
- player
- playlist
- soda-music
- song
- sound
ManifestType: locale
ManifestVersion: 1.12.0
