# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Jamailar.LeanFPS
PackageVersion: 0.1.147
InstallerType: inno
Scope: machine
ProductCode: '{6C0B6E8C-2F1B-4D5E-9A1F-4C1E5F0A7B21}_is1'
ReleaseDate: 2026-10-10
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\LeanFPS'
Installers:
- Architecture: x64
  InstallerUrl: https://dl.leanfps.com/windows/0.1.147/LeanFPS-Setup-0.1.147.exe
  InstallerSha256: 5FFC79BF5434679B08EE869C7980F0A80A6F9B574BDCF9C14ED42389AFB17F50
ManifestType: installer
ManifestVersion: 1.12.0
