# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Jamailar.LeanFPS
PackageVersion: 0.1.147
PackageLocale: zh-CN
ShortDescription: 适用于 Windows 10 和 11 的免费游戏优化器。
Description: LeanFPS 是一款适用于 Windows 10 和 11 的免费游戏优化器。它能识别正在运行的游戏，按游戏类型应用优化调整，测量 FPS 和 1% 最低帧率，并支持撤销每一项更改。
Tags:
- 帧率
- 性能
- 游戏
- 游戏优化
- 电竞
ManifestType: locale
ManifestVersion: 1.12.0
