# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: ALLPlayer.ALLPlayer
PackageVersion: "9.6"
PackageLocale: zh-CN
License: 免费软件
ShortDescription: 几乎支持所有格式的视频和音乐播放器。
Description: ALLPlayer 是一款 Windows 媒体播放器，支持播放几乎所有格式的视频和音乐，提供自动字幕匹配、家长控制、网络电台、语音合成以及可为字幕朗读配音的 AI 语音功能。
Tags:
- 多媒体
- 媒体
- 影音
- 播放器
- 视频
- 音乐
- 音频
ManifestType: locale
ManifestVersion: 1.12.0
