# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ALLPlayer.ALLPlayer
PackageVersion: "9.6"
InstallerType: inno
Scope: machine
FileExtensions:
- "264"
- 3g2
- 3gp
- 3gp2
- 3gpp
- aac
- ac3
- aif
- aifc
- aiff
- alac
- amr
- amv
- ape
- apl
- asf
- asx
- au
- avi
- avs
- bik
- cda
- cdk
- dat
- divx
- dts
- evo
- f4v
- flac
- flc
- flh
- fli
- flic
- flv
- hdmov
- ifo
- ivf
- k3g
- m1a
- m1v
- m2a
- m2p
- m2t
- m2ts
- m2v
- m4a
- m4b
- m4v
- mid
- midi
- mka
- mkv
- mov
- mp2
- mp2v
- mp3
- mp4
- mp4v
- mpa
- mpc
- mpe
- mpeg
- mpg
- mpv2
- mpv4
- mts
- ofr
- ofs
- oga
- ogg
- ogm
- ogv
- pv2
- qt
- r01
- ra
- ram
- rec
- rm
- rmi
- rmm
- rmvb
- rpm
- snd
- tp
- trp
- ts
- tta
- vob
- vro
- wav
- webm
- wm
- wma
- wmp
- wmv
- wpl
- wv
ProductCode: '{68972948-F221-4267-9EB6-2EB5D913C4CF}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://allplayer.com/Download/ALLPlayer.exe
  InstallerSha256: 239DEB29411CFFCC716718ED7FD16A2DB7AFA7F903C2B1CCC54B8B4BDA2D8A65
ManifestType: installer
ManifestVersion: 1.12.0
