# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: ALLPlayer.ALLPlayer
PackageVersion: "9.6"
PackageLocale: en-GB
Publisher: ALLPlayer Ltd.
PublisherUrl: https://www.allplayer.com/
PublisherSupportUrl: https://www.allplayer.com/contact
PrivacyUrl: https://www.allplayer.com/privacy-policy
Author: ALLPlayer Ltd.
PackageName: ALLPlayer
PackageUrl: https://www.allplayer.com/
License: Freeware
LicenseUrl: https://www.allplayer.com/terms-of-use
Copyright: © 2009-2026 ALLPlayer & SaraAI
CopyrightUrl: https://www.allplayer.com/terms-of-use
ShortDescription: Media player that plays videos and music in almost every format.
Description: ALLPlayer is a media player for Windows that plays video and music in almost every format. It includes automatic subtitle matching, parental control, internet radio, speech synthesis, and an AI voice-over feature that narrates subtitles.
Moniker: allplayer
Tags:
- audio
- media
- multimedia
- music
- player
- video
ManifestType: defaultLocale
ManifestVersion: 1.12.0
