# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CreakyCoss.Mewvis
PackageVersion: 0.1.0
InstallerType: nullsoft
Scope: user
ProductCode: Mewvis
ReleaseDate: 2026-10-03
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Mewvis'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/CreakyCoss/mewvis/releases/download/v0.1.0/Mewvis_0.1.0_x64-setup.exe
  InstallerSha256: 741F79317D2D93915C34C732D913ACBB7281EFE77E408FCC562C4C06C66F29D9
- Architecture: arm64
  InstallerUrl: https://github.com/CreakyCoss/mewvis/releases/download/v0.1.0/Mewvis_0.1.0_arm64-setup.exe
  InstallerSha256: C7540710CB52397492F6913C96A98FB32F13F33A490BCC748DA19102B4931F8D
ManifestType: installer
ManifestVersion: 1.12.0
