# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.DesignCraft
PackageVersion: 0.2.1
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- UpgradeCode: '{49E87D30-BB68-4896-AA1D-F45C833CFC3C}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/storytold/designcraft/releases/download/v0.2.1/designcraft-0.2.1-windows-x64.msi
  InstallerSha256: D320310C33B9E887AB5A68B76B67E63E426E909AB92E3E3F39D06C2D49697D2C
  ProductCode: '{F553A5B9-4B62-47C5-BDDF-A3D77958F008}'
- Architecture: x86
  InstallerUrl: https://github.com/storytold/designcraft/releases/download/v0.2.1/designcraft-0.2.1-windows-x86.msi
  InstallerSha256: B7612A134B28A9A7EFCE7B776BEAD75E0A17C8FA122EFE57B7F7A24A3EB2AE22
  ProductCode: '{DF272391-FAE2-4E02-B891-685256ED3E67}'
ManifestType: installer
ManifestVersion: 1.12.0
