# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Anysphere.Cursor
PackageVersion: 3.24.9
InstallerType: inno
InstallerSwitches:
  Custom: /mergetasks=!runcode
UpgradeBehavior: install
Protocols:
- cursor
FileExtensions:
- ascx
- asp
- aspx
- bash
- bash_login
- bash_logout
- bash_profile
- bashrc
- bib
- bowerrc
- c
- c++
- cc
- cfg
- cjs
- clj
- cljs
- cljx
- clojure
- cls
- cmake
- code-workspace
- coffee
- config
- containerfile
- cpp
- cs
- cshtml
- csproj
- css
- csv
- csx
- ctp
- cxx
- dart
- diff
- dockerfile
- dot
- dtd
- editorconfig
- edn
- erb
- eyaml
- eyml
- fs
- fsi
- fsscript
- fsx
- gemspec
- gitattributes
- gitconfig
- gitignore
- go
- gradle
- groovy
- h
- h++
- handlebars
- hbs
- hh
- hpp
- hxx
- ini
- ipynb
- jade
- jav
- java
- js
- jscsrc
- jshintrc
- jshtm
- json
- jsp
- jsx
- less
- log
- lua
- m
- makefile
- markdown
- md
- mdoc
- mdown
- mdtext
- mdtxt
- mdwn
- mjs
- mk
- mkd
- mkdn
- ml
- mli
- npmignore
- php
- phtml
- pl
- pl6
- plist
- pm
- pm6
- pod
- pp
- profile
- properties
- ps1
- psd1
- psgi
- psm1
- py
- pyi
- r
- rb
- rhistory
- rprofile
- rs
- rst
- rt
- sass
- scss
- sh
- shtml
- sql
- svgz
- t
- tex
- toml
- ts
- tsx
- txt
- vb
- vue
- wxi
- wxl
- wxs
- xaml
- xhtml
- xml
- yaml
- yml
- zsh
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://downloads.cursor.com/production/cd6d2a1f2e56e9841f0ed9c7c24542087b4e69be/win32/x64/user-setup/CursorUserSetup-x64-3.24.9.exe
  InstallerSha256: 3600D825EB9C21DC703004B7D2838ECB1017CDD1305AC1E5F618B2FA54E49E43
  ProductCode: '{DADADADA-ADAD-ADAD-ADAD-ADADADADADAD}}_is1'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://downloads.cursor.com/production/cd6d2a1f2e56e9841f0ed9c7c24542087b4e69be/win32/x64/system-setup/CursorSetup-x64-3.24.9.exe
  InstallerSha256: 289577AD7586E55DAF74BE676A35864DF6C3F19B027AC1F9AEA1EC59878D35B8
  ProductCode: '{D7D7D7D7-7D7D-7D7D-7D7D-7D7D7D7D7D7D}}_is1'
- Architecture: arm64
  Scope: user
  InstallerUrl: https://downloads.cursor.com/production/cd6d2a1f2e56e9841f0ed9c7c24542087b4e69be/win32/arm64/user-setup/CursorUserSetup-arm64-3.24.9.exe
  InstallerSha256: ABDB8B0650EC29D64D46DAEECCE7E072C6D55B1FAEBC9E1CAC6A71E16DDB7FC4
  ProductCode: '{DBDBDBDB-BDBD-BDBD-BDBD-BDBDBDBDBDBD}}_is1'
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://downloads.cursor.com/production/cd6d2a1f2e56e9841f0ed9c7c24542087b4e69be/win32/arm64/system-setup/CursorSetup-arm64-3.24.9.exe
  InstallerSha256: AE9FDB0C666A15107710E994980EC0CC1D845EEEE7A58029705A78FD26CD2DE3
  ProductCode: '{D8D8D8D8-8D8D-8D8D-8D8D-8D8D8D8D8D8D}}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
