# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Elisa
PackageVersion: 26.11.70
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: Elisa
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/multimedia/elisa/master/windows/elisa-master-4610-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: ED12CDD4FA646A7D9A118018DFE06DFE8F90382E3DDB195EDB340FF3DE4BC0AA
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/multimedia/elisa/master/windows/elisa-master-4610-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: ED12CDD4FA646A7D9A118018DFE06DFE8F90382E3DDB195EDB340FF3DE4BC0AA
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
