# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ImageMagick.ImageMagick
PackageVersion: 7.1.2.32
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Commands:
- compare
- composite
- conjure
- identify
- magick
- mogrify
- montage
- stream
ReleaseDate: 2026-09-27
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-32/ImageMagick-7.1.2-32-Q16-HDRI-x86-dll.exe
  InstallerSha256: C9480768C78377C53824204F6F87090039544DB7FA6F7A40658829580E0C03BD
  ProductCode: ImageMagick 7.1.2 Q16-HDRI (32-bit)_is1
- Architecture: x64
  InstallerUrl: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-32/ImageMagick-7.1.2-32-Q16-HDRI-x64-dll.exe
  InstallerSha256: 646486FCDFAC4EB57A07EB69817A0F63EF505711109775B0C7A573119600AD4E
  ProductCode: ImageMagick 7.1.2 Q16-HDRI (64-bit)_is1
- Architecture: arm64
  InstallerUrl: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-32/ImageMagick-7.1.2-32-Q16-HDRI-arm64-dll.exe
  InstallerSha256: 12B716E51FDE779EF0F59A0C201310ADB43E2FB47285ADE0C8307E3BA4E3273E
  ProductCode: ImageMagick 7.1.2 Q16-HDRI (arm64)_is1
ManifestType: installer
ManifestVersion: 1.12.0
