# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ImageMagick.ImageMagick
PackageVersion: 7.1.2.33
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Commands:
- compare
- composite
- conjure
- identify
- magick
- mogrify
- montage
- stream
ReleaseDate: 2026-10-10
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-33/ImageMagick-7.1.2-33-Q16-HDRI-x86-dll.exe
  InstallerSha256: 13625211BF492BEDCC08174514C2893F4DE6752514363E9BBB0C3A7B1D05A01B
  ProductCode: ImageMagick 7.1.2 Q16-HDRI (32-bit)_is1
- Architecture: x64
  InstallerUrl: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-33/ImageMagick-7.1.2-33-Q16-HDRI-x64-dll.exe
  InstallerSha256: E5F1E14F8520B3720E626185700489FE4267026611834D74FBF4CD598FFA0788
  ProductCode: ImageMagick 7.1.2 Q16-HDRI (64-bit)_is1
- Architecture: arm64
  InstallerUrl: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-33/ImageMagick-7.1.2-33-Q16-HDRI-arm64-dll.exe
  InstallerSha256: 19684760480510C77F3AF5FBAE67917D6C1E1E6269B218144150E644A132DCEF
  ProductCode: ImageMagick 7.1.2 Q16-HDRI (arm64)_is1
ManifestType: installer
ManifestVersion: 1.12.0
