# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PrimateLabs.Geekbench.7
PackageVersion: 7.1.0
InstallerType: nullsoft
Scope: machine
ProductCode: Geekbench 7
ReleaseDate: 2026-09-18
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Geekbench 7'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.geekbench.com/Geekbench-7.1.0-WindowsSetup.exe
  InstallerSha256: 0A388E786DE3978D57E28561FEE4E1703C312853FAAF79DCC8690CC225885669
- Architecture: arm64
  InstallerUrl: https://cdn.geekbench.com/Geekbench-7.1.0-WindowsSetup.exe
  InstallerSha256: 0A388E786DE3978D57E28561FEE4E1703C312853FAAF79DCC8690CC225885669
ManifestType: installer
ManifestVersion: 1.12.0
