# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: PrimateLabs.Geekbench.7
PackageVersion: 7.1.0
PackageLocale: zh-CN
License: 专有软件
ShortDescription: 测量你设备的 CPU 和 GPU 性能。
Description: Geekbench 7 是一款跨平台基准测试软件，只需按一下按钮即可测量系统性能。Geekbench 7 提供全新和改进的 CPU 与 GPU 工作负载，模拟真实世界的任务和应用；新增测量 CPU 处理音频、视频编码、解码与处理的媒体工作负载，并重新设计了包含全新图像编辑与合成测试的 GPU 基准测试。你的电脑在重负载下表现如何？与市面上的最新设备相比又如何？立即用 Geekbench 7 一探究竟。
Tags:
- 基准测试
- 性能测试
- 跑分
Documentations:
- DocumentLabel: CPU 工作负载
  DocumentUrl: https://www.geekbench.com/doc/geekbench7-cpu-workloads.pdf
- DocumentLabel: GPU 工作负载
  DocumentUrl: https://www.geekbench.com/doc/geekbench7-gpu-workloads.pdf
ManifestType: locale
ManifestVersion: 1.12.0
