# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: PrimateLabs.Geekbench.7
PackageVersion: 7.1.0
PackageLocale: en-US
Publisher: Primate Labs Inc.
PublisherUrl: https://www.primatelabs.com/
PublisherSupportUrl: https://support.primatelabs.com/
PrivacyUrl: https://www.primatelabs.com/legal/privacy.html
Author: Primate Labs Inc.
PackageName: Geekbench 7
PackageUrl: https://www.geekbench.com/
License: Proprietary
LicenseUrl: https://www.primatelabs.com/legal/eula-v7.html
Copyright: © 2004-2026 Primate Labs Inc.
CopyrightUrl: https://www.primatelabs.com/legal/eula-v7.html
ShortDescription: Measures your device's CPU and GPU performance.
Description: Geekbench 7 is a cross-platform benchmark that measures your system's performance with the press of a button. Geekbench 7 features new and improved CPU and GPU workloads that model real-world tasks and applications, new media workloads that measure how well your CPU handles audio and video encoding, decoding, and processing, and a redesigned GPU benchmark with new image editing and synthesis tests. How will your computer perform when push comes to crunch? How will it compare to the newest devices on the market? Find out today with Geekbench 7.
Moniker: geekbench7
Tags:
- analysis
- benchmark
- cpu-benchmark
- gpu-benchmark
- graphics-test
- performance-measure
- system-benchmark
ReleaseNotes: '- Initial release.'
ReleaseNotesUrl: https://www.primatelabs.com/release/geekbench7/
PurchaseUrl: https://www.geekbench.com/editions/
Documentations:
- DocumentLabel: CPU Workloads
  DocumentUrl: https://www.geekbench.com/doc/geekbench7-cpu-workloads.pdf
- DocumentLabel: GPU Workloads
  DocumentUrl: https://www.geekbench.com/doc/geekbench7-gpu-workloads.pdf
ManifestType: defaultLocale
ManifestVersion: 1.12.0
