# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Alibaba.Quark
PackageVersion: 4.3.5.479
InstallerType: inno
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- mhtml
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: '{FB7670C2-7F99-426D-B687-21BB585A5C73}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://umcdn.quark.cn/download/37212/quarkpc/pcquark@homepage_oficial/QuarkPC_V4.3.5.479_pc_pf30002_(zh-cn)_release_(Build2370570-250815175717-x64).exe
  InstallerSha256: FC198760181AF44ABC5E1FAC443480D2FFCC332E2DD3D6492347C2E8DECB3BFA
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://umcdn.quark.cn/download/37212/quarkpc/pcquark@homepage_oficial/QuarkPC_V4.3.5.479_pc_pf30002_(zh-cn)_release_(Build2370570-250815175717-x64).exe
  InstallerSha256: FC198760181AF44ABC5E1FAC443480D2FFCC332E2DD3D6492347C2E8DECB3BFA
  InstallerSwitches:
    Custom: /ALLUSERS
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Quark'
ManifestType: installer
ManifestVersion: 1.10.0
