# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Anthropic.Claude
PackageVersion: 2.31226.0
Protocols:
- claude
ReleaseDate: 2026-10-08
Installers:
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://downloads.claude.ai/releases/win32/x64/2.31226.0/Claude-eb794d1033f2a59c2cd89aa29ed1f8b5de12aa73.msix
  InstallerSha256: 36F2B8A07F76672FE0C796D50B43DCDB2EFF0E815F2AE9EC634A068B9AF11B8B
  SignatureSha256: F7FB0E49E02602BEFAB0CD61E5DC242CB03D9802760DCC3B97BA2AFBB405E382
  PackageFamilyName: Claude_pzs8sxrjxfjjc
  Capabilities:
  - internetClient
  RestrictedCapabilities:
  - localSystemServices
  - packagedServices
  - runFullTrust
  - unvirtualizedResources
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://downloads.claude.ai/releases/win32/arm64/2.31226.0/Claude-eb794d1033f2a59c2cd89aa29ed1f8b5de12aa73.msix
  InstallerSha256: 53570BDB1BC671EFE80F170316E00CF6B50BCA4FBB1F228748A2602A84DF7501
  SignatureSha256: 2D807A15E3AE9821DAE123BEAC2856F6E6282F300C0705C98599B4A599CB7068
  PackageFamilyName: Claude_pzs8sxrjxfjjc
  Capabilities:
  - internetClient
  RestrictedCapabilities:
  - localSystemServices
  - packagedServices
  - runFullTrust
  - unvirtualizedResources
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.claude.ai/releases/win32/x64/2.31226.0/Claude-eb794d1033f2a59c2cd89aa29ed1f8b5de12aa73.exe
  InstallerSha256: EDDBB3B9A31A4AB017EB2CB9EEA804EAF3BB6CE6D74B2227A3E7A31A7846780F
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
  ProductCode: AnthropicClaude
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.claude.ai/releases/win32/arm64/2.31226.0/Claude-eb794d1033f2a59c2cd89aa29ed1f8b5de12aa73.exe
  InstallerSha256: 5A5D1CC9D9B02C010B1B9A3BA63E2BC726CFCF2BE3A043AA9A258CEC4B020639
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
  ProductCode: AnthropicClaude
ManifestType: installer
ManifestVersion: 1.12.0
