# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.1.0.schema.json

PackageIdentifier: Contoso.Contoso
PackageVersion: Contoso
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.1.0
