# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Contoso.Contoso
PackageVersion: Contoso
InstallerSwitches:
  Silent: -silent
  SilentWithProgress: -silent # -auto
  InstallLocation: -installpath:"<INSTALLPATH>"
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://res06.bignox.com/full/20210909/8490e0989cd34113bc1bf29513f8b05a.exe
  InstallerSha256: 4529C69A2CCD1382700802EC4788C028FE76D1CD9CE86BF790BFDA3183346046
ManifestType: installer
ManifestVersion: 1.1.0
