# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.FilmCraft
PackageVersion: 0.2.1
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- UpgradeCode: '{31E6FB14-9DBC-41DD-B24B-26B71FB31B62}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/storytold/filmcraft/releases/download/v0.2.1/filmcraft-0.2.1-windows-x64.msi
  InstallerSha256: CFE73EEA4523A8EE896B4888A7208158B22506A73BD08F811C2880596BBAD503
  ProductCode: '{B450CF2A-BE6A-4CFC-96AD-24FD9343F2B2}'
- Architecture: x86
  InstallerUrl: https://github.com/storytold/filmcraft/releases/download/v0.2.1/filmcraft-0.2.1-windows-x86.msi
  InstallerSha256: DB4988F87E8B27C23BCDA3E8A2B4E1222462A683F230E584D65AC8E3133A83FB
  ProductCode: '{F1EFB067-9045-4AE5-B239-1606E59A983E}'
ManifestType: installer
ManifestVersion: 1.12.0
