# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Delinea.ThycoticLocalSecurityAgent
PackageVersion: 13.0.1058
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-10-02
AppsAndFeaturesEntries:
- UpgradeCode: '{16A921FF-12EE-4C8D-AE3B-0E9D0BAAA0E1}'
Installers:
- Architecture: x64
  InstallerUrl: https://tmsnuget.thycotic.com/software/Agents/Delinea_LocalSecurityAgent_x64_13_0_1058.msi
  InstallerSha256: 7484F8D710C536BEAF90F9761C1D5361B582310AB8C367F557C6FDDA1406BC10
  ProductCode: '{74E3C58A-704B-497F-A80C-D66C58D47EE8}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Thycotic\Agents\LocalSecurity\.'
- Architecture: arm64
  InstallerUrl: https://tmsnuget.thycotic.com/software/Agents/Delinea_LocalSecurityAgent_ARM64_13_0_1058.msi
  InstallerSha256: 604D40E8ED0E912E3F04CE923E52894D25F0C8B14CEA4706647BBA333B50DC2D
  ProductCode: '{3F434FD0-6A4C-4330-9727-5AE8D32885DA}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\Thycotic\Agents\LocalSecurity\.'
ManifestType: installer
ManifestVersion: 1.12.0
