# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Alibaba.UC
PackageVersion: 1.1.0.23
InstallerType: inno
Protocols:
- http
- https
- mailto
- tel
- uclink
FileExtensions:
- htm
- html
- mhtml
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: '{EA3A6E38-AFD7-4538-A748-4B43425F42D5}_is1'
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://pdds.ucweb.com/download/stfile/qqwwtyrtuqruqszzk/UCWin_V1.1.0.23_windows_pf5003_(zh-cn)_release_(Build20260923123058).exe
  InstallerSha256: 348F428D91BB1124C3B220E53EB66E4AB5101AD676B9618F2FD00F084A161E9C
  InstallerSwitches:
    Custom: /CURRENTUSER
  ReleaseDate: 2026-10-08
- Architecture: x64
  Scope: machine
  InstallerUrl: https://pdds.ucweb.com/download/stfile/qqwwtyrtuqruqszzk/UCWin_V1.1.0.23_windows_pf5003_(zh-cn)_release_(Build20260923123058).exe
  InstallerSha256: 348F428D91BB1124C3B220E53EB66E4AB5101AD676B9618F2FD00F084A161E9C
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
