# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ZhipuAI.ZCode
PackageVersion: 3.14.4
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- zcode
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: 268ce9e6-a30b-5890-ad18-d4b3ebba5377
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn-zcode.z.ai/zcode/electron/releases/3.14.4/windows-x64/ZCode-3.14.4-win-x64.exe
  InstallerSha256: 52972D6AC1AA189F0B89163C76AB6963814B45EB256A151B2ED04F32546E256B
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn-zcode.z.ai/zcode/electron/releases/3.14.4/windows-x64/ZCode-3.14.4-win-x64.exe
  InstallerSha256: 52972D6AC1AA189F0B89163C76AB6963814B45EB256A151B2ED04F32546E256B
  InstallerSwitches:
    Custom: /allusers
- Architecture: arm64
  Scope: user
  InstallerUrl: https://cdn-zcode.z.ai/zcode/electron/releases/3.14.4/windows-arm64/ZCode-3.14.4-win-arm64.exe
  InstallerSha256: E349E6DB9CF9DD10E3E7BC0861C65DDDCC08DF2E25CD2E7E117A91425030E2CA
  InstallerSwitches:
    Custom: /currentuser
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://cdn-zcode.z.ai/zcode/electron/releases/3.14.4/windows-arm64/ZCode-3.14.4-win-arm64.exe
  InstallerSha256: E349E6DB9CF9DD10E3E7BC0861C65DDDCC08DF2E25CD2E7E117A91425030E2CA
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
