# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.DartSDK
PackageVersion: 3.13.5
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: dart-sdk\bin\dart.exe
  PortableCommandAlias: dart
- RelativeFilePath: dart-sdk\bin\dartaotruntime.exe
  PortableCommandAlias: dartaotruntime
ReleaseDate: 2026-09-29
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://storage.googleapis.com/dart-archive/channels/stable/release/3.13.5/sdk/dartsdk-windows-x64-release.zip
  InstallerSha256: AED8E4A8932CE8FA18EA32F990E43B4A1C9390A4C73777AB6FDF77FC9F4524D1
- Architecture: arm64
  InstallerUrl: https://storage.googleapis.com/dart-archive/channels/stable/release/3.13.5/sdk/dartsdk-windows-arm64-release.zip
  InstallerSha256: E7DF6DB651743440194DF9E90005F70700DA171BCFB8852DD7CC26303792A09B
ManifestType: installer
ManifestVersion: 1.12.0
