# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: yetone.Confirmo
PackageVersion: 1.0.96
PackageLocale: zh-CN
License: 免费软件
ShortDescription: 面向 Claude Code 用户的桌面宠物与 AI 编程伴侣。
Description: Confirmo 是一款为 Claude Code 用户开发的桌面宠物，也是生活在桌面上的 AI 编程伴侣。
Tags:
- claude-code
- 桌宠
ManifestType: locale
ManifestVersion: 1.12.0
