# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RebonAI.RebonDesktop
PackageVersion: 1.11.0
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: Rebon
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/RebonAI/Rebon-Code/releases/download/app-v1.11.0/Rebon_1.11.0_x64-setup.exe
  InstallerSha256: 72EA1CFF7E483ABD15B43DF9EA7EB240F941CB839298BF7CB01DEB231869085C
ManifestType: installer
ManifestVersion: 1.12.0
